// Flashcards QPUC - Packs de révision
const FLASHCARD_PACKS = [
  {
    id: "chefs-lieux",
    name: "Chefs-lieux des départements",
    icon: "🏛️",
    description: "Les 101 préfectures de France",
    difficulty: "debutant",
    cards: [
      { front: "Ain (01)", back: "Bourg-en-Bresse" },
      { front: "Aisne (02)", back: "Laon" },
      { front: "Allier (03)", back: "Moulins" },
      { front: "Alpes-de-Haute-Provence (04)", back: "Digne-les-Bains" },
      { front: "Hautes-Alpes (05)", back: "Gap" },
      { front: "Alpes-Maritimes (06)", back: "Nice" },
      { front: "Ardèche (07)", back: "Privas" },
      { front: "Ardennes (08)", back: "Charleville-Mézières" },
      { front: "Ariège (09)", back: "Foix" },
      { front: "Aube (10)", back: "Troyes" },
      { front: "Aude (11)", back: "Carcassonne" },
      { front: "Aveyron (12)", back: "Rodez" },
      { front: "Bouches-du-Rhône (13)", back: "Marseille" },
      { front: "Calvados (14)", back: "Caen" },
      { front: "Cantal (15)", back: "Aurillac" },
      { front: "Charente (16)", back: "Angoulême" },
      { front: "Charente-Maritime (17)", back: "La Rochelle" },
      { front: "Cher (18)", back: "Bourges" },
      { front: "Corrèze (19)", back: "Tulle" },
      { front: "Corse-du-Sud (2A)", back: "Ajaccio" },
      { front: "Haute-Corse (2B)", back: "Bastia" },
      { front: "Côte-d'Or (21)", back: "Dijon" },
      { front: "Côtes-d'Armor (22)", back: "Saint-Brieuc" },
      { front: "Creuse (23)", back: "Guéret" },
      { front: "Dordogne (24)", back: "Périgueux" },
      { front: "Doubs (25)", back: "Besançon" },
      { front: "Drôme (26)", back: "Valence" },
      { front: "Eure (27)", back: "Évreux" },
      { front: "Eure-et-Loir (28)", back: "Chartres" },
      { front: "Finistère (29)", back: "Quimper" },
      { front: "Gard (30)", back: "Nîmes" },
      { front: "Haute-Garonne (31)", back: "Toulouse" },
      { front: "Gers (32)", back: "Auch" },
      { front: "Gironde (33)", back: "Bordeaux" },
      { front: "Hérault (34)", back: "Montpellier" },
      { front: "Ille-et-Vilaine (35)", back: "Rennes" },
      { front: "Indre (36)", back: "Châteauroux" },
      { front: "Indre-et-Loire (37)", back: "Tours" },
      { front: "Isère (38)", back: "Grenoble" },
      { front: "Jura (39)", back: "Lons-le-Saunier" },
      { front: "Landes (40)", back: "Mont-de-Marsan" },
      { front: "Loir-et-Cher (41)", back: "Blois" },
      { front: "Loire (42)", back: "Saint-Étienne" },
      { front: "Haute-Loire (43)", back: "Le Puy-en-Velay" },
      { front: "Loire-Atlantique (44)", back: "Nantes" },
      { front: "Loiret (45)", back: "Orléans" },
      { front: "Lot (46)", back: "Cahors" },
      { front: "Lot-et-Garonne (47)", back: "Agen" },
      { front: "Lozère (48)", back: "Mende" },
      { front: "Maine-et-Loire (49)", back: "Angers" },
      { front: "Manche (50)", back: "Saint-Lô" },
      { front: "Marne (51)", back: "Châlons-en-Champagne" },
      { front: "Haute-Marne (52)", back: "Chaumont" },
      { front: "Mayenne (53)", back: "Laval" },
      { front: "Meurthe-et-Moselle (54)", back: "Nancy" },
      { front: "Meuse (55)", back: "Bar-le-Duc" },
      { front: "Morbihan (56)", back: "Vannes" },
      { front: "Moselle (57)", back: "Metz" },
      { front: "Nièvre (58)", back: "Nevers" },
      { front: "Nord (59)", back: "Lille" },
      { front: "Oise (60)", back: "Beauvais" },
      { front: "Orne (61)", back: "Alençon" },
      { front: "Pas-de-Calais (62)", back: "Arras" },
      { front: "Puy-de-Dôme (63)", back: "Clermont-Ferrand" },
      { front: "Pyrénées-Atlantiques (64)", back: "Pau" },
      { front: "Hautes-Pyrénées (65)", back: "Tarbes" },
      { front: "Pyrénées-Orientales (66)", back: "Perpignan" },
      { front: "Bas-Rhin (67)", back: "Strasbourg" },
      { front: "Haut-Rhin (68)", back: "Colmar" },
      { front: "Rhône (69)", back: "Lyon" },
      { front: "Haute-Saône (70)", back: "Vesoul" },
      { front: "Saône-et-Loire (71)", back: "Mâcon" },
      { front: "Sarthe (72)", back: "Le Mans" },
      { front: "Savoie (73)", back: "Chambéry" },
      { front: "Haute-Savoie (74)", back: "Annecy" },
      { front: "Paris (75)", back: "Paris" },
      { front: "Seine-Maritime (76)", back: "Rouen" },
      { front: "Seine-et-Marne (77)", back: "Melun" },
      { front: "Yvelines (78)", back: "Versailles" },
      { front: "Deux-Sèvres (79)", back: "Niort" },
      { front: "Somme (80)", back: "Amiens" },
      { front: "Tarn (81)", back: "Albi" },
      { front: "Tarn-et-Garonne (82)", back: "Montauban" },
      { front: "Var (83)", back: "Toulon" },
      { front: "Vaucluse (84)", back: "Avignon" },
      { front: "Vendée (85)", back: "La Roche-sur-Yon" },
      { front: "Vienne (86)", back: "Poitiers" },
      { front: "Haute-Vienne (87)", back: "Limoges" },
      { front: "Vosges (88)", back: "Épinal" },
      { front: "Yonne (89)", back: "Auxerre" },
      { front: "Territoire de Belfort (90)", back: "Belfort" },
      { front: "Essonne (91)", back: "Évry-Courcouronnes" },
      { front: "Hauts-de-Seine (92)", back: "Nanterre" },
      { front: "Seine-Saint-Denis (93)", back: "Bobigny" },
      { front: "Val-de-Marne (94)", back: "Créteil" },
      { front: "Val-d'Oise (95)", back: "Cergy" },
      { front: "Guadeloupe (971)", back: "Basse-Terre" },
      { front: "Martinique (972)", back: "Fort-de-France" },
      { front: "Guyane (973)", back: "Cayenne" },
      { front: "La Réunion (974)", back: "Saint-Denis" },
      { front: "Mayotte (976)", back: "Mamoudzou" },
    ],
  },
  {
    id: "termes-medicaux",
    name: "Termes médicaux",
    icon: "🩺",
    description: "Suffixes, inflammations et vocabulaire médical",
    difficulty: "expert",
    cards: [
      { front: "Inflammation de l'estomac", back: "Gastrite" },
      { front: "Inflammation du foie", back: "Hépatite" },
      { front: "Inflammation du péricarde", back: "Péricardite" },
      { front: "Inflammation de la vésicule biliaire", back: "Cholécystite" },
      { front: "Inflammation des méninges", back: "Méningite" },
      { front: "Inflammation du pancréas", back: "Pancréatite" },
      { front: "Inflammation de la plèvre", back: "Pleurésie (pleurite)" },
      { front: "Inflammation de l'appendice", back: "Appendicite" },
      { front: "Inflammation des articulations", back: "Arthrite" },
      { front: "Inflammation du larynx", back: "Laryngite" },
      { front: "Inflammation du pharynx", back: "Pharyngite" },
      { front: "Inflammation des bronches", back: "Bronchite" },
      { front: "Inflammation de la peau (derme)", back: "Dermatite" },
      { front: "Inflammation de l'oreille", back: "Otite" },
      { front: "Inflammation des gencives", back: "Gingivite" },
      { front: "Inflammation de la conjonctive de l'oeil", back: "Conjonctivite" },
      { front: "Inflammation de la vessie", back: "Cystite" },
      { front: "Inflammation du côlon", back: "Colite" },
      { front: "Inflammation des reins (néphrons)", back: "Néphrite" },
      { front: "Inflammation du myocarde", back: "Myocardite" },
      { front: "Douleurs pendant les règles", back: "Dysménorrhée" },
      { front: "Absence de règles", back: "Aménorrhée" },
      { front: "Ablation chirurgicale de l'appendice", back: "Appendicectomie" },
      { front: "Ablation chirurgicale de la rate", back: "Splénectomie" },
      { front: "Ablation chirurgicale de l'utérus", back: "Hystérectomie" },
      { front: "Ablation chirurgicale de l'estomac", back: "Gastrectomie" },
      { front: "Examen visuel de l'intérieur de l'estomac", back: "Gastroscopie" },
      { front: "Examen visuel de l'intérieur du côlon", back: "Coloscopie" },
      { front: "Mesure de l'activité électrique du cœur", back: "Électrocardiogramme (ECG)" },
      { front: "Mesure de l'activité électrique du cerveau", back: "Électroencéphalogramme (EEG)" },
      { front: "Mesure de l'activité des muscles", back: "Électromyogramme (EMG)" },
      { front: "Suffixe -algie signifie...", back: "Douleur (névralgie, lombalgie)" },
      { front: "Suffixe -ectomie signifie...", back: "Ablation (appendicectomie)" },
      { front: "Suffixe -ite signifie...", back: "Inflammation (gastrite)" },
      { front: "Suffixe -ose signifie...", back: "Maladie dégénérative (arthrose)" },
      { front: "Suffixe -scopie signifie...", back: "Examen visuel (endoscopie)" },
      { front: "Suffixe -tomie signifie...", back: "Incision (trachéotomie)" },
      { front: "Suffixe -pathie signifie...", back: "Maladie (neuropathie)" },
      { front: "Suffixe -émie signifie...", back: "Relatif au sang (anémie, glycémie)" },
      { front: "Préfixe brady- signifie...", back: "Lent (bradycardie)" },
      { front: "Préfixe tachy- signifie...", back: "Rapide (tachycardie)" },
      { front: "Préfixe dys- signifie...", back: "Difficulté, trouble (dyspnée, dyslexie)" },
    ],
  },
  {
    id: "figures-style",
    name: "Figures de style",
    icon: "✒️",
    description: "Rhétorique et procédés littéraires",
    difficulty: "expert",
    cards: [
      { front: "Atténuation d'une idée pour en renforcer l'effet\nEx : « Va, je ne te hais point »", back: "Litote" },
      { front: "Répétition d'un mot en tête de plusieurs phrases\nEx : « Moi président... Moi président... »", back: "Anaphore" },
      { front: "Exagération volontaire\nEx : « Je meurs de faim »", back: "Hyperbole" },
      { front: "Dire le contraire de ce qu'on pense\nEx : « Quel beau temps ! » sous la pluie", back: "Ironie (antiphrase)" },
      { front: "Rapprochement de deux termes sans outil de comparaison\nEx : « Cette faucille d'or dans le champ des étoiles »", back: "Métaphore" },
      { front: "Rapprochement avec un outil de comparaison (comme, tel)\nEx : « Fort comme un lion »", back: "Comparaison" },
      { front: "Atténuation d'une réalité désagréable\nEx : « Il nous a quittés » pour « il est mort »", back: "Euphémisme" },
      { front: "Remplacement d'un mot par un autre ayant un lien logique\nEx : « Boire un verre » (le contenant pour le contenu)", back: "Métonymie" },
      { front: "Partie pour le tout ou le tout pour la partie\nEx : « Les voiles » pour les bateaux", back: "Synecdoque" },
      { front: "Attribution de qualités humaines à un objet/animal\nEx : « Le vent gémit »", back: "Personnification" },
      { front: "Rapprochement de deux termes opposés\nEx : « Cette obscure clarté qui tombe des étoiles »", back: "Oxymore" },
      { front: "Opposition de deux idées dans une phrase\nEx : « Tel qui rit vendredi, dimanche pleurera »", back: "Antithèse" },
      { front: "Répétition d'un même son consonantique\nEx : « Pour qui sont ces serpents qui sifflent... »", back: "Allitération" },
      { front: "Répétition d'un même son vocalique\nEx : « Les sanglots longs des violons »", back: "Assonance" },
      { front: "Mot dont le son imite la chose désignée\nEx : « coucou », « crac », « murmure »", back: "Onomatopée" },
      { front: "Inversion de l'ordre normal des mots\nEx : « Du sénat romain la puissance »", back: "Hyperbate (ou inversion)" },
      { front: "Construction identique de deux phrases\nEx : « Ni vu ni connu »", back: "Parallélisme" },
      { front: "Répétition d'un mot à la fin de plusieurs vers/phrases", back: "Épiphore" },
      { front: "Figure où l'on feint de ne pas vouloir dire ce que l'on dit pourtant\nEx : « Je ne dirai pas que... »", back: "Prétérition" },
      { front: "Question posée sans attendre de réponse\nEx : « Sommes-nous des bêtes ? »", back: "Question rhétorique" },
      { front: "Gradation ascendante ou descendante\nEx : « Va, cours, vole et nous venge ! »", back: "Gradation" },
      { front: "Accumulation de termes\nEx : « Adieu veau, vache, cochon, couvée »", back: "Énumération" },
      { front: "Phrase dont la construction est volontairement rompue\nEx : « Moi, la grammaire, ça me fatigue »", back: "Anacoluthe" },
      { front: "Suppression d'un mot de liaison entre deux propositions\nEx : « Je suis venu, j'ai vu, j'ai vaincu »", back: "Asyndète" },
      { front: "Répétition insistante d'un mot dans une même phrase\nEx : « Paris, Paris outragé, Paris brisé, Paris martyrisé »", back: "Épanaphore (ou anaphore rhétorique)" },
    ],
  },
  {
    id: "botanique",
    name: "Vocabulaire botanique",
    icon: "🌿",
    description: "Termes techniques de botanique",
    difficulty: "intermediaire",
    cards: [
      { front: "Fruit charnu à noyau (cerise, pêche, olive)", back: "Drupe" },
      { front: "Fruit sec qui s'ouvre à maturité (haricot, pois)", back: "Gousse (ou légume)" },
      { front: "Fruit sec indéhiscent à une seule graine (blé, maïs)", back: "Caryopse" },
      { front: "Fruit sec à coque dure (noix, noisette)", back: "Akène (ou nucule)" },
      { front: "Tissu conducteur de la sève brute (racines → feuilles)", back: "Xylème" },
      { front: "Tissu conducteur de la sève élaborée (feuilles → reste)", back: "Phloème" },
      { front: "Dispersion des graines par le vent", back: "Anémochorie" },
      { front: "Dispersion des graines par les animaux", back: "Zoochorie" },
      { front: "Dispersion des graines par l'eau", back: "Hydrochorie" },
      { front: "Dispersion des graines par la plante elle-même", back: "Autochorie (ou ballochorie)" },
      { front: "Organisme dont l'appareil reproducteur n'est pas apparent (algues, mousses)", back: "Cryptogame" },
      { front: "Plante dont l'appareil reproducteur est visible (fleurs)", back: "Phanérogame" },
      { front: "Plante à fleurs dont les graines sont enfermées dans un fruit", back: "Angiosperme" },
      { front: "Plante dont les graines sont nues (pins, sapins)", back: "Gymnosperme" },
      { front: "Plante qui vit sur une autre sans la parasiter (orchidée, mousse)", back: "Épiphyte" },
      { front: "Plante qui pousse dans les milieux secs", back: "Xérophyte" },
      { front: "Plante qui pousse les pieds dans l'eau", back: "Hydrophyte" },
      { front: "Plante grimpante ligneuse (vigne, lierre)", back: "Liane" },
      { front: "Arbre dont les fleurs poussent directement sur le tronc", back: "Cauliflore" },
      { front: "Ensemble des pétales d'une fleur", back: "Corolle" },
      { front: "Ensemble des sépales d'une fleur", back: "Calice" },
      { front: "Organe mâle de la fleur (filet + anthère)", back: "Étamine" },
      { front: "Organe femelle de la fleur (stigmate + style + ovaire)", back: "Pistil" },
      { front: "Plante qui vit deux ans", back: "Bisannuelle" },
      { front: "Plante qui perd ses feuilles en hiver", back: "Caduque (ou caducifoliée)" },
      { front: "Plante qui garde ses feuilles toute l'année", back: "Sempervirente (persistante)" },
      { front: "Trigonelle, dont le nom vient du « foin grec »", back: "Fenugrec" },
      { front: "Arbre méditerranéen dont le bois sert pour les manches d'outils", back: "Micocoulier" },
      { front: "Classification des plantes à fleurs établie par un botaniste américain", back: "Classification de Cronquist" },
    ],
  },
  {
    id: "vins-cepages",
    name: "Vins et cépages",
    icon: "🍷",
    description: "Appellations, cépages et vignobles français",
    difficulty: "intermediaire",
    cards: [
      { front: "Seul cépage autorisé en Pouilly-Fumé", back: "Sauvignon blanc" },
      { front: "Cépage du Condrieu (Rhône nord)", back: "Viognier" },
      { front: "Cépage blanc du vin jaune du Jura", back: "Savagnin" },
      { front: "Cépage des grands crus de la Côte de Nuits (Chambertin, Romanée)", back: "Pinot noir" },
      { front: "Cépage dominant à Pomerol et Saint-Émilion", back: "Merlot" },
      { front: "Seul cépage autorisé en Muscadet", back: "Melon de Bourgogne" },
      { front: "Cépage alsacien noble donnant des vins aromatiques et épicés", back: "Gewurztraminer" },
      { front: "Cépage de la Syrah, assemblé avec le Grenache en Côtes-du-Rhône", back: "Syrah" },
      { front: "Cépage blanc unique du Chablis et des Bourgognes blancs", back: "Chardonnay" },
      { front: "Appellation pouvant assembler jusqu'à 18 cépages", back: "Châteauneuf-du-Pape" },
      { front: "Vin jaune du Jura : contenance de la bouteille (clavelin)", back: "62 cl" },
      { front: "Plus ancien vin mousseux de France, cité dès 1531", back: "Blanquette de Limoux" },
      { front: "Vin doux naturel de Banyuls oxydé au soleil", back: "Banyuls (rancio)" },
      { front: "Vin muté au cognac produit en Charente", back: "Pineau des Charentes" },
      { front: "Vin de paille du Jura : procédé de fabrication", back: "Séchage des raisins sur claies avant pressurage" },
      { front: "Appellation bordelaise rive droite, exclusivement rouge, base merlot", back: "Pomerol" },
      { front: "Seul Grand Cru classé de Graves en rouge ET en blanc", back: "Château Haut-Brion" },
      { front: "Vignoble alsacien : nombre de cépages nobles", back: "4 (Riesling, Gewurztraminer, Pinot gris, Muscat)" },
      { front: "Région du Muscadet : fleuve et département", back: "Loire, Loire-Atlantique" },
      { front: "Vin effervescent de la Loire, méthode traditionnelle, produit à Saumur", back: "Crémant de Loire" },
    ],
  },
  {
    id: "termes-techniques",
    name: "Vocabulaire technique",
    icon: "🔧",
    description: "Termes d'artisanat, mécanique et métiers",
    difficulty: "expert",
    cards: [
      { front: "Four alchimique tirant son nom d'un mot arabe", back: "Athanor" },
      { front: "Outil pour frapper le cuir et y imprimer un motif", back: "Matoir" },
      { front: "Cuir fabriqué à partir de peau de raie ou de requin", back: "Galuchat" },
      { front: "Dispositif d'allumage à retardement d'une bombe de feu d'artifice", back: "Espolette" },
      { front: "Premières explosions d'un feu d'artifice", back: "Marrons d'air" },
      { front: "Lime conique et pointue en mécanique", back: "Queue-de-rat" },
      { front: "Plus petite roue dentée d'un engrenage", back: "Pignon" },
      { front: "Traitement thermique : plonger un métal chauffé dans un bain froid", back: "Trempe" },
      { front: "Pierre au sommet d'un arc ou d'une voûte", back: "Clef de voûte" },
      { front: "Gravure en creux sur métal par l'action d'un acide", back: "Eau-forte" },
      { front: "Impression à plat inventée par Senefelder (1796)", back: "Lithographie" },
      { front: "Technique de fonte en bronze avec un modèle qui disparaît", back: "Cire perdue" },
      { front: "Alliage de cuivre et de zinc", back: "Laiton" },
      { front: "Alliage de cuivre et d'étain", back: "Bronze" },
      { front: "Alliage de zinc, nickel et argent (couverts), nom d'un chimiste", back: "Ruolz" },
      { front: "Instrument à mâchoires coulissantes pour la mécanique de précision", back: "Pied à coulisse" },
      { front: "Instrument qui mesure les angles en topographie", back: "Théodolite" },
      { front: "Réverbère : inventeur au XVIIIe siècle", back: "Bourgeois de Châtaublanc" },
      { front: "Art de concevoir des feux d'artifice", back: "Pyrotechnie" },
      { front: "Maçonnerie d'un pont entre deux piles", back: "Travée" },
    ],
  },
  {
    id: "geologie-geo",
    name: "Géologie et géographie",
    icon: "🌍",
    description: "Relief, formations et termes géographiques",
    difficulty: "expert",
    cards: [
      { front: "Pli dont la convexité est orientée vers le haut", back: "Anticlinal" },
      { front: "Pli dont la convexité est orientée vers le bas", back: "Synclinal" },
      { front: "Plateaux calcaires arides du Languedoc (avens, grottes)", back: "Causses" },
      { front: "Gouffre vertical naturel dans un terrain calcaire", back: "Aven" },
      { front: "Roche volcanique vitreuse et noire", back: "Obsidienne" },
      { front: "Roche volcanique poreuse et légère qui flotte sur l'eau", back: "Pierre ponce" },
      { front: "Passage d'un solide à l'état gazeux sans état liquide", back: "Sublimation" },
      { front: "Détroit entre l'Italie et la Sicile", back: "Détroit de Messine" },
      { front: "Détroit entre l'Espagne et le Maroc", back: "Détroit de Gibraltar" },
      { front: "Détroit entre la France et l'Angleterre", back: "Pas-de-Calais" },
      { front: "Canal reliant la Loire au Loing, le plus ancien de France", back: "Canal de Briare" },
      { front: "Canal reliant mer du Nord et Baltique (1895)", back: "Canal de Kiel" },
      { front: "Chaîne de volcans éteints culminant au puy de Dôme (1 465 m)", back: "Chaîne des Puys" },
      { front: "Rivière passant aux Eyzies-de-Tayac (préhistoire, Dordogne)", back: "La Vézère" },
      { front: "Col des Alpes-Maritimes à 2 802 m", back: "Col de la Bonette" },
      { front: "Fleuve côtier passant à Béziers, embouchure à Agde", back: "L'Hérault" },
      { front: "Rivière normande passant à Lisieux, embouchure à Honfleur", back: "La Touques" },
      { front: "Affluent de la Loire passant à Blois et Vendôme (sans E)", back: "Le Loir" },
      { front: "Fleuve côtier de Provence, embouchure dans l'étang de Berre", back: "L'Arc" },
      { front: "Affluent de la Loire passant à Vichy", back: "L'Allier" },
    ],
  },
  {
    id: "compositeurs",
    name: "Compositeurs classiques",
    icon: "🎵",
    description: "Œuvres et compositeurs à connaître",
    difficulty: "intermediaire",
    cards: [
      { front: "L'Orfeo (1607, Mantoue), premier chef-d'œuvre de l'opéra", back: "Monteverdi" },
      { front: "Organiste à Lübeck, influença le jeune Bach", back: "Dietrich Buxtehude" },
      { front: "Tragédie en musique à la cour de Louis XIV, né à Florence", back: "Lully" },
      { front: "Hippolyte et Aricie (1733), réformateur de l'opéra français", back: "Rameau" },
      { front: "Iphigénie en Aulide (1774), réforme de l'opéra", back: "Gluck" },
      { front: "Didon et Énée, seul véritable opéra anglais du XVIIe", back: "Purcell" },
      { front: "Requiem allemand (Brême, 1868), Danses hongroises", back: "Brahms" },
      { front: "9 symphonies monumentales, 8e inachevée, « maître de la symphonie »", back: "Anton Bruckner" },
      { front: "Symphonie L'Inextinguible (4e, 1916), compositeur danois", back: "Carl Nielsen" },
      { front: "Concerto champêtre pour clavecin (pour Wanda Landowska)", back: "Francis Poulenc" },
      { front: "Dialogues des carmélites (d'après Bernanos)", back: "Francis Poulenc" },
      { front: "Thrène à la mémoire des victimes d'Hiroshima", back: "Krzysztof Penderecki" },
      { front: "Jenůfa (Brno, 1904), vie paysanne morave", back: "Janáček" },
      { front: "Salomé (Dresde, 1905), d'après Oscar Wilde", back: "Richard Strauss" },
      { front: "Boris Godounov, d'après Pouchkine", back: "Moussorgski" },
      { front: "War Requiem (Coventry, 1962), fondateur du festival d'Aldeburgh", back: "Benjamin Britten" },
      { front: "The Turn of the Screw, d'après Henry James", back: "Benjamin Britten" },
      { front: "Le buste de Louis XIV le plus célèbre (sculpture)", back: "Antoine Coysevox" },
      { front: "Gambiste catalan, ensemble Hespèrion XXI", back: "Jordi Savall" },
      { front: "Hautbois : instrument qui donne le la à l'orchestre", back: "Le hautbois" },
    ],
  },
  {
    id: "peintres",
    name: "Peintres et leurs œuvres",
    icon: "🎨",
    description: "Peintres, surnoms et œuvres majeures",
    difficulty: "intermediaire",
    cards: [
      { front: "La Mort de Marat (Bruxelles), né en 1748", back: "Jacques-Louis David" },
      { front: "Jacopo Robusti, surnommé le Petit Teinturier (Venise, XVIe)", back: "Le Tintoret" },
      { front: "Pietro Vannucci, maître de Raphaël, Annonciation de Fano", back: "Le Pérugin" },
      { front: "L'Apothéose d'Homère, Le Grand Odalisque, élève de David", back: "Ingres" },
      { front: "Le Printemps, La Naissance de Vénus (Quattrocento, Florence)", back: "Botticelli" },
      { front: "La Laitière, Vue de Delft, peintre de Delft (XVIIe)", back: "Vermeer" },
      { front: "La Chute des anges rebelles, symboliste belge", back: "Félicien Rops" },
      { front: "Die Brücke, aplats criards, silhouettes anguleuses", back: "Ernst Ludwig Kirchner" },
      { front: "Manifeste Dada, cabaret Voltaire, Zurich (1916)", back: "Hugo Ball" },
      { front: "Le douanier Rousseau : principal représentant de...", back: "L'art naïf" },
      { front: "Colonnade du Louvre (XVIIe), architecte parisien", back: "Claude Perrault" },
      { front: "Galerie des Glaces de Versailles, architecte", back: "Jules Hardouin-Mansart" },
      { front: "Bauhaus à Weimar (1919), architecte allemand", back: "Walter Gropius" },
      { front: "Introduction de la tulipe en Europe, botaniste belge (XVIe)", back: "Charles de L'Écluse (Clusius)" },
      { front: "Historia plantarum, même botaniste", back: "Charles de L'Écluse (Clusius)" },
    ],
  },
  {
    id: "histoire-dates",
    name: "Dates et traités historiques",
    icon: "📜",
    description: "Batailles, traités et dates clés",
    difficulty: "expert",
    cards: [
      { front: "Bataille de Bouvines", back: "1214 — Philippe Auguste bat la coalition anglo-germano-flamande" },
      { front: "Fin de la guerre de Trente Ans", back: "1648 — Traités de Westphalie" },
      { front: "Fin de la guerre de Succession d'Espagne", back: "1713 — Traité d'Utrecht" },
      { front: "Assassinat d'Henri III", back: "1589 — par le moine Jacques Clément" },
      { front: "Baptême d'Henri IV (ail et jurançon)", back: "1554" },
      { front: "Concile de Trente (réponse à la Réforme)", back: "1545 — convoqué par Paul III" },
      { front: "Mort de Pie VI en captivité à Valence", back: "1799" },
      { front: "Bataille d'Essling (mort de Lannes)", back: "1809" },
      { front: "Accords Sykes-Picot (partage du Moyen-Orient)", back: "1916" },
      { front: "Traité de Rome (CEE)", back: "1957" },
      { front: "Premier vainqueur du Tour de France", back: "1903 — Maurice Garin" },
      { front: "Première radiographie (Röntgen)", back: "1895 — main de sa femme" },
      { front: "Invention de la lithographie (Senefelder)", back: "1796" },
      { front: "Invention du réverbère (Bourgeois de Châtaublanc)", back: "XVIIIe siècle" },
      { front: "Conservation des aliments en bocaux (Appert)", back: "1795-1810" },
      { front: "Canal de Kiel inauguré", back: "1895" },
      { front: "Découverte du LSD (Albert Hofmann)", back: "1938" },
      { front: "Manifeste Dada au cabaret Voltaire", back: "1916" },
      { front: "Manifeste des peintres futuristes (Boccioni, Carrà, Russolo)", back: "1910" },
      { front: "Bauhaus fondé à Weimar (Gropius)", back: "1919" },
    ],
  },
  {
    id: "litterature",
    name: "Littérature et écrivains",
    icon: "📚",
    description: "Auteurs, œuvres et prix Nobel",
    difficulty: "expert",
    cards: [
      { front: "Hérodiade, Un coup de dés, poète symboliste", back: "Stéphane Mallarmé" },
      { front: "L'Astrée, roman pastoral fleuve (XVIIe), inachevé", back: "Honoré d'Urfé" },
      { front: "Grammaire de Port-Royal (avec Claude Lancelot)", back: "Antoine Arnauld" },
      { front: "Oraison funèbre d'Henriette d'Angleterre, évêque de Meaux", back: "Bossuet" },
      { front: "L'Idiot, Le Joueur, Crime et Châtiment (condamné à mort puis gracié)", back: "Dostoïevski" },
      { front: "Pays de neige, Nobel 1968, écrivain japonais", back: "Yasunari Kawabata" },
      { front: "Max Havelaar (1860), exploitation coloniale aux Indes néerlandaises", back: "Multatuli" },
      { front: "Tirade des Non-merci dans Cyrano de Bergerac", back: "Edmond Rostand" },
      { front: "La Saga de Gösta Berlings, Nobel 1909, écrivain suédois", back: "Selma Lagerlöf" },
      { front: "Tropismes, L'Usage de la parole, Nobel 1985", back: "Nathalie Sarraute" },
      { front: "Strophe (recueil), Nobel 1963, poète grec", back: "Giorgos Séféris" },
      { front: "La Pianiste, Nobel 2004, romancière autrichienne", back: "Elfriede Jelinek" },
      { front: "La Fête au Bouc, Nobel 2010, écrivain péruvien", back: "Mario Vargas Llosa" },
      { front: "Gabriel Leuvielle : vrai nom de...", back: "Max Linder (cinéma muet)" },
      { front: "Évariste Galois : mort à quel âge ?", back: "20 ans (1832), duel, théorie des groupes" },
    ],
  },
];
