// Fun Facts — Packs pour les 12 Coups de Midi
// Infos insolites, culture générale flash, régions, gastronomie
const FUNFACTS_PACKS = [

  // ===== 1. ANIMAUX INSOLITES =====
  {
    id: "animaux-insolites",
    name: "Animaux insolites",
    icon: "🦑",
    description: "Noms bizarres, records et anecdotes animales",
    cards: [
      { front: "Quel animal peut survivre dans le vide spatial ?", back: "Le tardigrade (ou ourson d'eau), moins de 1 mm" },
      { front: "Quel est le seul mammifère capable de voler ?", back: "La chauve-souris (les écureuils volants planent, ils ne volent pas)" },
      { front: "Combien de cœurs possède une pieuvre ?", back: "3 cœurs (2 branchiaux + 1 systémique)" },
      { front: "Quel animal a le cœur dans la tête ?", back: "La crevette" },
      { front: "Quel est l'animal terrestre le plus rapide ?", back: "Le guépard (~120 km/h sur courte distance)" },
      { front: "Quel oiseau peut voler en arrière ?", back: "Le colibri (seul oiseau capable)" },
      { front: "Quel animal dort debout ?", back: "Le cheval (grâce à un système de blocage des articulations)" },
      { front: "Quel est le plus grand poisson du monde ?", back: "Le requin-baleine (jusqu'à 18 mètres)" },
      { front: "Comment appelle-t-on le cri du cerf ?", back: "Le brame (ou bramement)" },
      { front: "Comment appelle-t-on le cri du corbeau ?", back: "Le croassement (≠ coassement de la grenouille)" },
      { front: "Comment appelle-t-on le cri de la chouette ?", back: "Le hululement (ou chuintement)" },
      { front: "Comment appelle-t-on le mâle de l'oie ?", back: "Le jars" },
      { front: "Comment appelle-t-on le petit du lièvre ?", back: "Le levraut" },
      { front: "Comment appelle-t-on le petit de la biche ?", back: "Le faon" },
      { front: "Quel est le seul continent sans reptiles ?", back: "L'Antarctique" },
      { front: "Quel mammifère pond des œufs ?", back: "L'ornithorynque et les échidnés (monotrèmes)" },
      { front: "De quelle couleur est le sang des poulpes ?", back: "Bleu (à cause du cuivre dans l'hémocyanine)" },
      { front: "Quel animal a les empreintes digitales les plus proches de l'homme ?", back: "Le koala" },
      { front: "Combien de pattes a une araignée ?", back: "8 (ce n'est pas un insecte mais un arachnide)" },
      { front: "Quelle est la durée de gestation d'un éléphant ?", back: "22 mois (la plus longue chez les mammifères terrestres)" },
      { front: "Comment appelle-t-on un groupe de lions ?", back: "Une troupe (ou une harde)" },
      { front: "Quel papillon migre du Canada au Mexique chaque année ?", back: "Le monarque (Danaus plexippus), ~4 000 km" },
      { front: "Quel poisson peut changer de sexe au cours de sa vie ?", back: "Le mérou (et le poisson-clown)" },
      { front: "Quel est le plus petit oiseau du monde ?", back: "Le colibri d'Elena (~5 cm, ~2 g)" },
      { front: "Quel est le seul félin qui ne peut pas rétracter ses griffes ?", back: "Le guépard" },
      { front: "Comment appelle-t-on l'élevage des abeilles ?", back: "L'apiculture" },
      { front: "Comment appelle-t-on l'élevage des vers à soie ?", back: "La sériciculture" },
      { front: "Comment appelle-t-on l'élevage des huîtres ?", back: "L'ostréiculture" },
      { front: "Quel animal est le symbole de la médecine ?", back: "Le serpent (bâton d'Asclépios / caducée)" },
      { front: "Quelle est la seule espèce de singe sauvage en Europe ?", back: "Le macaque de Barbarie (magot), à Gibraltar" },
      { front: "Combien d'estomacs possède une vache ?", back: "4 (panse, bonnet, feuillet, caillette)" },
      { front: "Comment appelle-t-on l'élevage des escargots ?", back: "L'héliciculture" },
      { front: "Quel animal peut dormir jusqu'à 22 heures par jour ?", back: "Le koala" },
      { front: "Quel est l'insecte le plus fort par rapport à son poids ?", back: "Le scarabée bousier (peut tirer 1 141 fois son poids)" },
    ],
  },

  // ===== 2. CORPS HUMAIN =====
  {
    id: "corps-humain",
    name: "Corps humain",
    icon: "🧠",
    description: "Anecdotes étonnantes sur le corps humain",
    cards: [
      { front: "Combien d'os dans le corps humain adulte ?", back: "206 os (un bébé en a environ 270)" },
      { front: "Quel est le plus grand organe du corps humain ?", back: "La peau (~2 m² de surface)" },
      { front: "Quel est le plus petit os du corps humain ?", back: "L'étrier, dans l'oreille (environ 3 mm)" },
      { front: "Quel est le muscle le plus puissant du corps ?", back: "Le masséter (muscle de la mâchoire)" },
      { front: "Combien de litres de sang contient le corps humain ?", back: "Environ 5 litres chez un adulte" },
      { front: "Quelle est la longueur totale de l'intestin grêle ?", back: "Environ 6 à 7 mètres" },
      { front: "Combien de dents possède un adulte ?", back: "32 dents (dont 4 dents de sagesse)" },
      { front: "Quelle est la seule partie du corps qui ne reçoit pas de sang ?", back: "La cornée de l'œil (nourrie par le liquide lacrymal)" },
      { front: "Quel est le seul os du corps qui n'est relié à aucun autre ?", back: "L'os hyoïde (dans la gorge)" },
      { front: "Quelle est la vitesse d'un éternuement ?", back: "Environ 150 km/h" },
      { front: "Combien de neurones dans le cerveau humain ?", back: "Environ 86 milliards" },
      { front: "Quel pourcentage d'eau contient le corps humain adulte ?", back: "Environ 60 %" },
      { front: "Quel organe consomme 20 % de l'énergie du corps ?", back: "Le cerveau (alors qu'il ne représente que 2 % du poids)" },
      { front: "Combien de kilomètres de vaisseaux sanguins dans le corps ?", back: "Environ 100 000 km" },
      { front: "Combien de fois le cœur bat-il en moyenne par jour ?", back: "Environ 100 000 fois" },
      { front: "Quelle est la durée de vie d'un globule rouge ?", back: "Environ 120 jours" },
      { front: "Quel est le plus long nerf du corps humain ?", back: "Le nerf sciatique" },
      { front: "Quel est le plus gros organe interne ?", back: "Le foie (environ 1,5 kg)" },
      { front: "Combien de muscles dans le corps humain ?", back: "Environ 640 muscles" },
      { front: "Quel est le plus long os du corps humain ?", back: "Le fémur (os de la cuisse)" },
    ],
  },

  // ===== 3. RECORDS ET STATISTIQUES =====
  {
    id: "records-stats",
    name: "Records & Statistiques",
    icon: "📊",
    description: "Chiffres fous et records du monde",
    cards: [
      { front: "Quel est le pays le plus petit du monde ?", back: "Le Vatican (0,44 km²)" },
      { front: "Quel est le pays le plus grand du monde ?", back: "La Russie (17,1 millions de km²)" },
      { front: "Quel est le fleuve le plus long du monde ?", back: "Le Nil (~6 650 km, devant l'Amazone)" },
      { front: "Quel est le lac le plus profond du monde ?", back: "Le lac Baïkal en Russie (1 642 m)" },
      { front: "Quel est le point le plus bas sur Terre ?", back: "La mer Morte (-430 m sous le niveau de la mer)" },
      { front: "Quel est le désert le plus grand du monde ?", back: "L'Antarctique (désert froid), puis le Sahara (désert chaud)" },
      { front: "Quelle est la montagne la plus haute du monde ?", back: "L'Everest (8 849 m)" },
      { front: "Quelle est la ville la plus peuplée du monde ?", back: "Tokyo (agglomération ~37 millions d'habitants)" },
      { front: "Quel est le bâtiment le plus haut du monde ?", back: "Burj Khalifa à Dubaï (828 m)" },
      { front: "Quel est le pays avec le plus de langues officielles ?", back: "L'Afrique du Sud (11 langues officielles)" },
      { front: "Quelle est la langue la plus parlée au monde (natifs) ?", back: "Le mandarin (~920 millions de locuteurs natifs)" },
      { front: "Quel est le plus long mur du monde ?", back: "La Grande Muraille de Chine (~21 000 km au total)" },
      { front: "Quelle est la fosse océanique la plus profonde ?", back: "La fosse des Mariannes (environ 11 034 m)" },
      { front: "Quel pays possède le plus de fuseaux horaires ?", back: "La France (12 fuseaux, grâce aux DOM-TOM)" },
      { front: "Quelle est la cascade la plus haute du monde ?", back: "Le Salto Ángel au Venezuela (979 m)" },
      { front: "Quel est le plus petit pays d'Afrique ?", back: "Les Seychelles (455 km²)" },
      { front: "Quel est le pays le plus peuplé d'Afrique ?", back: "Le Nigeria (~220 millions d'habitants)" },
      { front: "Quelle est la plus longue frontière terrestre du monde ?", back: "Canada / États-Unis (8 891 km)" },
      { front: "Quel pays possède le plus d'îles au monde ?", back: "La Suède (environ 267 570 îles)" },
      { front: "Quel est le plus vieux pays du monde encore existant ?", back: "Saint-Marin (fondé en 301)" },
    ],
  },

  // ===== 4. SCIENCES ÉTONNANTES =====
  {
    id: "sciences-etonnantes",
    name: "Sciences étonnantes",
    icon: "🔬",
    description: "Physique, chimie, espace : l'inattendu",
    cards: [
      { front: "Quelle planète tourne à l'envers (rotation rétrograde) ?", back: "Vénus (le Soleil s'y lève à l'ouest)" },
      { front: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", back: "Environ 8 minutes et 20 secondes" },
      { front: "Quel gaz compose majoritairement l'atmosphère terrestre ?", back: "L'azote (78 %), pas l'oxygène (21 %)" },
      { front: "Quelle est la température du noyau de la Terre ?", back: "Environ 5 500 °C (comparable à la surface du Soleil)" },
      { front: "De quoi est principalement composé le Soleil ?", back: "D'hydrogène (~73 %) et d'hélium (~25 %)" },
      { front: "Quel est l'élément chimique le plus abondant dans l'univers ?", back: "L'hydrogène" },
      { front: "Combien de planètes dans le système solaire ?", back: "8 (Pluton reclassée en planète naine en 2006)" },
      { front: "Quel métal est liquide à température ambiante ?", back: "Le mercure (Hg)" },
      { front: "Quel est l'élément le plus léger du tableau périodique ?", back: "L'hydrogène (H, numéro atomique 1)" },
      { front: "À quelle température l'eau bout-elle au sommet de l'Everest ?", back: "Environ 70 °C (pression plus basse)" },
      { front: "Quel scientifique a formulé E = mc² ?", back: "Albert Einstein (relativité restreinte, 1905)" },
      { front: "Quelle est la vitesse de la lumière ?", back: "Environ 300 000 km/s (299 792 km/s)" },
      { front: "Quel est le plus grand volcan du système solaire ?", back: "Olympus Mons sur Mars (~21 km de haut)" },
      { front: "Qui a découvert la pénicilline ?", back: "Alexander Fleming en 1928" },
      { front: "Quel est le numéro atomique de l'or ?", back: "79 (symbole Au, du latin aurum)" },
      { front: "De quoi sont principalement faits les diamants ?", back: "De carbone pur cristallisé" },
      { front: "Quel gaz donne sa couleur rouge aux enseignes lumineuses ?", back: "Le néon" },
      { front: "Quelle planète est la plus chaude du système solaire ?", back: "Vénus (~465 °C en surface, effet de serre)" },
      { front: "Quel est le plus petit os du corps humain et quel rôle joue-t-il ?", back: "L'étrier (3 mm), transmet les vibrations sonores dans l'oreille" },
      { front: "Combien pèse environ un litre d'eau ?", back: "1 kilogramme (à 4 °C)" },
    ],
  },

  // ===== 5. VRAIS NOMS DES CÉLÉBRITÉS =====
  {
    id: "vrais-noms",
    name: "Vrais noms des célébrités",
    icon: "🌟",
    description: "Les vrais noms de stars connues",
    cards: [
      { front: "Quel est le vrai nom de Voltaire ?", back: "François-Marie Arouet" },
      { front: "Quel est le vrai nom de Molière ?", back: "Jean-Baptiste Poquelin" },
      { front: "Quel est le vrai nom de Stendhal ?", back: "Henri Beyle" },
      { front: "Quel est le vrai nom de George Sand ?", back: "Amantine Aurore Lucile Dupin" },
      { front: "Quel est le vrai nom du Caravage ?", back: "Michelangelo Merisi" },
      { front: "Quel est le vrai nom de Johnny Hallyday ?", back: "Jean-Philippe Smet" },
      { front: "Quel est le vrai nom de Bourvil ?", back: "André Raimbourg" },
      { front: "Quel est le vrai nom de Fernandel ?", back: "Fernand Joseph Désiré Contandin" },
      { front: "Quel est le vrai nom de Coluche ?", back: "Michel Gérard Joseph Colucci" },
      { front: "Quel est le vrai nom de Le Corbusier ?", back: "Charles-Édouard Jeanneret" },
      { front: "Quel est le vrai nom de Romain Gary ?", back: "Roman Kacew (aussi connu sous le pseudo Émile Ajar)" },
      { front: "Quel est le vrai nom de MC Solaar ?", back: "Claude M'Barali" },
      { front: "Quel est le vrai nom de Daft Punk ?", back: "Thomas Bangalter et Guy-Manuel de Homem-Christo" },
      { front: "Quel est le vrai nom d'Édith Piaf ?", back: "Édith Giovanna Gassion" },
      { front: "Quel est le vrai nom de Dalida ?", back: "Iolanda Cristina Gigliotti" },
      { front: "Quel est le vrai prénom de Napoléon ?", back: "Napoleone di Buonaparte (corse puis francisé)" },
      { front: "Quel est le vrai nom de Marilyn Monroe ?", back: "Norma Jeane Mortenson (puis Baker)" },
      { front: "Quel est le vrai nom de Mark Twain ?", back: "Samuel Langhorne Clemens" },
      { front: "Quel est le vrai nom de Lino Ventura ?", back: "Angiolino Giuseppe Pasquale Ventura" },
      { front: "Quel est le vrai nom de Staline ?", back: "Iossif Vissarionovitch Djougachvili" },
      { front: "Quel est le vrai nom de Calamity Jane ?", back: "Martha Jane Cannary" },
      { front: "Quel est le vrai nom du Greco ?", back: "Domínikos Theotokópoulos" },
      { front: "Quel est le vrai nom de Pelé ?", back: "Edson Arantes do Nascimento" },
      { front: "Quel est le vrai nom de Tino Rossi ?", back: "Constantino Rossi" },
    ],
  },

  // ===== 6. GÉOGRAPHIE INSOLITE =====
  {
    id: "geo-insolite",
    name: "Géographie insolite",
    icon: "🗺️",
    description: "Capitales pièges, frontières bizarres, curiosités",
    cards: [
      { front: "Quelle est la capitale de l'Australie ?", back: "Canberra (pas Sydney)" },
      { front: "Quelle est la capitale du Brésil ?", back: "Brasília (pas Rio de Janeiro)" },
      { front: "Quelle est la capitale de la Turquie ?", back: "Ankara (pas Istanbul)" },
      { front: "Quelle est la capitale du Canada ?", back: "Ottawa (pas Toronto ni Montréal)" },
      { front: "Quelle est la capitale du Maroc ?", back: "Rabat (pas Casablanca)" },
      { front: "Quelle est la capitale de la Suisse ?", back: "Berne (pas Zurich ni Genève)" },
      { front: "Quelle est la capitale du Myanmar ?", back: "Naypyidaw (pas Rangoun)" },
      { front: "Quelle est la capitale de la Nouvelle-Zélande ?", back: "Wellington (pas Auckland)" },
      { front: "Quelle est la capitale du Nigeria ?", back: "Abuja (pas Lagos)" },
      { front: "Quelle est la capitale du Pakistan ?", back: "Islamabad (pas Karachi)" },
      { front: "Quel est le seul pays dont le drapeau n'est pas rectangulaire ?", back: "Le Népal (double pennon triangulaire)" },
      { front: "Quel pays d'Afrique est entièrement entouré par un seul autre pays ?", back: "Le Lesotho (enclavé dans l'Afrique du Sud)" },
      { front: "Quel pays est traversé par le plus de fuseaux horaires (continental) ?", back: "La Russie (11 fuseaux horaires)" },
      { front: "Quel fleuve traverse le plus de capitales européennes ?", back: "Le Danube (4 capitales : Vienne, Bratislava, Budapest, Belgrade)" },
      { front: "Quelle ville est sur deux continents ?", back: "Istanbul (Europe et Asie, séparée par le Bosphore)" },
      { front: "Quel pays a la densité la plus faible au monde ?", back: "La Mongolie (~2 hab./km²)" },
      { front: "Quelle est la capitale de la Birmanie ?", back: "Naypyidaw (depuis 2006)" },
      { front: "Quelle est la capitale du Sri Lanka ?", back: "Sri Jayawardenepura Kotte (pas Colombo)" },
      { front: "Quelle est la capitale de la Côte d'Ivoire ?", back: "Yamoussoukro (pas Abidjan)" },
      { front: "Quelle est la capitale de la Tanzanie ?", back: "Dodoma (pas Dar es Salaam)" },
      { front: "Quel est le plus petit pays d'Amérique du Sud ?", back: "Le Suriname (~164 000 km²)" },
      { front: "Combien de pays sont traversés par l'équateur ?", back: "13 pays" },
    ],
  },

  // ===== 7. CINÉMA & SÉRIES =====
  {
    id: "cinema-series",
    name: "Cinéma & Séries",
    icon: "🎬",
    description: "Anecdotes de tournage, Oscars et records",
    cards: [
      { front: "Quel film a remporté le plus d'Oscars ?", back: "Ben-Hur (1959), Titanic (1997) et Le Retour du Roi (2003) : 11 chacun" },
      { front: "Quel acteur a remporté deux Oscars consécutifs ?", back: "Tom Hanks (Philadelphia 1994, Forrest Gump 1995)" },
      { front: "Dans quel film entend-on « Je suis ton père » ?", back: "Star Wars : L'Empire contre-attaque (1980)" },
      { front: "Quel réalisateur est surnommé « le maître du suspense » ?", back: "Alfred Hitchcock" },
      { front: "Quel est le premier long-métrage d'animation de Disney ?", back: "Blanche-Neige et les Sept Nains (1937)" },
      { front: "Qui a réalisé Pulp Fiction ?", back: "Quentin Tarantino (1994)" },
      { front: "Quel film français détient le record d'entrées en France ?", back: "Bienvenue chez les Ch'tis (plus de 20 millions d'entrées)" },
      { front: "Qui a réalisé 2001, l'Odyssée de l'espace ?", back: "Stanley Kubrick (1968)" },
      { front: "Quel est le premier film parlant de l'histoire ?", back: "Le Chanteur de jazz (The Jazz Singer, 1927)" },
      { front: "Quel est le vrai nom de Charlie Chaplin ?", back: "Sir Charles Spencer Chaplin" },
      { front: "Quel est le premier film des frères Lumière ?", back: "La Sortie de l'usine Lumière à Lyon (1895)" },
      { front: "Qui joue le rôle-titre dans Amélie Poulain ?", back: "Audrey Tautou (réalisé par Jean-Pierre Jeunet, 2001)" },
      { front: "Quel est le plus gros succès du cinéma français à l'international ?", back: "Intouchables (2011, plus de 50 millions d'entrées dans le monde)" },
      { front: "Quel acteur incarne OSS 117 dans les films de Michel Hazanavicius ?", back: "Jean Dujardin" },
      { front: "Quel film de Jean Dujardin a remporté l'Oscar du meilleur film ?", back: "The Artist (2012, film muet en noir et blanc)" },
      { front: "Quel est le nom du personnage joué par Jean Reno dans Léon ?", back: "Léon (Le Professionnel, 1994, réalisé par Luc Besson)" },
      { front: "Quel dessin animé Pixar met en scène un rat cuisinier à Paris ?", back: "Ratatouille (2007)" },
      { front: "Quel James Bond a été incarné par le plus d'acteurs ?", back: "6 acteurs principaux : Connery, Lazenby, Moore, Dalton, Brosnan, Craig" },
      { front: "Quel est le film le plus cher jamais produit (ajusté inflation) ?", back: "Pirates des Caraïbes : Jusqu'au bout du monde (2007)" },
      { front: "Qui a créé la saga Star Wars ?", back: "George Lucas (premier film en 1977)" },
    ],
  },

  // ===== 8. RÉGIONS DE FRANCE =====
  {
    id: "regions-france",
    name: "Régions de France",
    icon: "🇫🇷",
    description: "Spécialités, capitales et curiosités régionales",
    cards: [
      { front: "Combien de régions métropolitaines en France ?", back: "13 régions (depuis la réforme de 2016)" },
      { front: "Quelle est la plus grande région de France métropolitaine ?", back: "Nouvelle-Aquitaine (~84 000 km²)" },
      { front: "Quelle est la région la plus peuplée de France ?", back: "Île-de-France (~12 millions d'habitants)" },
      { front: "Quel est le chef-lieu de la région Grand Est ?", back: "Strasbourg" },
      { front: "Quel est le chef-lieu de la région Occitanie ?", back: "Toulouse" },
      { front: "Quel est le chef-lieu de la région Hauts-de-France ?", back: "Lille" },
      { front: "Quel est le chef-lieu de la région Nouvelle-Aquitaine ?", back: "Bordeaux" },
      { front: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", back: "Lyon" },
      { front: "Quel est le chef-lieu de la région Bourgogne-Franche-Comté ?", back: "Dijon" },
      { front: "Quel est le chef-lieu de la région Centre-Val de Loire ?", back: "Orléans" },
      { front: "Quel est le chef-lieu de la région Normandie ?", back: "Rouen" },
      { front: "Quel est le chef-lieu de la région Bretagne ?", back: "Rennes" },
      { front: "Quel est le chef-lieu de la région Pays de la Loire ?", back: "Nantes" },
      { front: "Quel est le chef-lieu de la région PACA ?", back: "Marseille" },
      { front: "Quel est le chef-lieu de la Corse ?", back: "Ajaccio" },
      { front: "La Camargue se situe dans quel département ?", back: "Les Bouches-du-Rhône (13)" },
      { front: "Le Mont-Saint-Michel est dans quel département ?", back: "La Manche (50), en Normandie" },
      { front: "Les gorges du Verdon traversent quels départements ?", back: "Alpes-de-Haute-Provence et Var" },
      { front: "Le Futuroscope se trouve dans quel département ?", back: "La Vienne (86), à Poitiers" },
      { front: "La dune du Pilat se trouve dans quel département ?", back: "La Gironde (33), à La Teste-de-Buch" },
      { front: "Quelle région est associée au beurre salé ?", back: "La Bretagne" },
      { front: "Quelle région produit le calisson ?", back: "La Provence (Aix-en-Provence)" },
      { front: "Quelle ville est connue pour sa moutarde ?", back: "Dijon (Bourgogne)" },
      { front: "Le nougat de Montélimar vient de quelle région ?", back: "Auvergne-Rhône-Alpes (Drôme)" },
      { front: "Le béret basque est originaire de quel département ?", back: "Le Béarn (Pyrénées-Atlantiques, 64), pas le Pays basque !" },
      { front: "Les volcans d'Auvergne : quel est le plus haut ?", back: "Le puy de Sancy (1 885 m), dans le Massif central" },
      { front: "Quelle ville est surnommée la « Ville rose » ?", back: "Toulouse (briques roses)" },
      { front: "Quelle ville est surnommée la « Cité des Papes » ?", back: "Avignon (palais des Papes)" },
      { front: "Quelle ville française est inscrite au patrimoine mondial pour ses fortifications ?", back: "Carcassonne (Aude)" },
      { front: "Le pont du Gard est un aqueduc romain situé dans quel département ?", back: "Le Gard (30)" },
      { front: "Les alignements mégalithiques les plus célèbres de France ?", back: "Carnac (Morbihan, Bretagne)" },
      { front: "Quelle île française est surnommée l'île de Beauté ?", back: "La Corse" },
      { front: "La tapisserie de Bayeux raconte quel événement ?", back: "La conquête de l'Angleterre par Guillaume le Conquérant (1066)" },
    ],
  },

  // ===== 9. GASTRONOMIE FRANÇAISE =====
  {
    id: "gastronomie",
    name: "Gastronomie française",
    icon: "🧑‍🍳",
    description: "Fromages, plats, vins et traditions culinaires",
    cards: [
      { front: "Combien de fromages différents recense-t-on en France ?", back: "Plus de 1 200 variétés" },
      { front: "Quel fromage est surnommé « le roi des fromages » ?", back: "Le roquefort (ou parfois le brie)" },
      { front: "De quelle région vient le camembert ?", back: "Normandie (village de Camembert, Orne)" },
      { front: "Avec quel lait est fabriqué le roquefort ?", back: "Lait de brebis (affiné dans les caves de Roquefort-sur-Soulzon)" },
      { front: "Quel est le fromage le plus consommé en France ?", back: "L'emmental (pas le camembert !)" },
      { front: "Qu'est-ce qu'un fromage à pâte persillée ?", back: "Un fromage à moisissures (bleu) : roquefort, bleu d'Auvergne, fourme d'Ambert" },
      { front: "La bouillabaisse est une spécialité de quelle ville ?", back: "Marseille" },
      { front: "Le cassoulet est un plat de quelle région ?", back: "Occitanie (Castelnaudary, Toulouse, Carcassonne)" },
      { front: "La choucroute est une spécialité de quelle région ?", back: "L'Alsace" },
      { front: "Le gratin dauphinois vient de quelle région ?", back: "Le Dauphiné (Isère, actuelle Auvergne-Rhône-Alpes)" },
      { front: "La quiche lorraine vient de quelle région ?", back: "La Lorraine (Grand Est)" },
      { front: "Quel est l'ingrédient principal de l'aligot ?", back: "La tome fraîche de Laguiole (et purée de pommes de terre)" },
      { front: "Le kouign-amann est une pâtisserie de quelle région ?", back: "Bretagne (Douarnenez)" },
      { front: "La tarte Tatin a été inventée par accident dans quel département ?", back: "Le Loir-et-Cher (Lamotte-Beuvron)" },
      { front: "Le canelé est une spécialité de quelle ville ?", back: "Bordeaux" },
      { front: "La pissaladière est une spécialité de quelle région ?", back: "Nice (Côte d'Azur)" },
      { front: "Le baba au rhum a été popularisé en France par quel pâtissier ?", back: "Nicolas Stohrer (1730), plus vieille pâtisserie de Paris" },
      { front: "Combien d'étoiles au maximum peut décerner le Guide Michelin ?", back: "3 étoiles (1 = très bonne table, 2 = excellente, 3 = exceptionnelle)" },
      { front: "Qui est considéré comme le « père de la gastronomie française » ?", back: "Auguste Escoffier (ou Antonin Carême, selon les sources)" },
      { front: "Qu'est-ce qu'une AOC / AOP ?", back: "Appellation d'Origine Contrôlée / Protégée : garantit l'origine géographique" },
      { front: "Le champagne ne peut être produit que dans quelle région ?", back: "La Champagne (AOC stricte)" },
      { front: "Le croissant est-il une invention française ?", back: "Non ! Il vient du kipferl autrichien (Vienne), popularisé en France au XIXe" },
      { front: "Le bœuf bourguignon tire son nom de quel ingrédient clé ?", back: "Le vin de Bourgogne (vin rouge)" },
      { front: "Quel condiment est fabriqué à Espelette au Pays basque ?", back: "Le piment d'Espelette (AOP)" },
      { front: "Le pain d'épices est une spécialité de quelle ville ?", back: "Dijon (tradition depuis le Moyen Âge)" },
      { front: "Qu'est-ce que le « repas gastronomique des Français » ?", back: "Inscrit au patrimoine immatériel de l'UNESCO depuis 2010" },
      { front: "Quel légume est à la base de la ratatouille ?", back: "Aubergine, courgette, poivron, tomate, oignon (plat provençal)" },
      { front: "Quel est le plat national non officiel de la France ?", back: "Le pot-au-feu" },
      { front: "La socca est une spécialité de quelle ville ?", back: "Nice (galette de farine de pois chiche)" },
      { front: "Quel fruit est associé à la ville de Montmorency ?", back: "La cerise (griotte de Montmorency)" },
      { front: "Les macarons de quel pâtissier parisien sont mondialement connus ?", back: "Pierre Hermé (et Ladurée)" },
    ],
  },

  // ===== 10. LANGUE FRANÇAISE =====
  {
    id: "langue-francaise",
    name: "Langue française",
    icon: "📖",
    description: "Étymologies, mots rares et pièges",
    cards: [
      { front: "Quel est le mot le plus long de la langue française ?", back: "Anticonstitutionnellement (25 lettres)" },
      { front: "Comment appelle-t-on la peur des araignées ?", back: "L'arachnophobie" },
      { front: "Comment appelle-t-on la peur des espaces clos ?", back: "La claustrophobie" },
      { front: "Comment appelle-t-on la peur du vide / hauteurs ?", back: "L'acrophobie (≠ vertige)" },
      { front: "Comment appelle-t-on un mot qui se lit pareil dans les deux sens ?", back: "Un palindrome (ex : kayak, radar, ressasser)" },
      { front: "Que signifie le mot « procrastiner » ?", back: "Reporter à plus tard ce qu'on pourrait faire maintenant" },
      { front: "Que signifie l'expression « avoir maille à partir » ?", back: "Avoir un différend (la maille était une petite pièce de monnaie)" },
      { front: "D'où vient le mot « salaire » ?", back: "Du latin salarium : ration de sel des soldats romains" },
      { front: "D'où vient le mot « quarantaine » ?", back: "De quaranta giorni (40 jours d'isolement imposés aux navires à Venise)" },
      { front: "Qu'est-ce qu'un hapax ?", back: "Un mot qui n'apparaît qu'une seule fois dans un corpus" },
      { front: "Comment appelle-t-on un mot formé des initiales d'autres mots ?", back: "Un acronyme (ex : SIDA, ONU, laser)" },
      { front: "Qu'est-ce qu'un pléonasme ?", back: "Répétition inutile (ex : « monter en haut », « descendre en bas »)" },
      { front: "Que signifie « sérendipité » ?", back: "Faire une découverte heureuse par hasard" },
      { front: "Quelle lettre est la plus utilisée en français ?", back: "Le E" },
      { front: "Comment s'appelle un roman écrit sans la lettre E ?", back: "Un lipogramme (ex : La Disparition de Georges Perec, 1969)" },
      { front: "Quel est le pluriel de « œil » ?", back: "Yeux (sauf œils-de-bœuf, œils-de-perdrix)" },
      { front: "Quels mots français viennent de l'arabe ?", back: "Algorithme, algèbre, chiffre, zéro, magasin, café, alcool..." },
      { front: "D'où vient le mot « assassin » ?", back: "De l'arabe hashshashin (consommateurs de haschisch)" },
      { front: "Quel mot désigne la peur de la peur ?", back: "La phobophobie" },
      { front: "Comment appelle-t-on quelqu'un qui parle plusieurs langues ?", back: "Un polyglotte" },
    ],
  },

  // ===== 11. INVENTIONS & DÉCOUVERTES =====
  {
    id: "inventions",
    name: "Inventions & Découvertes",
    icon: "💡",
    description: "Qui a inventé quoi ? Les réponses qui surprennent",
    cards: [
      { front: "Qui a inventé l'imprimerie en Europe ?", back: "Johannes Gutenberg (vers 1450, à Mayence)" },
      { front: "Qui a inventé le vaccin contre la rage ?", back: "Louis Pasteur (1885)" },
      { front: "Qui a inventé la dynamite ?", back: "Alfred Nobel (1867) — d'où le prix Nobel" },
      { front: "Qui a inventé la conserve alimentaire ?", back: "Nicolas Appert (1795, méthode d'appertisation)" },
      { front: "Qui a inventé le cinématographe ?", back: "Les frères Lumière (1895, Lyon)" },
      { front: "Qui a inventé le stéthoscope ?", back: "René Laennec (1816, à l'hôpital Necker)" },
      { front: "Qui a inventé la machine à calculer ?", back: "Blaise Pascal (1642, la Pascaline)" },
      { front: "Qui a inventé le paratonnerre ?", back: "Benjamin Franklin (1752)" },
      { front: "Qui a inventé la photographie ?", back: "Nicéphore Niépce (1826-1827, première photo connue)" },
      { front: "Qui a inventé le braille ?", back: "Louis Braille (1825, lui-même aveugle)" },
      { front: "Qui a inventé le stylo à bille ?", back: "László Bíró (1938, Hongrois)" },
      { front: "Qui a découvert la radioactivité ?", back: "Henri Becquerel (1896), puis les Curie" },
      { front: "Qui a inventé la guillotine ?", back: "Le Dr Guillotin l'a proposée, mais c'est Antoine Louis qui l'a conçue" },
      { front: "Qui a inventé la carte à puce ?", back: "Roland Moreno (1974, Français)" },
      { front: "Qui a inventé le Minitel ?", back: "France Télécom / PTT (lancé en 1982, invention française)" },
      { front: "Qui a inventé la montgolfière ?", back: "Les frères Montgolfier (1783, Annonay)" },
      { front: "Qui a inventé la boîte de conserve ?", back: "Peter Durand (1810), mais le procédé est de Nicolas Appert" },
      { front: "Qui a inventé le vaccin contre la variole ?", back: "Edward Jenner (1796)" },
      { front: "Qui a inventé le téléphone ?", back: "Alexander Graham Bell (brevet en 1876)" },
      { front: "Qui a inventé l'aspirine ?", back: "Felix Hoffmann chez Bayer (1897)" },
      { front: "Qui a inventé le système métrique ?", back: "La France révolutionnaire (1795)" },
    ],
  },

  // ===== 12. MUSIQUE =====
  {
    id: "musique-pop",
    name: "Musique",
    icon: "🎸",
    description: "Groupes, albums cultes et anecdotes musicales",
    cards: [
      { front: "Quel est l'album le plus vendu de tous les temps ?", back: "Thriller de Michael Jackson (1982, ~70 millions)" },
      { front: "Quel groupe a vendu le plus d'albums au monde ?", back: "Les Beatles" },
      { front: "Comment s'appelle le chanteur des Rolling Stones ?", back: "Mick Jagger" },
      { front: "Quel chanteur est surnommé « The King » ?", back: "Elvis Presley" },
      { front: "Quel groupe a chanté « Bohemian Rhapsody » ?", back: "Queen (1975, album A Night at the Opera)" },
      { front: "Quel groupe de rock a pour chanteur Bono ?", back: "U2" },
      { front: "Quel est le festival de musique le plus célèbre (1969) ?", back: "Woodstock (État de New York)" },
      { front: "Comment s'appelle le batteur des Beatles ?", back: "Ringo Starr (vrai nom Richard Starkey)" },
      { front: "Quel artiste a chanté « La Bohème » ?", back: "Charles Aznavour" },
      { front: "Quel artiste a chanté « Ne me quitte pas » ?", back: "Jacques Brel (1959)" },
      { front: "Quel musicien est devenu sourd et a continué à composer ?", back: "Ludwig van Beethoven" },
      { front: "Quel opéra de Mozart raconte l'histoire de Don Juan ?", back: "Don Giovanni (1787)" },
      { front: "De quel instrument jouait Django Reinhardt ?", back: "La guitare (jazz manouche, avec 2 doigts paralysés)" },
      { front: "Quel compositeur a écrit « Le Boléro » ?", back: "Maurice Ravel (1928)" },
      { front: "Quel compositeur a écrit « Les Quatre Saisons » ?", back: "Antonio Vivaldi (vers 1723)" },
      { front: "Qui a composé « La Flûte enchantée » ?", back: "Wolfgang Amadeus Mozart (1791)" },
      { front: "Quel rappeur français est le plus gros vendeur de disques ?", back: "MC Solaar (plus de 10 millions d'albums)" },
      { front: "Comment s'appelle le festival de musique classique de Salzbourg ?", back: "Le Festival de Salzbourg (fondé en 1920)" },
      { front: "Quel instrument donne le « la » à l'orchestre ?", back: "Le hautbois" },
      { front: "Combien de cordes a un violon ?", back: "4 cordes (sol, ré, la, mi)" },
    ],
  },

  // ===== 13. ÉTYMOLOGIE DES MOTS =====
  {
    id: "etymologie",
    name: "Étymologie des mots",
    icon: "🔤",
    description: "D'où viennent les mots qu'on utilise tous les jours ?",
    cards: [
      { front: "D'où vient le mot « salaire » ?", back: "Du latin salarium (sel) — les soldats romains étaient payés en sel" },
      { front: "D'où vient le mot « candidat » ?", back: "Du latin candidus (blanc) — les candidats romains portaient une toge blanche" },
      { front: "D'où vient le mot « hystérie » ?", back: "Du grec hystera (utérus) — on croyait que c'était une maladie utérine" },
      { front: "D'où vient le mot « quarantaine » ?", back: "De quaranta giorni (40 jours) — durée d'isolement des navires à Venise" },
      { front: "D'où vient le mot « assassin » ?", back: "De l'arabe hashshashin — secte du XIe siècle au Moyen-Orient" },
      { front: "D'où vient le mot « robot » ?", back: "Du tchèque robota (travail forcé) — inventé par Karel Čapek en 1920" },
      { front: "D'où vient le mot « caprice » ?", back: "De l'italien capriccio (frisson de la tête) — lié à capra (chèvre)" },
      { front: "D'où vient le mot « cravate » ?", back: "De « croate » — les cavaliers croates portaient un foulard au cou (XVIIe)" },
      { front: "D'où vient le mot « alcool » ?", back: "De l'arabe al-kuḥl (poudre d'antimoine) — sens élargi à la distillation" },
      { front: "D'où vient le mot « bonbon » ?", back: "Redoublement enfantin de « bon » — apparu au XVIIe siècle" },
      { front: "D'où vient le mot « fiasco » ?", back: "De l'italien fiasco (bouteille) — un acteur raté « faisait une bouteille »" },
      { front: "D'où vient le mot « baguette » ?", back: "De l'italien bacchetta (petit bâton) — issu du latin baculum" },
      { front: "D'où vient le mot « muscle » ?", back: "Du latin musculus (petite souris) — la contraction du muscle ressemble à une souris" },
      { front: "D'où vient le mot « désastre » ?", back: "De l'italien disastro (mauvaise étoile) — astro = astre" },
      { front: "D'où vient le mot « bikini » ?", back: "De l'atoll Bikini (essais nucléaires) — l'effet du maillot serait « explosif »" },
      { front: "D'où vient le mot « pistol » / « pistolet » ?", back: "De la ville de Pistoia en Italie, connue pour ses armuriers" },
      { front: "D'où vient le mot « jeans » ?", back: "De Gênes (Genova) — « Genes » en anglais, tissu venu de cette ville" },
      { front: "D'où vient le mot « denim » ?", back: "De « de Nîmes » — la toile venait de Nîmes" },
      { front: "D'où vient le mot « gazette » ?", back: "De l'italien gazzetta — petite pièce de monnaie vénitienne (prix du journal)" },
      { front: "D'où vient le mot « compagnon » ?", back: "Du latin cum + panis (avec + pain) — celui avec qui on partage le pain" },
      { front: "D'où vient le mot « métro » ?", back: "Abréviation de « chemin de fer métropolitain »" },
      { front: "D'où vient le mot « catastrophe » ?", back: "Du grec katastrophê (renversement) — kata (en bas) + strephein (tourner)" },
      { front: "D'où vient le mot « chapeau » ?", back: "Du latin cappa (manteau) — même racine que « cape » et « chapelle »" },
      { front: "D'où vient le mot « silhouette » ?", back: "D'Étienne de Silhouette, contrôleur des finances (1759), connu pour son austérité" },
      { front: "D'où vient le mot « bistrot » ?", back: "Origine disputée — peut-être du russe bystro (vite) ou du français bistrouille" },
      { front: "D'où vient le mot « chiffre » ?", back: "De l'arabe sifr (vide, zéro) — même origine que « zéro »" },
      { front: "D'où vient le mot « magasin » ?", back: "De l'arabe makhzan (entrepôt) — même racine que « magazine »" },
      { front: "D'où vient le mot « abricot » ?", back: "De l'arabe al-barquq, lui-même du latin praecoquum (fruit précoce)" },
      { front: "D'où vient le mot « pantalon » ?", back: "Du personnage Pantalone de la commedia dell'arte italienne" },
      { front: "D'où vient le mot « palace » ?", back: "Du mont Palatin à Rome, où Auguste avait son palatium (palais)" },
    ],
  },

  // ===== 14. POP CULTURE FRANÇAISE =====
  {
    id: "pop-culture-fr",
    name: "Pop Culture française",
    icon: "📺",
    description: "Émissions cultes, chansons, séries et personnages FR",
    cards: [
      { front: "Qui présentait « Les Enfants de la Télé » à l'origine ?", back: "Arthur (Jacques Essebag)" },
      { front: "Quel animateur présente « Les 12 Coups de Midi » ?", back: "Jean-Luc Reichmann" },
      { front: "Quel animateur présentait « Questions pour un Champion » avant Samuel Étienne ?", back: "Julien Lepers (1988-2015)" },
      { front: "Qui est le créateur des « Guignols de l'Info » ?", back: "Alain de Greef (producteur Canal+)" },
      { front: "Dans quelle émission entend-on « C'est mon dernier mot, Jean-Pierre » ?", back: "Qui veut gagner des millions ? (présenté par Jean-Pierre Foucault)" },
      { front: "Quelle émission a révélé Mimie Mathy, Muriel Robin et Pierre Palmade ?", back: "Le Petit Théâtre de Bouvard" },
      { front: "Qui présente « Fort Boyard » depuis le début ?", back: "Patrice Laffont (1990-1999), puis Olivier Minne" },
      { front: "Quel personnage de Fort Boyard garde les clés ?", back: "Le Père Fouras (avec ses énigmes)" },
      { front: "Quelle chanson française est la plus connue à l'étranger ?", back: "« La Vie en rose » d'Édith Piaf" },
      { front: "Qui chante « Pour que tu m'aimes encore » ?", back: "Céline Dion (1995, écrite par Jean-Jacques Goldman)" },
      { front: "Qui a écrit la plupart des tubes de Céline Dion en français ?", back: "Jean-Jacques Goldman" },
      { front: "Quelle série française se passe au Moyen Âge avec une Table Ronde ?", back: "Kaamelott (Alexandre Astier)" },
      { front: "Qui a créé et joue dans Kaamelott ?", back: "Alexandre Astier (il joue le roi Arthur)" },
      { front: "Comment s'appelle la série culte du « Splendid » ?", back: "Le Père Noël est une ordure (film) et Scènes de ménages est une série du Splendid? Non, la série culte est Les Bronzés / Le Père Noël est une ordure" },
      { front: "Qui sont les membres de la troupe du Splendid ?", back: "Jugnot, Lhermitte, Clavier, Balasko, Chazel, Moynot, Blanc" },
      { front: "Quel rappeur est à l'origine du collectif Sexion d'Assaut ?", back: "Gims (Maître Gims / Gandhi Djuna)" },
      { front: "Qui a chanté « Dès que le vent soufflera » ?", back: "Renaud (1983)" },
      { front: "Qui a chanté « Les Lacs du Connemara » ?", back: "Michel Sardou (1981)" },
      { front: "Qui a écrit et chanté « Le Métèque » ?", back: "Georges Moustaki (1969)" },
      { front: "Qui chante « Mistral gagnant » ?", back: "Renaud (1985)" },
      { front: "Quel dessin animé français met en scène un village gaulois ?", back: "Astérix (créé par Goscinny et Uderzo, 1959)" },
      { front: "Comment s'appelle le village des Schtroumpfs ?", back: "Le village des Schtroumpfs (créés par Peyo, belge)" },
      { front: "Quelle BD franco-belge se passe dans l'espace avec Valérian ?", back: "Valérian et Laureline (Christin & Mézières, 1967)" },
      { front: "Qui présente « Tout le monde veut prendre sa place » ?", back: "Nagui" },
      { front: "Qui a présenté « Nulle Part Ailleurs » sur Canal+ ?", back: "Antoine de Caunes et José Garcia (entre autres)" },
      { front: "Quel groupe a chanté « L'Aziza » ?", back: "Daniel Balavoine (1985)" },
      { front: "Qui chante « Je l'aime à mourir » ?", back: "Francis Cabrel (1979)" },
      { front: "Qui a chanté « Alexandrie Alexandra » ?", back: "Claude François (1977)" },
      { front: "Quel chanteur français est surnommé « Cloclo » ?", back: "Claude François" },
      { front: "Qui chante « Il est 5 heures, Paris s'éveille » ?", back: "Jacques Dutronc (1968)" },
    ],
  },

  // ===== 15. ACTU & SOCIÉTÉ =====
  {
    id: "actu-societe",
    name: "Actu & Société",
    icon: "📰",
    description: "Fun facts de société, records récents, infos insolites",
    cards: [
      { front: "Quelle est la marque de voiture la plus vendue au monde ?", back: "Toyota" },
      { front: "Quel est le site web le plus visité au monde ?", back: "Google" },
      { front: "Quel réseau social a dépassé 2 milliards d'utilisateurs ?", back: "Facebook (Meta), puis YouTube et WhatsApp" },
      { front: "Quel pays a le plus de prix Nobel ?", back: "Les États-Unis (plus de 400)" },
      { front: "Quel sport est le plus regardé au monde ?", back: "Le football (soccer)" },
      { front: "Quel est le livre le plus vendu au monde après la Bible ?", back: "Don Quichotte de Cervantès (~500 millions)" },
      { front: "Quel est le fruit le plus consommé au monde ?", back: "La banane" },
      { front: "Combien de pays sont membres de l'ONU ?", back: "193 pays membres" },
      { front: "Combien de pays dans l'Union européenne ?", back: "27 pays (depuis le Brexit en 2020)" },
      { front: "Quel pays produit le plus de café au monde ?", back: "Le Brésil" },
      { front: "Quel pays produit le plus de vin au monde ?", back: "L'Italie (devant la France et l'Espagne)" },
      { front: "Quel est le sport le plus pratiqué en France ?", back: "Le football (2+ millions de licenciés)" },
      { front: "Combien de communes en France ?", back: "Environ 35 000 (le pays avec le plus de communes en Europe)" },
      { front: "Quel est le monument le plus visité de France ?", back: "La cathédrale Notre-Dame de Paris (avant l'incendie : ~13M visiteurs/an)" },
      { front: "Quel est le musée le plus visité au monde ?", back: "Le Louvre (~10 millions de visiteurs/an)" },
      { front: "Quel est le prénom masculin le plus donné en France en 2024 ?", back: "Gabriel" },
      { front: "Quelle est l'espérance de vie moyenne en France ?", back: "~85 ans (femmes), ~79 ans (hommes)" },
      { front: "Quel est le plus long pont de France ?", back: "Le viaduc de Millau (2 460 m, Aveyron)" },
      { front: "Quelle est la plus haute structure de France ?", back: "La Tour Eiffel (330 m avec antenne)" },
      { front: "Quel animal est le plus mortel pour l'homme dans le monde ?", back: "Le moustique (maladies transmises : ~700 000 morts/an)" },
      { front: "Quel pays est le plus grand producteur de fromage au monde ?", back: "Les États-Unis (en volume), mais la France a le plus de variétés" },
      { front: "Combien de langues sont parlées dans le monde ?", back: "Environ 7 000 langues" },
      { front: "Quel est le plus vieux journal encore en activité en France ?", back: "La Gazette (devenue Le Moniteur) — le plus ancien journal français encore actif est Le Figaro (1826)" },
      { front: "Quel pourcentage de la surface terrestre est couvert d'eau ?", back: "Environ 71 %" },
      { front: "Quelle est la monnaie la plus échangée au monde ?", back: "Le dollar américain (USD)" },
    ],
  },

  // ===== PACKS PARAMNÉSIE — Culture G avancée =====

  // --- ANIMAUX : Noms scientifiques & autres noms ---
  {
    id: "animaux-noms-alternatifs",
    name: "Animaux : l'autre nom",
    icon: "🦎",
    description: "Noms scientifiques, surnoms et noms alternatifs d'animaux",
    cards: [
      { front: "Autre nom du lézard Jésus-Christ (qui court sur l'eau) ?", back: "Basilic" },
      { front: "Autre nom du bénitier (gros coquillage) ?", back: "Tridacne" },
      { front: "Autre nom de la puce de mer ?", back: "Talitre" },
      { front: "Autre nom du couteau (coquillage) ?", back: "Solen" },
      { front: "Comment appelle-t-on l'ordre des tortues ?", back: "Chéloniens" },
      { front: "Quel singe a une moustache blanche ?", back: "Le tamarin" },
      { front: "Autre nom de la chouette des neiges ?", back: "Harfang" },
      { front: "Autre nom de la chouette hulotte ?", back: "Chat-huant" },
      { front: "Autre nom du loup blanc arctique ?", back: "Isatis" },
      { front: "Quel est le poney basque ?", back: "Pottok" },
      { front: "Autre nom du poisson Saint-Pierre ?", back: "Zée" },
      { front: "Autre nom du cerf-volant (insecte) ?", back: "Lucane" },
      { front: "Autre nom de la courtilière (insecte) ?", back: "Taupe-grillon" },
      { front: "Comment s'appelle la femelle du yack ?", back: "Dri" },
      { front: "Autre nom du perce-oreille ?", back: "Forficule" },
      { front: "Autre nom de la panthère des neiges ?", back: "Once" },
      { front: "Autre nom du cougar ?", back: "Puma" },
      { front: "Autre nom du grand tétras ?", back: "Coq de bruyère" },
      { front: "Autre nom de l'oiseau-lyre ?", back: "Ménure" },
      { front: "Autre nom de l'aiglefin ?", back: "Haddock" },
      { front: "Autre nom du poisson-lune ?", back: "Môle" },
      { front: "Autre nom du poisson rouge ?", back: "Cyprin doré" },
      { front: "Autre nom du crapaud de mer ?", back: "Rascasse" },
      { front: "Autre nom du singe-écureuil ?", back: "Saïmiri" },
      { front: "Autre nom du kiwi (oiseau) ?", back: "Aptéryx" },
      { front: "Autre nom du dodo ?", back: "Dronte" },
      { front: "Autre nom du charançon ?", back: "Balanin (ravageur du riz)" },
      { front: "Autre nom du scarabée d'eau ?", back: "Dytique" },
      { front: "Autre nom de la pintade ?", back: "Poule d'Inde" },
      { front: "Autre nom de l'agami (oiseau) ?", back: "Oiseau-trompette" },
      { front: "Autre nom de l'engoulevent ?", back: "Tête de chèvre (attrape insectes en vol)" },
      { front: "Autre nom de l'aoûtat ?", back: "Trombidion" },
      { front: "Autre nom de l'araignée-crabe ?", back: "Thomise" },
      { front: "Autre nom du hérisson malgache ?", back: "Tangue" },
      { front: "Autre nom de l'ablette ?", back: "Vif-argent" },
      { front: "Autre nom de la bergeronnette ?", back: "Hochequeue" },
      { front: "Autre nom de la mouffette ?", back: "Sconse" },
      { front: "Quel chien sibérien est connu pour son sourire ?", back: "Le samoyède" },
      { front: "Autre nom du cochon malais ?", back: "Babiroussa" },
      { front: "Comment s'appelle la femelle du bouquetin ?", back: "Étagne" },
      { front: "Autre nom du serpent à sonnette ?", back: "Crotale" },
      { front: "Autre nom du serpent à corne ?", back: "Céraste" },
      { front: "Autre nom du rat-taupe nu ?", back: "Hétérocéphale" },
      { front: "Autre nom du dingo ?", back: "Warrigal" },
      { front: "Autre nom du lycaon ?", back: "Loup-peint" },
      { front: "Autre nom du fennec (nom latin) ?", back: "Vulpes zerda" },
      { front: "Autre nom du chat-ours ?", back: "Binturong" },
      { front: "Autre nom du caribou ?", back: "Renne" },
      { front: "Autre nom de l'orignal ?", back: "Élan" },
      { front: "Quel singe vit à Gibraltar ?", back: "Le magot" },
      { front: "Autre nom de la tarentule ?", back: "Araignée-loup" },
      { front: "Quel rapace est endémique de La Réunion ?", back: "Le busard de Maillard (papangue)" },
      { front: "Quel oiseau est endémique de Nouvelle-Calédonie ?", back: "Le cagou" },
      { front: "Autre nom du poisson d'argent ?", back: "Lépisme" },
      { front: "Quel singe est sacré en Inde ?", back: "L'entelle" },
      { front: "Autre nom du perce-neige ?", back: "Galantine d'hiver" },
      { front: "Quel papillon est le grand migrateur ?", back: "Le monarque" },
      { front: "Quel papillon ravage le buis ?", back: "La pyrale" },
      { front: "Quel papillon attaque les choux ?", back: "La piéride" },
      { front: "Quel loup marsupial a disparu ?", back: "Le thylacine" },
      { front: "Quel est l'ancêtre de tous les carnivores ?", back: "Le miacis" },
      { front: "Autre nom du moustique du paludisme ?", back: "Anophèle" },
      { front: "Autre nom du dauphin rose d'Amazonie ?", back: "Boto" },
    ],
  },

  // --- BOTANIQUE ---
  {
    id: "botanique",
    name: "Botanique : plantes & fruits",
    icon: "🌿",
    description: "Noms de plantes, fruits exotiques, arbres et champignons",
    cards: [
      { front: "Quel poison est extrait des lianes ?", back: "Le curare" },
      { front: "Autre nom de l'angélique (plante) ?", back: "Herbe du Saint-Esprit" },
      { front: "Comment s'appellent les fruits du frêne ?", back: "Samares" },
      { front: "Comment s'appellent les fruits du hêtre ?", back: "Faînes" },
      { front: "Autre nom du kapokier ?", back: "Fromager" },
      { front: "Autre nom du litchi chevelu ?", back: "Ramboutan" },
      { front: "De quelle prune vient le pruneau d'Agen ?", back: "La prune d'ente" },
      { front: "Autre nom de la moutarde (plante) ?", back: "Sénevé" },
      { front: "Comment s'appelle la partie de l'étamine qui renferme le pollen ?", back: "L'anthère" },
      { front: "Quelle variété de sapin est populaire à Noël ?", back: "Nordmann" },
      { front: "Autre nom de la rose de Noël ?", back: "Hellébore" },
      { front: "Autre nom de l'hortensia ?", back: "Hydrangea" },
      { front: "Autre nom du palmier à huile ?", back: "Éléis" },
      { front: "Autre nom de la menthe aux chats ?", back: "Cataire" },
      { front: "Autre nom de la langue de feu (plante) ?", back: "Anthurium" },
      { front: "Autre nom de la plante gruyère ?", back: "Philodendron" },
      { front: "Quel fruit est surnommé le fruit des dieux ?", back: "Le mangoustan" },
      { front: "Autre nom du fruit du dragon ?", back: "Pitaya" },
      { front: "Autre nom de la baie de goji ?", back: "Lyciet" },
      { front: "Autre nom du corossol ?", back: "Cachiment" },
      { front: "Autre nom de la jujube ?", back: "Datte chinoise" },
      { front: "Autre nom du taro ?", back: "Colocase" },
      { front: "Autre nom de la gourde (végétale) ?", back: "Calebasse" },
      { front: "Autre nom de l'hibiscus ?", back: "Rose de Chine" },
      { front: "Autre nom de l'aulne ?", back: "Vergne" },
      { front: "Autre nom de l'oiseau du paradis (plante) ?", back: "Strelitzia" },
      { front: "Autre nom du jacaranda ?", back: "Arbre-fougère" },
      { front: "Autre nom du bleuet ?", back: "Barbeau" },
      { front: "Autre nom de l'arbre à saucisses ?", back: "Kigelia" },
      { front: "Autre nom de l'arbre aux mouchoirs ?", back: "Davidia" },
      { front: "Quel champignon s'appelle aussi coulemelle ?", back: "La lépiote" },
      { front: "Quel champignon est la fausse morille ?", back: "La gyromitre" },
      { front: "Autre nom de la girolle ?", back: "Chanterelle" },
      { front: "Quel est le nom de l'amanite tue-mouches ?", back: "Fausse oronge" },
      { front: "Quel est le nom de l'amanite des Césars ?", back: "Oronge vraie" },
      { front: "Quel est le nom de l'amanite phalloïde ?", back: "Oronge verte" },
      { front: "Quel fruit est le kiwano ?", back: "Le melon à cornes" },
      { front: "Quel arbre pousse dans le désert de Californie ?", back: "L'arbre de Josué" },
      { front: "Comment s'appellent les fruits de l'aubépine ?", back: "Cenelles" },
      { front: "Citrus sinensis = ?", back: "Oranger" },
      { front: "Citrus reticulata = ?", back: "Mandarine" },
      { front: "Citrus juno = ?", back: "Yuzu" },
      { front: "Citrus maxima = ?", back: "Pamplemousse" },
      { front: "Citrus paradisi = ?", back: "Pomélo" },
      { front: "Maladie du blanc chez les plantes ?", back: "Oïdium" },
      { front: "Qu'est-ce que le blob ?", back: "Physarum — organisme unicellulaire ni plante ni animal" },
    ],
  },

  // --- ARTS & ARCHITECTURE ---
  {
    id: "arts-architecture",
    name: "Arts & Architecture",
    icon: "🏛️",
    description: "Peintres, mouvements, architectes de monuments célèbres",
    cards: [
      { front: "Qui a dessiné La Semeuse (pièces de monnaie) ?", back: "Oscar Roty" },
      { front: "Quel groupe expressionniste allemand a été fondé à Dresde en 1905 ?", back: "Die Brücke" },
      { front: "Qui est Andrei Roublev ?", back: "Peintre russe des XIVe-XVe siècles, canonisé" },
      { front: "Quel peintre espagnol est associé au cubisme ?", back: "Juan Gris" },
      { front: "Qui a théorisé le futurisme ?", back: "Marinetti" },
      { front: "Qui a fondé le Nouveau Réalisme ?", back: "Pierre Restany" },
      { front: "Quel artiste est connu pour les Accumulations ?", back: "Arman" },
      { front: "Quel artiste est connu pour les Compressions ?", back: "César" },
      { front: "Quel peintre mexicain est le maître du muralisme ?", back: "Diego Rivera" },
      { front: "Quel mouvement d'art utilise des matériaux pauvres ?", back: "Arte Povera (Giuseppe Penone, Manzoni)" },
      { front: "Qui sont les artistes du Land Art ?", back: "Robert Smithson & Andy Goldsworthy" },
      { front: "Qui est le théoricien des Nabis ?", back: "Maurice Denis" },
      { front: "Qui a créé le terme « impressionnisme » ?", back: "Louis Leroy (critique d'art)" },
      { front: "Quelle artiste japonaise est connue pour ses pois ?", back: "Yayoi Kusama" },
      { front: "Qui a peint Le Talisman ?", back: "Paul Sérusier" },
      { front: "Qui a peint Le Cauchemar ?", back: "Füssli" },
      { front: "Qui a peint Ophélie ?", back: "John Everett Millais" },
      { front: "Le Retable d'Issenheim est de quel peintre ?", back: "Grünewald" },
      { front: "Qui était le maître de Léonard de Vinci ?", back: "Verrocchio" },
      { front: "Qui est le peintre américain ornithologue d'origine française ?", back: "Jean-Jacques Audubon" },
      { front: "Quel artiste a créé le logo d'Antenne 2 ?", back: "Georges Mathieu (abstraction lyrique)" },
      { front: "Qui est le peintre de la Grèce antique le plus célèbre ?", back: "Apelle" },
      { front: "Qu'est-ce que le védutisme ?", back: "Représentation urbaine au XVIIe en Italie" },
      { front: "Qui a conçu le Panthéon de Paris ?", back: "Soufflot" },
      { front: "Qui a conçu l'Arc de Triomphe ?", back: "Chalgrin" },
      { front: "Qui a conçu l'Opéra Bastille ?", back: "Carlos Ott" },
      { front: "Qui a conçu l'Arche de la Défense ?", back: "Spreckelsen" },
      { front: "Qui a conçu le Centre Pompidou ?", back: "Richard Rogers (et Renzo Piano)" },
      { front: "Qui a conçu le Viaduc de Millau ?", back: "Norman Foster" },
      { front: "Qui a conçu la Maison sur la cascade ?", back: "Frank Lloyd Wright" },
      { front: "Qui a conçu le Musée Guggenheim de Bilbao ?", back: "Frank Gehry" },
      { front: "Qui a conçu le MUCEM à Marseille ?", back: "Rudy Ricciotti" },
      { front: "Qui a conçu Saint-Paul de Londres ?", back: "Christopher Wren" },
      { front: "Qui a conçu le Sacré-Cœur ?", back: "Paul Abadie" },
      { front: "Qui a conçu le Palais de l'Élysée ?", back: "Armand-Claude Mollet" },
      { front: "Qui a conçu la BNF ?", back: "Dominique Perrault" },
      { front: "Qui a conçu la Gare du Nord ?", back: "Hittorff" },
      { front: "Qui a conçu le Petit Trianon ?", back: "Gabriel" },
      { front: "Qui a conçu la Saline d'Arc-et-Senans ?", back: "Ledoux" },
      { front: "Muse de Rubens ?", back: "Hélène Fourment" },
      { front: "Muse de Modigliani ?", back: "Jeanne Hébuterne" },
    ],
  },

  // --- LITTÉRATURE : Auteurs & Livres ---
  {
    id: "litterature-auteurs",
    name: "Littérature : qui a écrit quoi ?",
    icon: "📚",
    description: "Associer auteurs et œuvres — des classiques aux prix littéraires",
    cards: [
      { front: "Qui a écrit Winnie l'Ourson ?", back: "A.A. Milne" },
      { front: "Qui a écrit Heidi ?", back: "Johanna Spyri" },
      { front: "Qui a écrit Peter Pan ?", back: "J.M. Barrie" },
      { front: "Qui a écrit Les Bienveillantes ?", back: "Jonathan Littell" },
      { front: "Qui a écrit Oblomov ?", back: "Ivan Gontcharov" },
      { front: "Qui a écrit Tous les matins du monde ?", back: "Pascal Quignard" },
      { front: "Qui a écrit Ne le dis à personne ?", back: "Harlan Coben" },
      { front: "Qui a écrit Orange mécanique ?", back: "Anthony Burgess" },
      { front: "Qui a écrit L'Élégance du hérisson ?", back: "Muriel Barbery" },
      { front: "Qui a écrit La Désobéissance civile ?", back: "Thoreau" },
      { front: "Qui a écrit Fondation (science-fiction) ?", back: "Isaac Asimov" },
      { front: "Qui a écrit Au cœur des ténèbres ?", back: "Joseph Conrad" },
      { front: "Qui a écrit 50 nuances de Grey ?", back: "E.L. James" },
      { front: "Qui a écrit La conjuration des imbéciles ?", back: "John Kennedy Toole" },
      { front: "Qui a écrit Sapiens ?", back: "Yuval Noah Harari" },
      { front: "Qui a écrit Le Grand Sommeil ?", back: "Raymond Chandler" },
      { front: "Qui a écrit American Psycho ?", back: "Bret Easton Ellis" },
      { front: "Qui a écrit Manhattan Transfer ?", back: "John Dos Passos" },
      { front: "Qui a écrit Ulysse ?", back: "James Joyce" },
      { front: "Qui a écrit Le Bruit et la Fureur ?", back: "William Faulkner" },
      { front: "Qui a écrit L'Attrape-Cœurs ?", back: "Salinger" },
      { front: "Qui a écrit Les Sorcières de Salem ?", back: "Arthur Miller" },
      { front: "Qui a écrit La Servante écarlate ?", back: "Margaret Atwood" },
      { front: "Qui a écrit Persépolis ?", back: "Marjane Satrapi" },
      { front: "Qui a écrit Hunger Games ?", back: "Suzanne Collins" },
      { front: "Qui a écrit Le Meilleur des mondes ?", back: "Aldous Huxley" },
      { front: "Qui a écrit Autant en emporte le vent ?", back: "Margaret Mitchell" },
      { front: "Qui a écrit La Case de l'Oncle Tom ?", back: "Harriet Beecher Stowe" },
      { front: "Qui a écrit Le Décaméron ?", back: "Boccace" },
      { front: "Qui a écrit Le Loup des Steppes ?", back: "Hermann Hesse" },
      { front: "Qui a écrit Le Journal de Bridget Jones ?", back: "Helen Fielding" },
      { front: "Qui a écrit Le Tambour ?", back: "Günter Grass" },
      { front: "Qui a écrit L'Amant de Lady Chatterley ?", back: "D.H. Lawrence" },
      { front: "Qui a écrit Le Maître et Marguerite ?", back: "Mikhaïl Boulgakov" },
      { front: "Qui a écrit À l'Ouest, rien de nouveau ?", back: "Erich Maria Remarque" },
      { front: "Qui a écrit Le Monde de Narnia ?", back: "C.S. Lewis" },
      { front: "Qui a écrit 2001, L'Odyssée de l'espace ?", back: "Arthur C. Clarke" },
      { front: "Qui a écrit Jurassic Park ?", back: "Michael Crichton" },
      { front: "Qui a écrit Ne tirez pas sur l'oiseau moqueur ?", back: "Harper Lee" },
      { front: "Qui a écrit Rebecca ?", back: "Daphné du Maurier" },
      { front: "Qui a écrit Sex and the City ?", back: "Candace Bushnell" },
      { front: "Qui a écrit Pierre Lapin ?", back: "Beatrix Potter" },
      { front: "Écuyer de Don Quichotte ?", back: "Sancho Panza" },
      { front: "Femme dans Les Trois Mousquetaires ?", back: "Milady" },
      { front: "Épouse de Balzac ?", back: "Hanska" },
      { front: "Le Misanthrope de Molière : nom du personnage ?", back: "Alceste" },
      { front: "L'Avare de Molière : nom du personnage ?", back: "Harpagon" },
      { front: "Chef de file du Parnasse, né à La Réunion ?", back: "Leconte de Lisle" },
    ],
  },

  // --- MUSIQUE ---
  {
    id: "musique-classique-variete",
    name: "Musique : classique & variété",
    icon: "🎵",
    description: "Compositeurs, chanteurs, opéras et chansons cultes",
    cards: [
      { front: "Quel compositeur grec est célèbre pour sa musique mathématique ?", back: "Xenakis" },
      { front: "Quel est le grand compositeur finlandais ?", back: "Jean Sibelius" },
      { front: "Quel est le grand compositeur norvégien ?", back: "Edvard Grieg" },
      { front: "Quel compositeur estonien est célèbre pour sa musique minimaliste ?", back: "Arvo Pärt" },
      { front: "Qui a composé L'Amour Sorcier ?", back: "Manuel de Falla (espagnol)" },
      { front: "Quelles sœurs françaises sont toutes deux compositrices ?", back: "Lili et Nadia Boulanger" },
      { front: "Qui a composé Porgy and Bess ?", back: "Gershwin" },
      { front: "Qui a composé Le Prince Igor ?", back: "Alexandre Borodine" },
      { front: "Qui a composé O Fortuna (Carmina Burana) ?", back: "Carl Orff" },
      { front: "Qui a composé Giselle (ballet) ?", back: "Adolphe Adam" },
      { front: "Qui a composé Les Indes Galantes ?", back: "Rameau" },
      { front: "Qui a composé le Te Deum ?", back: "Marc-Antoine Charpentier" },
      { front: "Qui a composé L'Enfant et les Sortilèges ?", back: "Ravel" },
      { front: "Quelle chanson est typiquement péruvienne ?", back: "El condor pasa" },
      { front: "Quelle chanteuse allemande est punk / new wave ?", back: "Nina Hagen" },
      { front: "Quels sont les deux castrats les plus célèbres ?", back: "Farinelli et Alessandro Moreschi" },
      { front: "Quel pianiste chinois est mondialement connu ?", back: "Lang-Lang" },
      { front: "Qui était le producteur d'Elvis ?", back: "Le Colonel Parker" },
      { front: "Quel guitariste mexicain est légendaire ?", back: "Carlos Santana" },
      { front: "Qui a créé l'afrobeat ?", back: "Fela Kuti" },
      { front: "Quel genre musical vient de Trinité-et-Tobago ?", back: "Le calypso" },
      { front: "Qui chante « Au fur et à mesure » ?", back: "Liane Foly" },
      { front: "Qui a écrit les paroles de L'Internationale ?", back: "Eugène Pottier" },
      { front: "Qui a composé la musique d'Amélie Poulain ?", back: "Yann Tiersen" },
      { front: "Quel genre musical portugais est célèbre ?", back: "Le fado (Amália Rodrigues)" },
      { front: "Qui chante « Parlez-moi d'amour » ?", back: "Lucienne Boyer" },
      { front: "Qui chante « La java bleue » ?", back: "Fréhel" },
    ],
  },

  // --- CINÉMA & TV ---
  {
    id: "cinema-tv-pdf",
    name: "Cinéma & TV : le saviez-vous ?",
    icon: "🎬",
    description: "Acteurs, réalisateurs, cascadeurs et speakerines",
    cards: [
      { front: "Qui est le célèbre cascadeur français ?", back: "Rémy Julienne" },
      { front: "Quelle actrice jouait Angélique ?", back: "Michèle Mercier" },
      { front: "Quelle actrice jouait Emmanuelle ?", back: "Sylvia Kristel" },
      { front: "Quel Oscar a remporté Simone Signoret ?", back: "Meilleure actrice pour Les Chemins de la haute ville" },
      { front: "Qui est considéré comme le pire réalisateur de l'histoire ?", back: "Ed Wood" },
      { front: "Quelle comédienne de boulevard française est célèbre ?", back: "Jacqueline Maillan" },
      { front: "Qui a réalisé Le Triomphe de la Volonté et Les Dieux du Stade ?", back: "Leni Riefenstahl" },
      { front: "Qui a réalisé Slumdog Millionaire ?", back: "Danny Boyle" },
      { front: "Qui joue Cloclo au cinéma ?", back: "Jérémie Renier" },
      { front: "Qui jouait Black Panther ?", back: "Chadwick Boseman" },
      { front: "Qui est la première cinéaste de l'histoire ?", back: "Alice Guy" },
      { front: "Qui jouait dans Le Cerveau (1969) ?", back: "David Niven" },
      { front: "Qui jouait Robin des Bois dans le film de Michael Curtiz ?", back: "Errol Flynn" },
      { front: "Quelle speakerine française accompagnait Garcimore ?", back: "Denise Fabre" },
      { front: "Qui est la mère d'Antoine de Caunes ?", back: "Jacqueline Joubert (speakerine)" },
    ],
  },

  // --- SPORT ---
  {
    id: "sport-pdf",
    name: "Sport : anecdotes & champions",
    icon: "🏅",
    description: "Champions méconnus, trophées et anecdotes sportives",
    cards: [
      { front: "Comment s'appelle le trophée de la Coupe Davis ?", back: "Le saladier d'argent" },
      { front: "Qu'est-ce que le rallye des gazelles ?", back: "Un rallye féminin" },
      { front: "Qu'est-ce que le pancrace dans la Grèce antique ?", back: "Mix de pugilat et lutte (très violent)" },
      { front: "Qui dirige la NBA (célèbre joueur devenu dirigeant) ?", back: "Larry Bird" },
      { front: "Quelle footballeuse américaine est célèbre pour son engagement ?", back: "Megan Rapinoe" },
      { front: "Quels nageurs handicapés français sont célèbres ?", back: "Philippe Croizon et Théo Curin (lac Titicaca)" },
      { front: "Qui est la « ménagère volante » du sprint de 1948 ?", back: "Fanny Blankers-Koen" },
      { front: "Qu'est-ce que la « Bataille des Sexes » au tennis (1973) ?", back: "Billie Jean King VS Bobby Riggs" },
      { front: "Quel patineur de vitesse américain est légendaire ?", back: "Eric Heiden" },
      { front: "Quelle française est championne d'heptathlon ?", back: "Eunice Barber" },
      { front: "Quel cycliste suisse est spécialiste du contre-la-montre ?", back: "Fabian Cancellara" },
      { front: "Quel karatéka français est champion olympique ?", back: "Steven Da Costa" },
      { front: "Quel escrimeur français des années 40-50 est célèbre ?", back: "Christian d'Oriola" },
      { front: "Quelle cycliste française est championne de VTT ?", back: "Pauline Ferrand-Prévot" },
    ],
  },

  // --- GÉOGRAPHIE ---
  {
    id: "geo-pdf",
    name: "Géographie : villes & lieux",
    icon: "🗺️",
    description: "Noms romains des villes, points culminants, lieux insolites",
    cards: [
      { front: "Nom romain de Bourges ?", back: "Avaricum" },
      { front: "Nom romain de Strasbourg ?", back: "Argentoratum" },
      { front: "Nom romain d'Orléans ?", back: "Cenabum" },
      { front: "Nom romain de Poitiers ?", back: "Limonum" },
      { front: "Nom romain de Tours ?", back: "Caesarodunum" },
      { front: "Nom romain de Rennes ?", back: "Condate" },
      { front: "Quelle est la plus haute ville du monde ?", back: "La Rinconada (Pérou)" },
      { front: "Quel est l'ancien nom de Tallinn ?", back: "Reval" },
      { front: "Quel est l'ancien nom de Chennai (Inde) ?", back: "Madras" },
      { front: "Quel est l'ancien nom d'Essaouira (Maroc) ?", back: "Mogador" },
      { front: "Qu'est-ce que la Kolyma en Russie ?", back: "Région de l'Est, célèbre pour ses goulags" },
      { front: "Qui sont les co-princes d'Andorre ?", back: "Le président français et l'évêque d'Urgel" },
      { front: "Quel est le plus grand étang de France ?", back: "L'étang de Berre" },
      { front: "Quel est l'étang de Camargue le plus connu ?", back: "L'étang de Vaccarès" },
      { front: "Point culminant de l'Allemagne ?", back: "Zugspitze" },
      { front: "Point culminant du Canada ?", back: "Mont Logan" },
      { front: "Point culminant de la Suisse ?", back: "Pointe Dufour" },
      { front: "Point culminant de l'Antarctique ?", back: "Mont Vinson" },
      { front: "Point culminant de l'Autriche ?", back: "Grossglockner" },
      { front: "Point culminant de la Corse ?", back: "Monte Cinto" },
      { front: "Point culminant des Cévennes ?", back: "Mont Aigoual" },
      { front: "Point culminant du Massif armoricain ?", back: "Mont des Avaloirs (Mayenne)" },
      { front: "Quel pont vénitien est le plus célèbre ?", back: "Pont des Soupirs (aussi Rialto)" },
      { front: "Quel pont est célèbre à Florence ?", back: "Ponte Vecchio (+ Corridor de Vasari)" },
      { front: "Comment s'appelle la cathédrale de Milan ?", back: "Le Duomo" },
      { front: "Sur quelle île Mandela a-t-il été emprisonné ?", back: "Robben Island" },
      { front: "Quelle péninsule est au Québec ?", back: "La Gaspésie" },
      { front: "Ancien nom du détroit des Dardanelles ?", back: "Hellespont" },
      { front: "Ancien nom de la mer de Marmara ?", back: "Propontide" },
    ],
  },

  // --- VOCABULAIRE & MOTS RARES ---
  {
    id: "vocabulaire-rare",
    name: "Vocabulaire rare & insolite",
    icon: "🔤",
    description: "Mots rares qu'on peut te demander aux 12 Coups",
    cards: [
      { front: "Comment appelle-t-on le jaune d'œuf en termes scientifiques ?", back: "Vitellus" },
      { front: "Quels sont les Saints de Glace ?", back: "Saint Mamert, Saint Pancrace, Saint Servais" },
      { front: "Comment appelle-t-on la soute à munitions sur un bateau ?", back: "Sainte-Barbe" },
      { front: "Comment appelle-t-on le garde-manger sur un bateau ?", back: "Cambuse" },
      { front: "Comment appelle-t-on la boîte japonaise pour le repas ?", back: "Bento" },
      { front: "Comment appelle-t-on un poète de la Grèce antique ?", back: "Aède" },
      { front: "Comment appelle-t-on un meneur d'éléphant ?", back: "Cornac" },
      { front: "Comment appelle-t-on une vague d'estuaire ?", back: "Mascaret" },
      { front: "Comment appelle-t-on un tapis mural iranien ?", back: "Kilim" },
      { front: "Comment appelle-t-on un édit du tsar ?", back: "Oukase" },
      { front: "Comment appelle-t-on une statue de jeune homme en Grèce ?", back: "Kouros (femme = Koré)" },
      { front: "Comment appelle-t-on l'ancêtre du zoo ?", back: "Ménagerie" },
      { front: "Comment appelle-t-on un ancien cadran solaire ?", back: "Gnomon" },
      { front: "Comment appelle-t-on une branche de vigne ?", back: "Sarment" },
      { front: "Comment appelle-t-on la ceinture du kimono ?", back: "Obi" },
      { front: "Comment appelle-t-on l'odeur de la pluie ?", back: "Petrichor" },
      { front: "Comment appelle-t-on un barde africain ?", back: "Griot" },
      { front: "Comment appelle-t-on l'étude de textes sacrés ?", back: "Exégèse" },
      { front: "Comment appelle-t-on la pièce centrale d'un temple grec ?", back: "Naos" },
      { front: "Comment appelle-t-on la partie entre deux créneaux ?", back: "Merlon" },
      { front: "Comment appelle-t-on un dragon qui se mord la queue ?", back: "Ouroboros" },
      { front: "Comment appelle-t-on la tête d'une bague (avec la pierre) ?", back: "Chaton" },
      { front: "Comment appelle-t-on la réincarnation en philosophie ?", back: "Métempsychose" },
      { front: "Comment appelle-t-on une peinture en rond ?", back: "Tondo" },
      { front: "Comment appelle-t-on un imperméable breton ?", back: "Kabic" },
      { front: "Qu'est-ce qu'un kakémono ?", back: "Panneau japonais vertical (horizontal = makemono)" },
      { front: "Comment appelle-t-on un porteur d'encens ?", back: "Thuriféraire" },
      { front: "Comment appelle-t-on la forme d'un donut ?", back: "Tore" },
      { front: "Qu'est-ce qu'un oued ?", back: "Fleuve d'Afrique du Nord (souvent à sec)" },
      { front: "Comment appelle-t-on la casserole pour fondue ?", back: "Caquelon" },
      { front: "Comment appelle-t-on le vol d'oiseau en ligne droite ?", back: "Orthodromie" },
      { front: "Comment appelle-t-on la ponte des poissons ?", back: "Frai (lieu = frayère)" },
      { front: "Comment appelle-t-on un jeune garçon nu dans l'art ?", back: "Putto" },
      { front: "Qu'est-ce que l'impeachment ?", back: "Procédure de destitution aux USA" },
      { front: "Qu'est-ce qu'un mont-de-piété ?", back: "Établissement de prêt sur gage (surnommé « ma tante »)" },
      { front: "Qu'est-ce qu'un athanor ?", back: "Fourneau d'alchimiste" },
      { front: "Comment appelle-t-on un livre antique à feuilles cousues ?", back: "Codex" },
      { front: "Comment appelle-t-on un employé de change en banque ?", back: "Cambiste" },
      { front: "Comment appelle-t-on un délateur en Grèce antique ?", back: "Sycophante" },
      { front: "Qu'est-ce que le petrichor ?", back: "L'odeur de la terre après la pluie" },
    ],
  },

  // --- SCIENCES & MÉDECINE ---
  {
    id: "sciences-medecine-pdf",
    name: "Sciences & Médecine",
    icon: "🔬",
    description: "Inventeurs, termes médicaux et découvertes",
    cards: [
      { front: "Qui a inventé le parachute ?", back: "André-Jacques Garnerin" },
      { front: "Qui a inventé l'ascenseur ?", back: "Félix Léon Édoux" },
      { front: "Qui a inventé le vaccin contre la polio ?", back: "Jonas Salk" },
      { front: "Qui a inventé la pilule contraceptive ?", back: "Gregory Pincus" },
      { front: "Qui a découvert le bacille de la tuberculose ?", back: "Robert Koch" },
      { front: "Qui a inventé le vaccin contre la variole ?", back: "Jenner" },
      { front: "Quel chirurgien sud-africain est célèbre pour les greffes ?", back: "Barnard (première greffe du cœur)" },
      { front: "Qui a réalisé la première greffe de rein en France ?", back: "Jean Hamburger" },
      { front: "Qui est le premier Américain dans l'espace ?", back: "Alan Shepard" },
      { front: "Qui a découvert les lois de l'hérédité avec des petits pois ?", back: "Gregor Mendel" },
      { front: "Qui a inventé la méthode de contraception naturelle Ogino ?", back: "Ogino (gynécologue japonais)" },
      { front: "Qui a fondé l'homéopathie ?", back: "Samuel Hahnemann (1778)" },
      { front: "Qui a créé le système binaire (informatique) ?", back: "George Boole" },
      { front: "Qui a écrit le premier programme informatique ?", back: "Ada Lovelace (fille de Lord Byron)" },
      { front: "Comment s'appelle le mal de mer en termes médicaux ?", back: "Naupathie" },
      { front: "Comment appelle-t-on le blanchissement des cheveux ?", back: "Canitie" },
      { front: "Comment appelle-t-on la mauvaise haleine ?", back: "Halitose" },
      { front: "Comment appelle-t-on la chute de cheveux ?", back: "Alopécie" },
      { front: "Comment appelle-t-on une ampoule (cloque) ?", back: "Phlyctène" },
      { front: "Comment appelle-t-on un grain de beauté ?", back: "Naevus" },
      { front: "Comment appelle-t-on les taches de rousseur ?", back: "Éphélides" },
      { front: "Qui a inventé la guillotine (le mécanisme) ?", back: "Antoine Louis (d'où « Louison »)" },
      { front: "Qui est la première femme dans l'espace ?", back: "Valentina Terechkova" },
      { front: "Qui a inventé la première automobile ?", back: "Amédée Bollée (L'Obéissante)" },
      { front: "Qui a inventé le microscope ?", back: "Van Leeuwenhoek" },
    ],
  },

  // --- MONNAIES DU MONDE ---
  {
    id: "monnaies-monde",
    name: "Monnaies du monde",
    icon: "💰",
    description: "Quelle monnaie pour quel pays ?",
    cards: [
      { front: "Monnaie d'Israël ?", back: "Shekel" },
      { front: "Monnaie de Hongrie ?", back: "Forint" },
      { front: "Monnaie de Thaïlande ?", back: "Baht" },
      { front: "Monnaie du Vietnam ?", back: "Dong" },
      { front: "Monnaie d'Afrique du Sud ?", back: "Rand" },
      { front: "Monnaie du Brésil ?", back: "Real" },
      { front: "Monnaie d'Haïti ?", back: "Gourde" },
      { front: "Monnaie d'Ukraine ?", back: "Hryvnia" },
      { front: "Monnaie de Roumanie ?", back: "Leu" },
      { front: "Monnaie du Pérou ?", back: "Sol" },
      { front: "Monnaie du Venezuela ?", back: "Bolivar" },
      { front: "Monnaie d'Iran ?", back: "Rial" },
      { front: "Monnaie de Malaisie ?", back: "Ringgit" },
      { front: "Monnaie de Mongolie ?", back: "Tugrik" },
      { front: "Monnaie d'Afghanistan ?", back: "Afghani" },
      { front: "Monnaie du Nigeria ?", back: "Naira" },
      { front: "Monnaie du Ghana ?", back: "Cedi" },
      { front: "Monnaie de Madagascar ?", back: "Ariary" },
      { front: "Monnaie du Cambodge ?", back: "Riel" },
      { front: "Monnaie du Laos ?", back: "Kip" },
      { front: "Monnaie du Bangladesh ?", back: "Taka" },
      { front: "Monnaie du Myanmar ?", back: "Kyat" },
      { front: "Monnaie du Costa Rica ?", back: "Colon" },
      { front: "Monnaie du Panama ?", back: "Balboa" },
      { front: "Monnaie de l'Éthiopie ?", back: "Birr" },
    ],
  },

  // --- HISTOIRE & DIVERS ---
  {
    id: "histoire-divers-pdf",
    name: "Histoire & Divers",
    icon: "📜",
    description: "Révolutions, dirigeants, anecdotes historiques",
    cards: [
      { front: "Roi de Belgique actuel ?", back: "Philippe Ier (et Mathilde)" },
      { front: "Roi des Pays-Bas actuel ?", back: "Willem-Alexander" },
      { front: "Roi d'Espagne actuel ?", back: "Felipe VI (et Letizia)" },
      { front: "Enfants de William et Kate ?", back: "George, Charlotte, Louis" },
      { front: "Enfants de Harry et Meghan ?", back: "Archie, Lilibet" },
      { front: "Révolution des Œillets : quel pays et quelle année ?", back: "Portugal, 1974" },
      { front: "Révolution de Velours : quel pays ?", back: "Tchécoslovaquie, 1989" },
      { front: "Révolution Orange : quel pays ?", back: "Ukraine, 2004" },
      { front: "Révolution de Jasmin : quel pays ?", back: "Tunisie, 2011" },
      { front: "Révolution des Parapluies : quel pays ?", back: "Hong-Kong, 2014" },
      { front: "Révolution des Roses : quel pays ?", back: "Géorgie, 2003" },
      { front: "Révolution des Tulipes : quel pays ?", back: "Kirghizistan, 2005" },
      { front: "Qui est le premier aéronaute ?", back: "Pilâtre de Rozier (mort en voulant traverser la Manche)" },
      { front: "Qui est la première femme ministre en France ?", back: "Germaine Poinso-Chapuis" },
      { front: "Compagnon de Jean Moulin ?", back: "Daniel Cordier" },
      { front: "Comment s'appelait la monnaie de la Révolution ?", back: "L'assignat" },
      { front: "Comment s'appelle la voiture typique de la RDA ?", back: "La Trabant" },
      { front: "Qui a fondé RSF (Reporters sans frontières) ?", back: "Robert Ménard" },
      { front: "Qui est le défenseur des droits homosexuels américain célèbre ?", back: "Harvey Milk" },
      { front: "Quel métier fait Spirou ?", back: "Groom" },
      { front: "Nom complet de Barbara Millicent Roberts ?", back: "Barbie" },
      { front: "Qui a nommé les mois du calendrier républicain ?", back: "Fabre d'Églantine" },
      { front: "Comment s'appelle le cheval de Caligula ?", back: "Incitatus" },
      { front: "Quel pape a signé le Concordat avec Napoléon en 1801 ?", back: "Pie VII" },
      { front: "Quel est le héros national albanais ?", back: "Skanderbeg" },
    ],
  },

  // --- GASTRONOMIE PDF ---
  {
    id: "gastronomie-pdf",
    name: "Gastronomie avancée",
    icon: "👨‍🍳",
    description: "Cuisiniers historiques, plats du monde, fromages",
    cards: [
      { front: "Qui est Taillevent ?", back: "Cuisinier du Moyen Âge, auteur du Viandier" },
      { front: "Comment s'appelle le restaurant de la Gare de Lyon à Paris ?", back: "Le Train Bleu" },
      { front: "Quel fromage de Savoie est le « prince des gruyères » ?", back: "Le Beaufort" },
      { front: "Quel fromage a la forme d'une pyramide tronquée ?", back: "Le Valençay" },
      { front: "Quel fromage est emballé dans des feuilles de châtaignier ?", back: "Le Banon" },
      { front: "Quel est le fromage cévenol ?", back: "Le Pélardon" },
      { front: "Quel est le fromage du Nord ?", back: "Le Maroilles" },
      { front: "Comment s'appelle la bouillabaisse bretonne ?", back: "La cotriade" },
      { front: "Comment s'appelle la soupe paysanne du Sud-Ouest ?", back: "La garbure" },
      { front: "Comment s'appelle le nougat espagnol ?", back: "Le turrón" },
      { front: "Comment s'appelle le potage russe ?", back: "Le bortsch" },
      { front: "Comment s'appelle la soupe japonaise ?", back: "Le miso" },
      { front: "Quelle est la spécialité de la Nouvelle-Orléans ?", back: "Le jambalaya" },
      { front: "Comment s'appelle le gâteau corse ?", back: "Le fiadone" },
      { front: "Comment s'appelle le beignet japonais ?", back: "Le tempura" },
      { front: "Qui est Apicius ?", back: "Cuisinier antique romain" },
      { front: "Comment s'appelle le nougat espagnol ?", back: "Turrón" },
    ],
  },

  // --- HISTOIRE ANCIENNE & MYTHOLOGIE ---
  {
    id: "histoire-ancienne-mytho",
    name: "Histoire ancienne & Mythologie",
    icon: "⚔️",
    description: "Antiquité, Moyen Âge, mythologie grecque et inca",
    cards: [
      { front: "Géant aux 100 yeux dans la mythologie grecque ?", back: "Argos" },
      { front: "Fondateur mythique de Thèbes ?", back: "Cadmos" },
      { front: "Qui a été transformée en Grande Ourse ?", back: "Callisto" },
      { front: "Qui a été mangé par une baleine dans la Bible ?", back: "Jonas" },
      { front: "Dieu inca du Soleil ?", back: "Inti" },
      { front: "Déesse inca de la Terre ?", back: "Pachamama" },
      { front: "Mère d'Alexandre le Grand ?", back: "Olympias" },
      { front: "Port de la Rome antique ?", back: "Ostie" },
      { front: "Phrase des gladiateurs à l'empereur ?", back: "Ave Caesar, morituri te salutant" },
      { front: "Général de l'empereur Justinien ?", back: "Bélisaire" },
      { front: "Roi des Éburons, héros celte en Belgique ?", back: "Ambiorix" },
      { front: "Dictateur romain du Ier siècle av. J.-C. ?", back: "Sylla" },
      { front: "Cheval de Caligula (qu'il voulait faire consul) ?", back: "Incitatus" },
      { front: "Les deux tendances politiques à Rome ?", back: "Populares et Optimates" },
      { front: "Apogée d'Athènes (période de 50 ans) ?", back: "Pentécontaétie" },
      { front: "Comment appelle-t-on une guerre civile grecque ?", back: "Stasis" },
      { front: "Code de loi byzantin de 885 ?", back: "Épanagogé (Eisagogé)" },
      { front: "Révolte des esclaves dans le califat abbasside ?", back: "Révolte des Zanj" },
      { front: "Conseillers de Charles VI ?", back: "Les Marmousets" },
      { front: "Mouvement de destruction des machines au XIXe ?", back: "Luddisme" },
      { front: "Criminologue français du XIXe (anthropométrie) ?", back: "Alphonse Bertillon" },
      { front: "Coup d'État raté en 1812 contre Napoléon ?", back: "Conspiration de Malet" },
      { front: "Affaire judiciaire liée à Mazamet ?", back: "L'affaire Sirven" },
      { front: "Dandy anglais le plus célèbre ?", back: "George Brummell" },
      { front: "Délégué aux loisirs du Front Populaire ?", back: "Léo Lagrange" },
      { front: "Dirigeant de Saint-Marin ?", back: "Capitaine-Régent" },
      { front: "Mouvement culturel espagnol des années 80 ?", back: "La Movida" },
      { front: "Célèbre forgeron japonais ?", back: "Masamune" },
      { front: "Patron des curés (saint français) ?", back: "Le Curé d'Ars" },
      { front: "Dirigeant bolivien célèbre ?", back: "Evo Morales" },
      { front: "Dirigeant hongrois controversé ?", back: "Viktor Orbán" },
      { front: "Roi du Lesotho ?", back: "Letsie III" },
      { front: "Qui a nommé les mois du calendrier républicain ?", back: "Fabre d'Églantine" },
      { front: "Première femme ministre en France ?", back: "Germaine Poinso-Chapuis" },
      { front: "Premier aéronaute (mort en traversant la Manche) ?", back: "Pilâtre de Rozier" },
    ],
  },

  // --- GÉOGRAPHIE AVANCÉE (manquants) ---
  {
    id: "geo-avancee",
    name: "Géographie avancée",
    icon: "🌐",
    description: "Lieux, régions, villes méconnues du monde",
    cards: [
      { front: "Golfe du nord de l'Australie ?", back: "Golfe de Carpentarie" },
      { front: "Port de Syrie ?", back: "Lattaquié" },
      { front: "Camp militaire au Kentucky (réserve d'or) ?", back: "Fort Knox" },
      { front: "Ville de lutherie en France ?", back: "Mirecourt (Vosges)" },
      { front: "Ancien nom du Lesotho ?", back: "Basutoland" },
      { front: "Plaines de Tanzanie (grandes migrations) ?", back: "Serengeti" },
      { front: "Ville suisse célèbre pour son pont couvert ?", back: "Lucerne" },
      { front: "Zoo des Yvelines ?", back: "Thoiry" },
      { front: "Haras célèbre de l'Orne ?", back: "Haras du Pin" },
      { front: "Villa d'Edmond Rostand à Cambo-les-Bains ?", back: "Arnaga" },
      { front: "Grande île russe du Pacifique ?", back: "Sakhaline" },
      { front: "Ville romaine en Libye (Cyrénaïque) ?", back: "Cyrène" },
      { front: "Péninsule québécoise ?", back: "Gaspésie" },
      { front: "Région de Corse au nord-ouest ?", back: "Balagne" },
      { front: "Grande forêt de l'Allier ?", back: "Tronçais" },
      { front: "Château célèbre près de la mer Morte ?", back: "Massada" },
      { front: "Quartier historique d'Athènes ?", back: "Plaka" },
      { front: "Plus haute ville du monde ?", back: "La Rinconada (Pérou)" },
      { front: "Capitale de la Sibérie ?", back: "Novossibirsk" },
      { front: "Ancien nom de Tallinn ?", back: "Reval" },
      { front: "Ancien nom d'Essaouira ?", back: "Mogador" },
      { front: "Ancien nom de Chennai ?", back: "Madras" },
      { front: "Ancien nom de Maputo ?", back: "Lourenço Marques" },
      { front: "Ancien nom de Bichkek ?", back: "Frounzé" },
      { front: "École militaire de La Flèche ?", back: "Le Prytanée" },
    ],
  },

  // --- TISSUS & DIVERS ---
  {
    id: "tissus-divers",
    name: "Tissus, objets & divers",
    icon: "🧵",
    description: "Tissus du monde, objets, termes spéciaux",
    cards: [
      { front: "Tissu africain teint à base de boue ?", back: "Bogolan" },
      { front: "Tissu indonésien à motifs teints à la cire ?", back: "Batik" },
      { front: "Tissu anglais épais typique de l'Écosse ?", back: "Tweed" },
      { front: "Tissu à effet ondulé ?", back: "Moire" },
      { front: "Tissu indien multicolore ?", back: "Madras" },
      { front: "Voiture typique de la RDA ?", back: "Trabant" },
      { front: "Défenseur des droits homosexuels américain ?", back: "Harvey Milk" },
      { front: "Fondateur de Reporters sans frontières ?", back: "Robert Ménard" },
      { front: "Quel métier fait Spirou ?", back: "Groom" },
      { front: "Mannequin emblématique des années 60 ?", back: "Twiggy" },
      { front: "Voyageur français du froid avec des chiens ?", back: "Nicolas Vanier" },
      { front: "Que signifie le Boxing Day (26 décembre) ?", back: "Jour où on offre des cadeaux aux employés (tradition britannique)" },
      { front: "Commissaire célèbre qui a traqué Mesrine ?", back: "Robert Broussard" },
      { front: "Coiffeur anglais légendaire ?", back: "Vidal Sassoon" },
      { front: "Première Miss France (1920) ?", back: "Agnès Souret" },
    ],
  },

  // --- CAPITALES DU MONDE ---
  {
    id: "capitales-monde",
    name: "Capitales du monde",
    icon: "🏙️",
    description: "197 pays — toutes les capitales à connaître",
    cards: [
      // Europe
      { front: "Capitale de l'Albanie ?", back: "Tirana" },
      { front: "Capitale de l'Allemagne ?", back: "Berlin" },
      { front: "Capitale de l'Andorre ?", back: "Andorre-la-Vieille" },
      { front: "Capitale de l'Autriche ?", back: "Vienne" },
      { front: "Capitale de la Belgique ?", back: "Bruxelles" },
      { front: "Capitale de la Biélorussie ?", back: "Minsk" },
      { front: "Capitale de la Bosnie ?", back: "Sarajevo" },
      { front: "Capitale de la Bulgarie ?", back: "Sofia" },
      { front: "Capitale de la Croatie ?", back: "Zagreb" },
      { front: "Capitale du Danemark ?", back: "Copenhague" },
      { front: "Capitale de l'Espagne ?", back: "Madrid" },
      { front: "Capitale de l'Estonie ?", back: "Tallinn" },
      { front: "Capitale de la Finlande ?", back: "Helsinki" },
      { front: "Capitale de la Grèce ?", back: "Athènes" },
      { front: "Capitale de la Hongrie ?", back: "Budapest" },
      { front: "Capitale de l'Irlande ?", back: "Dublin" },
      { front: "Capitale de l'Islande ?", back: "Reykjavik" },
      { front: "Capitale de l'Italie ?", back: "Rome" },
      { front: "Capitale du Kosovo ?", back: "Pristina" },
      { front: "Capitale de la Lettonie ?", back: "Riga" },
      { front: "Capitale de la Lituanie ?", back: "Vilnius" },
      { front: "Capitale du Luxembourg ?", back: "Luxembourg" },
      { front: "Capitale de la Macédoine du Nord ?", back: "Skopje" },
      { front: "Capitale de Malte ?", back: "La Valette" },
      { front: "Capitale de la Moldavie ?", back: "Chișinău" },
      { front: "Capitale de Monaco ?", back: "Monaco" },
      { front: "Capitale du Monténégro ?", back: "Podgorica" },
      { front: "Capitale de la Norvège ?", back: "Oslo" },
      { front: "Capitale des Pays-Bas ?", back: "Amsterdam" },
      { front: "Capitale de la Pologne ?", back: "Varsovie" },
      { front: "Capitale du Portugal ?", back: "Lisbonne" },
      { front: "Capitale de la République tchèque ?", back: "Prague" },
      { front: "Capitale de la Roumanie ?", back: "Bucarest" },
      { front: "Capitale du Royaume-Uni ?", back: "Londres" },
      { front: "Capitale de la Russie ?", back: "Moscou" },
      { front: "Capitale de la Serbie ?", back: "Belgrade" },
      { front: "Capitale de la Slovaquie ?", back: "Bratislava" },
      { front: "Capitale de la Slovénie ?", back: "Ljubljana" },
      { front: "Capitale de la Suède ?", back: "Stockholm" },
      { front: "Capitale de la Suisse ?", back: "Berne" },
      { front: "Capitale de l'Ukraine ?", back: "Kiev" },
      // Asie
      { front: "Capitale de l'Afghanistan ?", back: "Kaboul" },
      { front: "Capitale de l'Arabie saoudite ?", back: "Riyad" },
      { front: "Capitale de l'Arménie ?", back: "Erevan" },
      { front: "Capitale de l'Azerbaïdjan ?", back: "Bakou" },
      { front: "Capitale du Bangladesh ?", back: "Dacca" },
      { front: "Capitale du Bhoutan ?", back: "Thimphou" },
      { front: "Capitale de la Birmanie (Myanmar) ?", back: "Naypyidaw" },
      { front: "Capitale du Cambodge ?", back: "Phnom Penh" },
      { front: "Capitale de la Chine ?", back: "Pékin (Beijing)" },
      { front: "Capitale de la Corée du Nord ?", back: "Pyongyang" },
      { front: "Capitale de la Corée du Sud ?", back: "Séoul" },
      { front: "Capitale des Émirats arabes unis ?", back: "Abou Dabi" },
      { front: "Capitale de la Géorgie ?", back: "Tbilissi" },
      { front: "Capitale de l'Inde ?", back: "New Delhi" },
      { front: "Capitale de l'Indonésie ?", back: "Jakarta" },
      { front: "Capitale de l'Irak ?", back: "Bagdad" },
      { front: "Capitale de l'Iran ?", back: "Téhéran" },
      { front: "Capitale d'Israël (proclamée) ?", back: "Jérusalem" },
      { front: "Capitale du Japon ?", back: "Tokyo" },
      { front: "Capitale de la Jordanie ?", back: "Amman" },
      { front: "Capitale du Kazakhstan ?", back: "Astana" },
      { front: "Capitale du Kirghizistan ?", back: "Bichkek" },
      { front: "Capitale du Koweït ?", back: "Koweït" },
      { front: "Capitale du Laos ?", back: "Vientiane" },
      { front: "Capitale du Liban ?", back: "Beyrouth" },
      { front: "Capitale de la Malaisie ?", back: "Kuala Lumpur" },
      { front: "Capitale des Maldives ?", back: "Malé" },
      { front: "Capitale de la Mongolie ?", back: "Oulan-Bator" },
      { front: "Capitale du Népal ?", back: "Katmandou" },
      { front: "Capitale d'Oman ?", back: "Mascate" },
      { front: "Capitale de l'Ouzbékistan ?", back: "Tachkent" },
      { front: "Capitale du Pakistan ?", back: "Islamabad" },
      { front: "Capitale des Philippines ?", back: "Manille" },
      { front: "Capitale du Qatar ?", back: "Doha" },
      { front: "Capitale de Singapour ?", back: "Singapour" },
      { front: "Capitale du Sri Lanka ?", back: "Sri Jayawardenapura Kotte" },
      { front: "Capitale de la Syrie ?", back: "Damas" },
      { front: "Capitale du Tadjikistan ?", back: "Douchanbé" },
      { front: "Capitale de la Thaïlande ?", back: "Bangkok" },
      { front: "Capitale du Timor oriental ?", back: "Dili" },
      { front: "Capitale du Turkménistan ?", back: "Achgabat" },
      { front: "Capitale de la Turquie ?", back: "Ankara" },
      { front: "Capitale du Vietnam ?", back: "Hanoï" },
      { front: "Capitale du Yémen ?", back: "Sanaa" },
      // Afrique
      { front: "Capitale de l'Afrique du Sud (exécutive) ?", back: "Pretoria" },
      { front: "Capitale de l'Algérie ?", back: "Alger" },
      { front: "Capitale de l'Angola ?", back: "Luanda" },
      { front: "Capitale du Bénin ?", back: "Porto-Novo" },
      { front: "Capitale du Botswana ?", back: "Gaborone" },
      { front: "Capitale du Burkina Faso ?", back: "Ouagadougou" },
      { front: "Capitale du Burundi ?", back: "Gitega" },
      { front: "Capitale du Cameroun ?", back: "Yaoundé" },
      { front: "Capitale du Tchad ?", back: "N'Djamena" },
      { front: "Capitale de la Côte d'Ivoire ?", back: "Yamoussoukro" },
      { front: "Capitale de Djibouti ?", back: "Djibouti" },
      { front: "Capitale de l'Égypte ?", back: "Le Caire" },
      { front: "Capitale de l'Érythrée ?", back: "Asmara" },
      { front: "Capitale de l'Éthiopie ?", back: "Addis-Abeba" },
      { front: "Capitale du Gabon ?", back: "Libreville" },
      { front: "Capitale du Ghana ?", back: "Accra" },
      { front: "Capitale de la Guinée ?", back: "Conakry" },
      { front: "Capitale du Kenya ?", back: "Nairobi" },
      { front: "Capitale de la Libye ?", back: "Tripoli" },
      { front: "Capitale de Madagascar ?", back: "Antananarivo" },
      { front: "Capitale du Mali ?", back: "Bamako" },
      { front: "Capitale du Maroc ?", back: "Rabat" },
      { front: "Capitale de la Mauritanie ?", back: "Nouakchott" },
      { front: "Capitale du Mozambique ?", back: "Maputo" },
      { front: "Capitale du Niger ?", back: "Niamey" },
      { front: "Capitale du Nigeria ?", back: "Abuja" },
      { front: "Capitale de l'Ouganda ?", back: "Kampala" },
      { front: "Capitale du Rwanda ?", back: "Kigali" },
      { front: "Capitale du Sénégal ?", back: "Dakar" },
      { front: "Capitale de la Somalie ?", back: "Mogadiscio" },
      { front: "Capitale du Soudan ?", back: "Khartoum" },
      { front: "Capitale du Soudan du Sud ?", back: "Djouba" },
      { front: "Capitale de la Tanzanie ?", back: "Dodoma" },
      { front: "Capitale du Togo ?", back: "Lomé" },
      { front: "Capitale de la Tunisie ?", back: "Tunis" },
      { front: "Capitale de la Zambie ?", back: "Lusaka" },
      { front: "Capitale du Zimbabwe ?", back: "Harare" },
      // Amériques
      { front: "Capitale de l'Argentine ?", back: "Buenos Aires" },
      { front: "Capitale de la Bolivie ?", back: "Sucre (constitutionnelle) / La Paz (siège du gouvernement)" },
      { front: "Capitale du Brésil ?", back: "Brasília" },
      { front: "Capitale du Canada ?", back: "Ottawa" },
      { front: "Capitale du Chili ?", back: "Santiago" },
      { front: "Capitale de la Colombie ?", back: "Bogota" },
      { front: "Capitale du Costa Rica ?", back: "San José" },
      { front: "Capitale de Cuba ?", back: "La Havane" },
      { front: "Capitale de l'Équateur ?", back: "Quito" },
      { front: "Capitale des États-Unis ?", back: "Washington D.C." },
      { front: "Capitale du Guatemala ?", back: "Guatemala" },
      { front: "Capitale d'Haïti ?", back: "Port-au-Prince" },
      { front: "Capitale du Honduras ?", back: "Tegucigalpa" },
      { front: "Capitale de la Jamaïque ?", back: "Kingston" },
      { front: "Capitale du Mexique ?", back: "Mexico" },
      { front: "Capitale du Nicaragua ?", back: "Managua" },
      { front: "Capitale du Panama ?", back: "Panama" },
      { front: "Capitale du Paraguay ?", back: "Asunción" },
      { front: "Capitale du Pérou ?", back: "Lima" },
      { front: "Capitale de la République dominicaine ?", back: "Saint-Domingue" },
      { front: "Capitale du Suriname ?", back: "Paramaribo" },
      { front: "Capitale de l'Uruguay ?", back: "Montevideo" },
      { front: "Capitale du Venezuela ?", back: "Caracas" },
      // Océanie
      { front: "Capitale de l'Australie ?", back: "Canberra" },
      { front: "Capitale des Fidji ?", back: "Suva" },
      { front: "Capitale de la Nouvelle-Zélande ?", back: "Wellington" },
      { front: "Capitale de la Papouasie-Nouvelle-Guinée ?", back: "Port Moresby" },
    ],
  },
];
