// Fun Facts — Packs pour les 12 Coups de Midi
// Infos insolites, culture générale flash, régions, gastronomie
const FUNFACTS_PACKS = [

  // ===== 1. ANIMAUX INSOLITES =====
  {
    id: "animaux-insolites",
    name: "Animaux insolites",
    icon: "🦑",
    description: "Noms bizarres, records et anecdotes animales",
    cards: [
      { front: "Quel animal peut survivre dans le vide spatial ?", back: "Le tardigrade (ou ourson d'eau), moins de 1 mm" },
      { front: "Quel est le seul mammifère capable de voler ?", back: "La chauve-souris (les écureuils volants planent, ils ne volent pas)" },
      { front: "Combien de cœurs possède une pieuvre ?", back: "3 cœurs (2 branchiaux + 1 systémique)" },
      { front: "Quel animal a le cœur dans la tête ?", back: "La crevette" },
      { front: "Quel est l'animal terrestre le plus rapide ?", back: "Le guépard (~120 km/h sur courte distance)" },
      { front: "Quel oiseau peut voler en arrière ?", back: "Le colibri (seul oiseau capable)" },
      { front: "Quel animal dort debout ?", back: "Le cheval (grâce à un système de blocage des articulations)" },
      { front: "Quel est le plus grand poisson du monde ?", back: "Le requin-baleine (jusqu'à 18 mètres)" },
      { front: "Comment appelle-t-on le cri du cerf ?", back: "Le brame (ou bramement)" },
      { front: "Comment appelle-t-on le cri du corbeau ?", back: "Le croassement (≠ coassement de la grenouille)" },
      { front: "Comment appelle-t-on le cri de la chouette ?", back: "Le hululement (ou chuintement)" },
      { front: "Comment appelle-t-on le mâle de l'oie ?", back: "Le jars" },
      { front: "Comment appelle-t-on le petit du lièvre ?", back: "Le levraut" },
      { front: "Comment appelle-t-on le petit de la biche ?", back: "Le faon" },
      { front: "Quel est le seul continent sans reptiles ?", back: "L'Antarctique" },
      { front: "Quel mammifère pond des œufs ?", back: "L'ornithorynque et les échidnés (monotrèmes)" },
      { front: "De quelle couleur est le sang des poulpes ?", back: "Bleu (à cause du cuivre dans l'hémocyanine)" },
      { front: "Quel animal a les empreintes digitales les plus proches de l'homme ?", back: "Le koala" },
      { front: "Combien de pattes a une araignée ?", back: "8 (ce n'est pas un insecte mais un arachnide)" },
      { front: "Quelle est la durée de gestation d'un éléphant ?", back: "22 mois (la plus longue chez les mammifères terrestres)" },
      { front: "Comment appelle-t-on un groupe de lions ?", back: "Une troupe (ou une harde)" },
      { front: "Quel papillon migre du Canada au Mexique chaque année ?", back: "Le monarque (Danaus plexippus), ~4 000 km" },
      { front: "Quel poisson peut changer de sexe au cours de sa vie ?", back: "Le mérou (et le poisson-clown)" },
      { front: "Quel est le plus petit oiseau du monde ?", back: "Le colibri d'Elena (~5 cm, ~2 g)" },
      { front: "Quel est le seul félin qui ne peut pas rétracter ses griffes ?", back: "Le guépard" },
      { front: "Comment appelle-t-on l'élevage des abeilles ?", back: "L'apiculture" },
      { front: "Comment appelle-t-on l'élevage des vers à soie ?", back: "La sériciculture" },
      { front: "Comment appelle-t-on l'élevage des huîtres ?", back: "L'ostréiculture" },
      { front: "Quel animal est le symbole de la médecine ?", back: "Le serpent (bâton d'Asclépios / caducée)" },
      { front: "Quelle est la seule espèce de singe sauvage en Europe ?", back: "Le macaque de Barbarie (magot), à Gibraltar" },
      { front: "Combien d'estomacs possède une vache ?", back: "4 (panse, bonnet, feuillet, caillette)" },
      { front: "Comment appelle-t-on l'élevage des escargots ?", back: "L'héliciculture" },
      { front: "Quel animal peut dormir jusqu'à 22 heures par jour ?", back: "Le koala" },
      { front: "Quel est l'insecte le plus fort par rapport à son poids ?", back: "Le scarabée bousier (peut tirer 1 141 fois son poids)" },
    ],
  },

  // ===== 2. CORPS HUMAIN =====
  {
    id: "corps-humain",
    name: "Corps humain",
    icon: "🧠",
    description: "Anecdotes étonnantes sur le corps humain",
    cards: [
      { front: "Combien d'os dans le corps humain adulte ?", back: "206 os (un bébé en a environ 270)" },
      { front: "Quel est le plus grand organe du corps humain ?", back: "La peau (~2 m² de surface)" },
      { front: "Quel est le plus petit os du corps humain ?", back: "L'étrier, dans l'oreille (environ 3 mm)" },
      { front: "Quel est le muscle le plus puissant du corps ?", back: "Le masséter (muscle de la mâchoire)" },
      { front: "Combien de litres de sang contient le corps humain ?", back: "Environ 5 litres chez un adulte" },
      { front: "Quelle est la longueur totale de l'intestin grêle ?", back: "Environ 6 à 7 mètres" },
      { front: "Combien de dents possède un adulte ?", back: "32 dents (dont 4 dents de sagesse)" },
      { front: "Quelle est la seule partie du corps qui ne reçoit pas de sang ?", back: "La cornée de l'œil (nourrie par le liquide lacrymal)" },
      { front: "Quel est le seul os du corps qui n'est relié à aucun autre ?", back: "L'os hyoïde (dans la gorge)" },
      { front: "Quelle est la vitesse d'un éternuement ?", back: "Environ 150 km/h" },
      { front: "Combien de neurones dans le cerveau humain ?", back: "Environ 86 milliards" },
      { front: "Quel pourcentage d'eau contient le corps humain adulte ?", back: "Environ 60 %" },
      { front: "Quel organe consomme 20 % de l'énergie du corps ?", back: "Le cerveau (alors qu'il ne représente que 2 % du poids)" },
      { front: "Combien de kilomètres de vaisseaux sanguins dans le corps ?", back: "Environ 100 000 km" },
      { front: "Combien de fois le cœur bat-il en moyenne par jour ?", back: "Environ 100 000 fois" },
      { front: "Quelle est la durée de vie d'un globule rouge ?", back: "Environ 120 jours" },
      { front: "Quel est le plus long nerf du corps humain ?", back: "Le nerf sciatique" },
      { front: "Quel est le plus gros organe interne ?", back: "Le foie (environ 1,5 kg)" },
      { front: "Combien de muscles dans le corps humain ?", back: "Environ 640 muscles" },
      { front: "Quel est le plus long os du corps humain ?", back: "Le fémur (os de la cuisse)" },
    ],
  },

  // ===== 3. RECORDS ET STATISTIQUES =====
  {
    id: "records-stats",
    name: "Records & Statistiques",
    icon: "📊",
    description: "Chiffres fous et records du monde",
    cards: [
      { front: "Quel est le pays le plus petit du monde ?", back: "Le Vatican (0,44 km²)" },
      { front: "Quel est le pays le plus grand du monde ?", back: "La Russie (17,1 millions de km²)" },
      { front: "Quel est le fleuve le plus long du monde ?", back: "Le Nil (~6 650 km, devant l'Amazone)" },
      { front: "Quel est le lac le plus profond du monde ?", back: "Le lac Baïkal en Russie (1 642 m)" },
      { front: "Quel est le point le plus bas sur Terre ?", back: "La mer Morte (-430 m sous le niveau de la mer)" },
      { front: "Quel est le désert le plus grand du monde ?", back: "L'Antarctique (désert froid), puis le Sahara (désert chaud)" },
      { front: "Quelle est la montagne la plus haute du monde ?", back: "L'Everest (8 849 m)" },
      { front: "Quelle est la ville la plus peuplée du monde ?", back: "Tokyo (agglomération ~37 millions d'habitants)" },
      { front: "Quel est le bâtiment le plus haut du monde ?", back: "Burj Khalifa à Dubaï (828 m)" },
      { front: "Quel est le pays avec le plus de langues officielles ?", back: "L'Afrique du Sud (11 langues officielles)" },
      { front: "Quelle est la langue la plus parlée au monde (natifs) ?", back: "Le mandarin (~920 millions de locuteurs natifs)" },
      { front: "Quel est le plus long mur du monde ?", back: "La Grande Muraille de Chine (~21 000 km au total)" },
      { front: "Quelle est la fosse océanique la plus profonde ?", back: "La fosse des Mariannes (environ 11 034 m)" },
      { front: "Quel pays possède le plus de fuseaux horaires ?", back: "La France (12 fuseaux, grâce aux DOM-TOM)" },
      { front: "Quelle est la cascade la plus haute du monde ?", back: "Le Salto Ángel au Venezuela (979 m)" },
      { front: "Quel est le plus petit pays d'Afrique ?", back: "Les Seychelles (455 km²)" },
      { front: "Quel est le pays le plus peuplé d'Afrique ?", back: "Le Nigeria (~220 millions d'habitants)" },
      { front: "Quelle est la plus longue frontière terrestre du monde ?", back: "Canada / États-Unis (8 891 km)" },
      { front: "Quel pays possède le plus d'îles au monde ?", back: "La Suède (environ 267 570 îles)" },
      { front: "Quel est le plus vieux pays du monde encore existant ?", back: "Saint-Marin (fondé en 301)" },
    ],
  },

  // ===== 4. SCIENCES ÉTONNANTES =====
  {
    id: "sciences-etonnantes",
    name: "Sciences étonnantes",
    icon: "🔬",
    description: "Physique, chimie, espace : l'inattendu",
    cards: [
      { front: "Quelle planète tourne à l'envers (rotation rétrograde) ?", back: "Vénus (le Soleil s'y lève à l'ouest)" },
      { front: "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", back: "Environ 8 minutes et 20 secondes" },
      { front: "Quel gaz compose majoritairement l'atmosphère terrestre ?", back: "L'azote (78 %), pas l'oxygène (21 %)" },
      { front: "Quelle est la température du noyau de la Terre ?", back: "Environ 5 500 °C (comparable à la surface du Soleil)" },
      { front: "De quoi est principalement composé le Soleil ?", back: "D'hydrogène (~73 %) et d'hélium (~25 %)" },
      { front: "Quel est l'élément chimique le plus abondant dans l'univers ?", back: "L'hydrogène" },
      { front: "Combien de planètes dans le système solaire ?", back: "8 (Pluton reclassée en planète naine en 2006)" },
      { front: "Quel métal est liquide à température ambiante ?", back: "Le mercure (Hg)" },
      { front: "Quel est l'élément le plus léger du tableau périodique ?", back: "L'hydrogène (H, numéro atomique 1)" },
      { front: "À quelle température l'eau bout-elle au sommet de l'Everest ?", back: "Environ 70 °C (pression plus basse)" },
      { front: "Quel scientifique a formulé E = mc² ?", back: "Albert Einstein (relativité restreinte, 1905)" },
      { front: "Quelle est la vitesse de la lumière ?", back: "Environ 300 000 km/s (299 792 km/s)" },
      { front: "Quel est le plus grand volcan du système solaire ?", back: "Olympus Mons sur Mars (~21 km de haut)" },
      { front: "Qui a découvert la pénicilline ?", back: "Alexander Fleming en 1928" },
      { front: "Quel est le numéro atomique de l'or ?", back: "79 (symbole Au, du latin aurum)" },
      { front: "De quoi sont principalement faits les diamants ?", back: "De carbone pur cristallisé" },
      { front: "Quel gaz donne sa couleur rouge aux enseignes lumineuses ?", back: "Le néon" },
      { front: "Quelle planète est la plus chaude du système solaire ?", back: "Vénus (~465 °C en surface, effet de serre)" },
      { front: "Quel est le plus petit os du corps humain et quel rôle joue-t-il ?", back: "L'étrier (3 mm), transmet les vibrations sonores dans l'oreille" },
      { front: "Combien pèse environ un litre d'eau ?", back: "1 kilogramme (à 4 °C)" },
    ],
  },

  // ===== 5. VRAIS NOMS DES CÉLÉBRITÉS =====
  {
    id: "vrais-noms",
    name: "Vrais noms des célébrités",
    icon: "🌟",
    description: "Les vrais noms de stars connues",
    cards: [
      { front: "Quel est le vrai nom de Voltaire ?", back: "François-Marie Arouet" },
      { front: "Quel est le vrai nom de Molière ?", back: "Jean-Baptiste Poquelin" },
      { front: "Quel est le vrai nom de Stendhal ?", back: "Henri Beyle" },
      { front: "Quel est le vrai nom de George Sand ?", back: "Amantine Aurore Lucile Dupin" },
      { front: "Quel est le vrai nom du Caravage ?", back: "Michelangelo Merisi" },
      { front: "Quel est le vrai nom de Johnny Hallyday ?", back: "Jean-Philippe Smet" },
      { front: "Quel est le vrai nom de Bourvil ?", back: "André Raimbourg" },
      { front: "Quel est le vrai nom de Fernandel ?", back: "Fernand Joseph Désiré Contandin" },
      { front: "Quel est le vrai nom de Coluche ?", back: "Michel Gérard Joseph Colucci" },
      { front: "Quel est le vrai nom de Le Corbusier ?", back: "Charles-Édouard Jeanneret" },
      { front: "Quel est le vrai nom de Romain Gary ?", back: "Roman Kacew (aussi connu sous le pseudo Émile Ajar)" },
      { front: "Quel est le vrai nom de MC Solaar ?", back: "Claude M'Barali" },
      { front: "Quel est le vrai nom de Daft Punk ?", back: "Thomas Bangalter et Guy-Manuel de Homem-Christo" },
      { front: "Quel est le vrai nom d'Édith Piaf ?", back: "Édith Giovanna Gassion" },
      { front: "Quel est le vrai nom de Dalida ?", back: "Iolanda Cristina Gigliotti" },
      { front: "Quel est le vrai prénom de Napoléon ?", back: "Napoleone di Buonaparte (corse puis francisé)" },
      { front: "Quel est le vrai nom de Marilyn Monroe ?", back: "Norma Jeane Mortenson (puis Baker)" },
      { front: "Quel est le vrai nom de Mark Twain ?", back: "Samuel Langhorne Clemens" },
      { front: "Quel est le vrai nom de Lino Ventura ?", back: "Angiolino Giuseppe Pasquale Ventura" },
      { front: "Quel est le vrai nom de Staline ?", back: "Iossif Vissarionovitch Djougachvili" },
      { front: "Quel est le vrai nom de Calamity Jane ?", back: "Martha Jane Cannary" },
      { front: "Quel est le vrai nom du Greco ?", back: "Domínikos Theotokópoulos" },
      { front: "Quel est le vrai nom de Pelé ?", back: "Edson Arantes do Nascimento" },
      { front: "Quel est le vrai nom de Tino Rossi ?", back: "Constantino Rossi" },
    ],
  },

  // ===== 6. GÉOGRAPHIE INSOLITE =====
  {
    id: "geo-insolite",
    name: "Géographie insolite",
    icon: "🗺️",
    description: "Capitales pièges, frontières bizarres, curiosités",
    cards: [
      { front: "Quelle est la capitale de l'Australie ?", back: "Canberra (pas Sydney)" },
      { front: "Quelle est la capitale du Brésil ?", back: "Brasília (pas Rio de Janeiro)" },
      { front: "Quelle est la capitale de la Turquie ?", back: "Ankara (pas Istanbul)" },
      { front: "Quelle est la capitale du Canada ?", back: "Ottawa (pas Toronto ni Montréal)" },
      { front: "Quelle est la capitale du Maroc ?", back: "Rabat (pas Casablanca)" },
      { front: "Quelle est la capitale de la Suisse ?", back: "Berne (pas Zurich ni Genève)" },
      { front: "Quelle est la capitale du Myanmar ?", back: "Naypyidaw (pas Rangoun)" },
      { front: "Quelle est la capitale de la Nouvelle-Zélande ?", back: "Wellington (pas Auckland)" },
      { front: "Quelle est la capitale du Nigeria ?", back: "Abuja (pas Lagos)" },
      { front: "Quelle est la capitale du Pakistan ?", back: "Islamabad (pas Karachi)" },
      { front: "Quel est le seul pays dont le drapeau n'est pas rectangulaire ?", back: "Le Népal (double pennon triangulaire)" },
      { front: "Quel pays d'Afrique est entièrement entouré par un seul autre pays ?", back: "Le Lesotho (enclavé dans l'Afrique du Sud)" },
      { front: "Quel pays est traversé par le plus de fuseaux horaires (continental) ?", back: "La Russie (11 fuseaux horaires)" },
      { front: "Quel fleuve traverse le plus de capitales européennes ?", back: "Le Danube (4 capitales : Vienne, Bratislava, Budapest, Belgrade)" },
      { front: "Quelle ville est sur deux continents ?", back: "Istanbul (Europe et Asie, séparée par le Bosphore)" },
      { front: "Quel pays a la densité la plus faible au monde ?", back: "La Mongolie (~2 hab./km²)" },
      { front: "Quelle est la capitale de la Birmanie ?", back: "Naypyidaw (depuis 2006)" },
      { front: "Quelle est la capitale du Sri Lanka ?", back: "Sri Jayawardenepura Kotte (pas Colombo)" },
      { front: "Quelle est la capitale de la Côte d'Ivoire ?", back: "Yamoussoukro (pas Abidjan)" },
      { front: "Quelle est la capitale de la Tanzanie ?", back: "Dodoma (pas Dar es Salaam)" },
      { front: "Quel est le plus petit pays d'Amérique du Sud ?", back: "Le Suriname (~164 000 km²)" },
      { front: "Combien de pays sont traversés par l'équateur ?", back: "13 pays" },
    ],
  },

  // ===== 7. CINÉMA & SÉRIES =====
  {
    id: "cinema-series",
    name: "Cinéma & Séries",
    icon: "🎬",
    description: "Anecdotes de tournage, Oscars et records",
    cards: [
      { front: "Quel film a remporté le plus d'Oscars ?", back: "Ben-Hur (1959), Titanic (1997) et Le Retour du Roi (2003) : 11 chacun" },
      { front: "Quel acteur a remporté deux Oscars consécutifs ?", back: "Tom Hanks (Philadelphia 1994, Forrest Gump 1995)" },
      { front: "Dans quel film entend-on « Je suis ton père » ?", back: "Star Wars : L'Empire contre-attaque (1980)" },
      { front: "Quel réalisateur est surnommé « le maître du suspense » ?", back: "Alfred Hitchcock" },
      { front: "Quel est le premier long-métrage d'animation de Disney ?", back: "Blanche-Neige et les Sept Nains (1937)" },
      { front: "Qui a réalisé Pulp Fiction ?", back: "Quentin Tarantino (1994)" },
      { front: "Quel film français détient le record d'entrées en France ?", back: "Bienvenue chez les Ch'tis (plus de 20 millions d'entrées)" },
      { front: "Qui a réalisé 2001, l'Odyssée de l'espace ?", back: "Stanley Kubrick (1968)" },
      { front: "Quel est le premier film parlant de l'histoire ?", back: "Le Chanteur de jazz (The Jazz Singer, 1927)" },
      { front: "Quel est le vrai nom de Charlie Chaplin ?", back: "Sir Charles Spencer Chaplin" },
      { front: "Quel est le premier film des frères Lumière ?", back: "La Sortie de l'usine Lumière à Lyon (1895)" },
      { front: "Qui joue le rôle-titre dans Amélie Poulain ?", back: "Audrey Tautou (réalisé par Jean-Pierre Jeunet, 2001)" },
      { front: "Quel est le plus gros succès du cinéma français à l'international ?", back: "Intouchables (2011, plus de 50 millions d'entrées dans le monde)" },
      { front: "Quel acteur incarne OSS 117 dans les films de Michel Hazanavicius ?", back: "Jean Dujardin" },
      { front: "Quel film de Jean Dujardin a remporté l'Oscar du meilleur film ?", back: "The Artist (2012, film muet en noir et blanc)" },
      { front: "Quel est le nom du personnage joué par Jean Reno dans Léon ?", back: "Léon (Le Professionnel, 1994, réalisé par Luc Besson)" },
      { front: "Quel dessin animé Pixar met en scène un rat cuisinier à Paris ?", back: "Ratatouille (2007)" },
      { front: "Quel James Bond a été incarné par le plus d'acteurs ?", back: "6 acteurs principaux : Connery, Lazenby, Moore, Dalton, Brosnan, Craig" },
      { front: "Quel est le film le plus cher jamais produit (ajusté inflation) ?", back: "Pirates des Caraïbes : Jusqu'au bout du monde (2007)" },
      { front: "Qui a créé la saga Star Wars ?", back: "George Lucas (premier film en 1977)" },
    ],
  },

  // ===== 8. RÉGIONS DE FRANCE =====
  {
    id: "regions-france",
    name: "Régions de France",
    icon: "🇫🇷",
    description: "Spécialités, capitales et curiosités régionales",
    cards: [
      { front: "Combien de régions métropolitaines en France ?", back: "13 régions (depuis la réforme de 2016)" },
      { front: "Quelle est la plus grande région de France métropolitaine ?", back: "Nouvelle-Aquitaine (~84 000 km²)" },
      { front: "Quelle est la région la plus peuplée de France ?", back: "Île-de-France (~12 millions d'habitants)" },
      { front: "Quel est le chef-lieu de la région Grand Est ?", back: "Strasbourg" },
      { front: "Quel est le chef-lieu de la région Occitanie ?", back: "Toulouse" },
      { front: "Quel est le chef-lieu de la région Hauts-de-France ?", back: "Lille" },
      { front: "Quel est le chef-lieu de la région Nouvelle-Aquitaine ?", back: "Bordeaux" },
      { front: "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?", back: "Lyon" },
      { front: "Quel est le chef-lieu de la région Bourgogne-Franche-Comté ?", back: "Dijon" },
      { front: "Quel est le chef-lieu de la région Centre-Val de Loire ?", back: "Orléans" },
      { front: "Quel est le chef-lieu de la région Normandie ?", back: "Rouen" },
      { front: "Quel est le chef-lieu de la région Bretagne ?", back: "Rennes" },
      { front: "Quel est le chef-lieu de la région Pays de la Loire ?", back: "Nantes" },
      { front: "Quel est le chef-lieu de la région PACA ?", back: "Marseille" },
      { front: "Quel est le chef-lieu de la Corse ?", back: "Ajaccio" },
      { front: "La Camargue se situe dans quel département ?", back: "Les Bouches-du-Rhône (13)" },
      { front: "Le Mont-Saint-Michel est dans quel département ?", back: "La Manche (50), en Normandie" },
      { front: "Les gorges du Verdon traversent quels départements ?", back: "Alpes-de-Haute-Provence et Var" },
      { front: "Le Futuroscope se trouve dans quel département ?", back: "La Vienne (86), à Poitiers" },
      { front: "La dune du Pilat se trouve dans quel département ?", back: "La Gironde (33), à La Teste-de-Buch" },
      { front: "Quelle région est associée au beurre salé ?", back: "La Bretagne" },
      { front: "Quelle région produit le calisson ?", back: "La Provence (Aix-en-Provence)" },
      { front: "Quelle ville est connue pour sa moutarde ?", back: "Dijon (Bourgogne)" },
      { front: "Le nougat de Montélimar vient de quelle région ?", back: "Auvergne-Rhône-Alpes (Drôme)" },
      { front: "Le béret basque est originaire de quel département ?", back: "Le Béarn (Pyrénées-Atlantiques, 64), pas le Pays basque !" },
      { front: "Les volcans d'Auvergne : quel est le plus haut ?", back: "Le puy de Sancy (1 885 m), dans le Massif central" },
      { front: "Quelle ville est surnommée la « Ville rose » ?", back: "Toulouse (briques roses)" },
      { front: "Quelle ville est surnommée la « Cité des Papes » ?", back: "Avignon (palais des Papes)" },
      { front: "Quelle ville française est inscrite au patrimoine mondial pour ses fortifications ?", back: "Carcassonne (Aude)" },
      { front: "Le pont du Gard est un aqueduc romain situé dans quel département ?", back: "Le Gard (30)" },
      { front: "Les alignements mégalithiques les plus célèbres de France ?", back: "Carnac (Morbihan, Bretagne)" },
      { front: "Quelle île française est surnommée l'île de Beauté ?", back: "La Corse" },
      { front: "La tapisserie de Bayeux raconte quel événement ?", back: "La conquête de l'Angleterre par Guillaume le Conquérant (1066)" },
    ],
  },

  // ===== 9. GASTRONOMIE FRANÇAISE =====
  {
    id: "gastronomie",
    name: "Gastronomie française",
    icon: "🧑‍🍳",
    description: "Fromages, plats, vins et traditions culinaires",
    cards: [
      { front: "Combien de fromages différents recense-t-on en France ?", back: "Plus de 1 200 variétés" },
      { front: "Quel fromage est surnommé « le roi des fromages » ?", back: "Le roquefort (ou parfois le brie)" },
      { front: "De quelle région vient le camembert ?", back: "Normandie (village de Camembert, Orne)" },
      { front: "Avec quel lait est fabriqué le roquefort ?", back: "Lait de brebis (affiné dans les caves de Roquefort-sur-Soulzon)" },
      { front: "Quel est le fromage le plus consommé en France ?", back: "L'emmental (pas le camembert !)" },
      { front: "Qu'est-ce qu'un fromage à pâte persillée ?", back: "Un fromage à moisissures (bleu) : roquefort, bleu d'Auvergne, fourme d'Ambert" },
      { front: "La bouillabaisse est une spécialité de quelle ville ?", back: "Marseille" },
      { front: "Le cassoulet est un plat de quelle région ?", back: "Occitanie (Castelnaudary, Toulouse, Carcassonne)" },
      { front: "La choucroute est une spécialité de quelle région ?", back: "L'Alsace" },
      { front: "Le gratin dauphinois vient de quelle région ?", back: "Le Dauphiné (Isère, actuelle Auvergne-Rhône-Alpes)" },
      { front: "La quiche lorraine vient de quelle région ?", back: "La Lorraine (Grand Est)" },
      { front: "Quel est l'ingrédient principal de l'aligot ?", back: "La tome fraîche de Laguiole (et purée de pommes de terre)" },
      { front: "Le kouign-amann est une pâtisserie de quelle région ?", back: "Bretagne (Douarnenez)" },
      { front: "La tarte Tatin a été inventée par accident dans quel département ?", back: "Le Loir-et-Cher (Lamotte-Beuvron)" },
      { front: "Le canelé est une spécialité de quelle ville ?", back: "Bordeaux" },
      { front: "La pissaladière est une spécialité de quelle région ?", back: "Nice (Côte d'Azur)" },
      { front: "Le baba au rhum a été popularisé en France par quel pâtissier ?", back: "Nicolas Stohrer (1730), plus vieille pâtisserie de Paris" },
      { front: "Combien d'étoiles au maximum peut décerner le Guide Michelin ?", back: "3 étoiles (1 = très bonne table, 2 = excellente, 3 = exceptionnelle)" },
      { front: "Qui est considéré comme le « père de la gastronomie française » ?", back: "Auguste Escoffier (ou Antonin Carême, selon les sources)" },
      { front: "Qu'est-ce qu'une AOC / AOP ?", back: "Appellation d'Origine Contrôlée / Protégée : garantit l'origine géographique" },
      { front: "Le champagne ne peut être produit que dans quelle région ?", back: "La Champagne (AOC stricte)" },
      { front: "Le croissant est-il une invention française ?", back: "Non ! Il vient du kipferl autrichien (Vienne), popularisé en France au XIXe" },
      { front: "Le bœuf bourguignon tire son nom de quel ingrédient clé ?", back: "Le vin de Bourgogne (vin rouge)" },
      { front: "Quel condiment est fabriqué à Espelette au Pays basque ?", back: "Le piment d'Espelette (AOP)" },
      { front: "Le pain d'épices est une spécialité de quelle ville ?", back: "Dijon (tradition depuis le Moyen Âge)" },
      { front: "Qu'est-ce que le « repas gastronomique des Français » ?", back: "Inscrit au patrimoine immatériel de l'UNESCO depuis 2010" },
      { front: "Quel légume est à la base de la ratatouille ?", back: "Aubergine, courgette, poivron, tomate, oignon (plat provençal)" },
      { front: "Quel est le plat national non officiel de la France ?", back: "Le pot-au-feu" },
      { front: "La socca est une spécialité de quelle ville ?", back: "Nice (galette de farine de pois chiche)" },
      { front: "Quel fruit est associé à la ville de Montmorency ?", back: "La cerise (griotte de Montmorency)" },
      { front: "Les macarons de quel pâtissier parisien sont mondialement connus ?", back: "Pierre Hermé (et Ladurée)" },
    ],
  },

  // ===== 10. LANGUE FRANÇAISE =====
  {
    id: "langue-francaise",
    name: "Langue française",
    icon: "📖",
    description: "Étymologies, mots rares et pièges",
    cards: [
      { front: "Quel est le mot le plus long de la langue française ?", back: "Anticonstitutionnellement (25 lettres)" },
      { front: "Comment appelle-t-on la peur des araignées ?", back: "L'arachnophobie" },
      { front: "Comment appelle-t-on la peur des espaces clos ?", back: "La claustrophobie" },
      { front: "Comment appelle-t-on la peur du vide / hauteurs ?", back: "L'acrophobie (≠ vertige)" },
      { front: "Comment appelle-t-on un mot qui se lit pareil dans les deux sens ?", back: "Un palindrome (ex : kayak, radar, ressasser)" },
      { front: "Que signifie le mot « procrastiner » ?", back: "Reporter à plus tard ce qu'on pourrait faire maintenant" },
      { front: "Que signifie l'expression « avoir maille à partir » ?", back: "Avoir un différend (la maille était une petite pièce de monnaie)" },
      { front: "D'où vient le mot « salaire » ?", back: "Du latin salarium : ration de sel des soldats romains" },
      { front: "D'où vient le mot « quarantaine » ?", back: "De quaranta giorni (40 jours d'isolement imposés aux navires à Venise)" },
      { front: "Qu'est-ce qu'un hapax ?", back: "Un mot qui n'apparaît qu'une seule fois dans un corpus" },
      { front: "Comment appelle-t-on un mot formé des initiales d'autres mots ?", back: "Un acronyme (ex : SIDA, ONU, laser)" },
      { front: "Qu'est-ce qu'un pléonasme ?", back: "Répétition inutile (ex : « monter en haut », « descendre en bas »)" },
      { front: "Que signifie « sérendipité » ?", back: "Faire une découverte heureuse par hasard" },
      { front: "Quelle lettre est la plus utilisée en français ?", back: "Le E" },
      { front: "Comment s'appelle un roman écrit sans la lettre E ?", back: "Un lipogramme (ex : La Disparition de Georges Perec, 1969)" },
      { front: "Quel est le pluriel de « œil » ?", back: "Yeux (sauf œils-de-bœuf, œils-de-perdrix)" },
      { front: "Quels mots français viennent de l'arabe ?", back: "Algorithme, algèbre, chiffre, zéro, magasin, café, alcool..." },
      { front: "D'où vient le mot « assassin » ?", back: "De l'arabe hashshashin (consommateurs de haschisch)" },
      { front: "Quel mot désigne la peur de la peur ?", back: "La phobophobie" },
      { front: "Comment appelle-t-on quelqu'un qui parle plusieurs langues ?", back: "Un polyglotte" },
    ],
  },

  // ===== 11. INVENTIONS & DÉCOUVERTES =====
  {
    id: "inventions",
    name: "Inventions & Découvertes",
    icon: "💡",
    description: "Qui a inventé quoi ? Les réponses qui surprennent",
    cards: [
      { front: "Qui a inventé l'imprimerie en Europe ?", back: "Johannes Gutenberg (vers 1450, à Mayence)" },
      { front: "Qui a inventé le vaccin contre la rage ?", back: "Louis Pasteur (1885)" },
      { front: "Qui a inventé la dynamite ?", back: "Alfred Nobel (1867) — d'où le prix Nobel" },
      { front: "Qui a inventé la conserve alimentaire ?", back: "Nicolas Appert (1795, méthode d'appertisation)" },
      { front: "Qui a inventé le cinématographe ?", back: "Les frères Lumière (1895, Lyon)" },
      { front: "Qui a inventé le stéthoscope ?", back: "René Laennec (1816, à l'hôpital Necker)" },
      { front: "Qui a inventé la machine à calculer ?", back: "Blaise Pascal (1642, la Pascaline)" },
      { front: "Qui a inventé le paratonnerre ?", back: "Benjamin Franklin (1752)" },
      { front: "Qui a inventé la photographie ?", back: "Nicéphore Niépce (1826-1827, première photo connue)" },
      { front: "Qui a inventé le braille ?", back: "Louis Braille (1825, lui-même aveugle)" },
      { front: "Qui a inventé le stylo à bille ?", back: "László Bíró (1938, Hongrois)" },
      { front: "Qui a découvert la radioactivité ?", back: "Henri Becquerel (1896), puis les Curie" },
      { front: "Qui a inventé la guillotine ?", back: "Le Dr Guillotin l'a proposée, mais c'est Antoine Louis qui l'a conçue" },
      { front: "Qui a inventé la carte à puce ?", back: "Roland Moreno (1974, Français)" },
      { front: "Qui a inventé le Minitel ?", back: "France Télécom / PTT (lancé en 1982, invention française)" },
      { front: "Qui a inventé la montgolfière ?", back: "Les frères Montgolfier (1783, Annonay)" },
      { front: "Qui a inventé la boîte de conserve ?", back: "Peter Durand (1810), mais le procédé est de Nicolas Appert" },
      { front: "Qui a inventé le vaccin contre la variole ?", back: "Edward Jenner (1796)" },
      { front: "Qui a inventé le téléphone ?", back: "Alexander Graham Bell (brevet en 1876)" },
      { front: "Qui a inventé l'aspirine ?", back: "Felix Hoffmann chez Bayer (1897)" },
      { front: "Qui a inventé le système métrique ?", back: "La France révolutionnaire (1795)" },
    ],
  },

  // ===== 12. MUSIQUE =====
  {
    id: "musique-pop",
    name: "Musique",
    icon: "🎸",
    description: "Groupes, albums cultes et anecdotes musicales",
    cards: [
      { front: "Quel est l'album le plus vendu de tous les temps ?", back: "Thriller de Michael Jackson (1982, ~70 millions)" },
      { front: "Quel groupe a vendu le plus d'albums au monde ?", back: "Les Beatles" },
      { front: "Comment s'appelle le chanteur des Rolling Stones ?", back: "Mick Jagger" },
      { front: "Quel chanteur est surnommé « The King » ?", back: "Elvis Presley" },
      { front: "Quel groupe a chanté « Bohemian Rhapsody » ?", back: "Queen (1975, album A Night at the Opera)" },
      { front: "Quel groupe de rock a pour chanteur Bono ?", back: "U2" },
      { front: "Quel est le festival de musique le plus célèbre (1969) ?", back: "Woodstock (État de New York)" },
      { front: "Comment s'appelle le batteur des Beatles ?", back: "Ringo Starr (vrai nom Richard Starkey)" },
      { front: "Quel artiste a chanté « La Bohème » ?", back: "Charles Aznavour" },
      { front: "Quel artiste a chanté « Ne me quitte pas » ?", back: "Jacques Brel (1959)" },
      { front: "Quel musicien est devenu sourd et a continué à composer ?", back: "Ludwig van Beethoven" },
      { front: "Quel opéra de Mozart raconte l'histoire de Don Juan ?", back: "Don Giovanni (1787)" },
      { front: "De quel instrument jouait Django Reinhardt ?", back: "La guitare (jazz manouche, avec 2 doigts paralysés)" },
      { front: "Quel compositeur a écrit « Le Boléro » ?", back: "Maurice Ravel (1928)" },
      { front: "Quel compositeur a écrit « Les Quatre Saisons » ?", back: "Antonio Vivaldi (vers 1723)" },
      { front: "Qui a composé « La Flûte enchantée » ?", back: "Wolfgang Amadeus Mozart (1791)" },
      { front: "Quel rappeur français est le plus gros vendeur de disques ?", back: "MC Solaar (plus de 10 millions d'albums)" },
      { front: "Comment s'appelle le festival de musique classique de Salzbourg ?", back: "Le Festival de Salzbourg (fondé en 1920)" },
      { front: "Quel instrument donne le « la » à l'orchestre ?", back: "Le hautbois" },
      { front: "Combien de cordes a un violon ?", back: "4 cordes (sol, ré, la, mi)" },
    ],
  },

  // ===== 13. ÉTYMOLOGIE DES MOTS =====
  {
    id: "etymologie",
    name: "Étymologie des mots",
    icon: "🔤",
    description: "D'où viennent les mots qu'on utilise tous les jours ?",
    cards: [
      { front: "D'où vient le mot « salaire » ?", back: "Du latin salarium (sel) — les soldats romains étaient payés en sel" },
      { front: "D'où vient le mot « candidat » ?", back: "Du latin candidus (blanc) — les candidats romains portaient une toge blanche" },
      { front: "D'où vient le mot « hystérie » ?", back: "Du grec hystera (utérus) — on croyait que c'était une maladie utérine" },
      { front: "D'où vient le mot « quarantaine » ?", back: "De quaranta giorni (40 jours) — durée d'isolement des navires à Venise" },
      { front: "D'où vient le mot « assassin » ?", back: "De l'arabe hashshashin — secte du XIe siècle au Moyen-Orient" },
      { front: "D'où vient le mot « robot » ?", back: "Du tchèque robota (travail forcé) — inventé par Karel Čapek en 1920" },
      { front: "D'où vient le mot « caprice » ?", back: "De l'italien capriccio (frisson de la tête) — lié à capra (chèvre)" },
      { front: "D'où vient le mot « cravate » ?", back: "De « croate » — les cavaliers croates portaient un foulard au cou (XVIIe)" },
      { front: "D'où vient le mot « alcool » ?", back: "De l'arabe al-kuḥl (poudre d'antimoine) — sens élargi à la distillation" },
      { front: "D'où vient le mot « bonbon » ?", back: "Redoublement enfantin de « bon » — apparu au XVIIe siècle" },
      { front: "D'où vient le mot « fiasco » ?", back: "De l'italien fiasco (bouteille) — un acteur raté « faisait une bouteille »" },
      { front: "D'où vient le mot « baguette » ?", back: "De l'italien bacchetta (petit bâton) — issu du latin baculum" },
      { front: "D'où vient le mot « muscle » ?", back: "Du latin musculus (petite souris) — la contraction du muscle ressemble à une souris" },
      { front: "D'où vient le mot « désastre » ?", back: "De l'italien disastro (mauvaise étoile) — astro = astre" },
      { front: "D'où vient le mot « bikini » ?", back: "De l'atoll Bikini (essais nucléaires) — l'effet du maillot serait « explosif »" },
      { front: "D'où vient le mot « pistol » / « pistolet » ?", back: "De la ville de Pistoia en Italie, connue pour ses armuriers" },
      { front: "D'où vient le mot « jeans » ?", back: "De Gênes (Genova) — « Genes » en anglais, tissu venu de cette ville" },
      { front: "D'où vient le mot « denim » ?", back: "De « de Nîmes » — la toile venait de Nîmes" },
      { front: "D'où vient le mot « gazette » ?", back: "De l'italien gazzetta — petite pièce de monnaie vénitienne (prix du journal)" },
      { front: "D'où vient le mot « compagnon » ?", back: "Du latin cum + panis (avec + pain) — celui avec qui on partage le pain" },
      { front: "D'où vient le mot « métro » ?", back: "Abréviation de « chemin de fer métropolitain »" },
      { front: "D'où vient le mot « catastrophe » ?", back: "Du grec katastrophê (renversement) — kata (en bas) + strephein (tourner)" },
      { front: "D'où vient le mot « chapeau » ?", back: "Du latin cappa (manteau) — même racine que « cape » et « chapelle »" },
      { front: "D'où vient le mot « silhouette » ?", back: "D'Étienne de Silhouette, contrôleur des finances (1759), connu pour son austérité" },
      { front: "D'où vient le mot « bistrot » ?", back: "Origine disputée — peut-être du russe bystro (vite) ou du français bistrouille" },
      { front: "D'où vient le mot « chiffre » ?", back: "De l'arabe sifr (vide, zéro) — même origine que « zéro »" },
      { front: "D'où vient le mot « magasin » ?", back: "De l'arabe makhzan (entrepôt) — même racine que « magazine »" },
      { front: "D'où vient le mot « abricot » ?", back: "De l'arabe al-barquq, lui-même du latin praecoquum (fruit précoce)" },
      { front: "D'où vient le mot « pantalon » ?", back: "Du personnage Pantalone de la commedia dell'arte italienne" },
      { front: "D'où vient le mot « palace » ?", back: "Du mont Palatin à Rome, où Auguste avait son palatium (palais)" },
    ],
  },

  // ===== 14. POP CULTURE FRANÇAISE =====
  {
    id: "pop-culture-fr",
    name: "Pop Culture française",
    icon: "📺",
    description: "Émissions cultes, chansons, séries et personnages FR",
    cards: [
      { front: "Qui présentait « Les Enfants de la Télé » à l'origine ?", back: "Arthur (Jacques Essebag)" },
      { front: "Quel animateur présente « Les 12 Coups de Midi » ?", back: "Jean-Luc Reichmann" },
      { front: "Quel animateur présentait « Questions pour un Champion » avant Samuel Étienne ?", back: "Julien Lepers (1988-2015)" },
      { front: "Qui est le créateur des « Guignols de l'Info » ?", back: "Alain de Greef (producteur Canal+)" },
      { front: "Dans quelle émission entend-on « C'est mon dernier mot, Jean-Pierre » ?", back: "Qui veut gagner des millions ? (présenté par Jean-Pierre Foucault)" },
      { front: "Quelle émission a révélé Mimie Mathy, Muriel Robin et Pierre Palmade ?", back: "Le Petit Théâtre de Bouvard" },
      { front: "Qui présente « Fort Boyard » depuis le début ?", back: "Patrice Laffont (1990-1999), puis Olivier Minne" },
      { front: "Quel personnage de Fort Boyard garde les clés ?", back: "Le Père Fouras (avec ses énigmes)" },
      { front: "Quelle chanson française est la plus connue à l'étranger ?", back: "« La Vie en rose » d'Édith Piaf" },
      { front: "Qui chante « Pour que tu m'aimes encore » ?", back: "Céline Dion (1995, écrite par Jean-Jacques Goldman)" },
      { front: "Qui a écrit la plupart des tubes de Céline Dion en français ?", back: "Jean-Jacques Goldman" },
      { front: "Quelle série française se passe au Moyen Âge avec une Table Ronde ?", back: "Kaamelott (Alexandre Astier)" },
      { front: "Qui a créé et joue dans Kaamelott ?", back: "Alexandre Astier (il joue le roi Arthur)" },
      { front: "Comment s'appelle la série culte du « Splendid » ?", back: "Le Père Noël est une ordure (film) et Scènes de ménages est une série du Splendid? Non, la série culte est Les Bronzés / Le Père Noël est une ordure" },
      { front: "Qui sont les membres de la troupe du Splendid ?", back: "Jugnot, Lhermitte, Clavier, Balasko, Chazel, Moynot, Blanc" },
      { front: "Quel rappeur est à l'origine du collectif Sexion d'Assaut ?", back: "Gims (Maître Gims / Gandhi Djuna)" },
      { front: "Qui a chanté « Dès que le vent soufflera » ?", back: "Renaud (1983)" },
      { front: "Qui a chanté « Les Lacs du Connemara » ?", back: "Michel Sardou (1981)" },
      { front: "Qui a écrit et chanté « Le Métèque » ?", back: "Georges Moustaki (1969)" },
      { front: "Qui chante « Mistral gagnant » ?", back: "Renaud (1985)" },
      { front: "Quel dessin animé français met en scène un village gaulois ?", back: "Astérix (créé par Goscinny et Uderzo, 1959)" },
      { front: "Comment s'appelle le village des Schtroumpfs ?", back: "Le village des Schtroumpfs (créés par Peyo, belge)" },
      { front: "Quelle BD franco-belge se passe dans l'espace avec Valérian ?", back: "Valérian et Laureline (Christin & Mézières, 1967)" },
      { front: "Qui présente « Tout le monde veut prendre sa place » ?", back: "Nagui" },
      { front: "Qui a présenté « Nulle Part Ailleurs » sur Canal+ ?", back: "Antoine de Caunes et José Garcia (entre autres)" },
      { front: "Quel groupe a chanté « L'Aziza » ?", back: "Daniel Balavoine (1985)" },
      { front: "Qui chante « Je l'aime à mourir » ?", back: "Francis Cabrel (1979)" },
      { front: "Qui a chanté « Alexandrie Alexandra » ?", back: "Claude François (1977)" },
      { front: "Quel chanteur français est surnommé « Cloclo » ?", back: "Claude François" },
      { front: "Qui chante « Il est 5 heures, Paris s'éveille » ?", back: "Jacques Dutronc (1968)" },
    ],
  },

  // ===== 15. ACTU & SOCIÉTÉ =====
  {
    id: "actu-societe",
    name: "Actu & Société",
    icon: "📰",
    description: "Fun facts de société, records récents, infos insolites",
    cards: [
      { front: "Quelle est la marque de voiture la plus vendue au monde ?", back: "Toyota" },
      { front: "Quel est le site web le plus visité au monde ?", back: "Google" },
      { front: "Quel réseau social a dépassé 2 milliards d'utilisateurs ?", back: "Facebook (Meta), puis YouTube et WhatsApp" },
      { front: "Quel pays a le plus de prix Nobel ?", back: "Les États-Unis (plus de 400)" },
      { front: "Quel sport est le plus regardé au monde ?", back: "Le football (soccer)" },
      { front: "Quel est le livre le plus vendu au monde après la Bible ?", back: "Don Quichotte de Cervantès (~500 millions)" },
      { front: "Quel est le fruit le plus consommé au monde ?", back: "La banane" },
      { front: "Combien de pays sont membres de l'ONU ?", back: "193 pays membres" },
      { front: "Combien de pays dans l'Union européenne ?", back: "27 pays (depuis le Brexit en 2020)" },
      { front: "Quel pays produit le plus de café au monde ?", back: "Le Brésil" },
      { front: "Quel pays produit le plus de vin au monde ?", back: "L'Italie (devant la France et l'Espagne)" },
      { front: "Quel est le sport le plus pratiqué en France ?", back: "Le football (2+ millions de licenciés)" },
      { front: "Combien de communes en France ?", back: "Environ 35 000 (le pays avec le plus de communes en Europe)" },
      { front: "Quel est le monument le plus visité de France ?", back: "La cathédrale Notre-Dame de Paris (avant l'incendie : ~13M visiteurs/an)" },
      { front: "Quel est le musée le plus visité au monde ?", back: "Le Louvre (~10 millions de visiteurs/an)" },
      { front: "Quel est le prénom masculin le plus donné en France en 2024 ?", back: "Gabriel" },
      { front: "Quelle est l'espérance de vie moyenne en France ?", back: "~85 ans (femmes), ~79 ans (hommes)" },
      { front: "Quel est le plus long pont de France ?", back: "Le viaduc de Millau (2 460 m, Aveyron)" },
      { front: "Quelle est la plus haute structure de France ?", back: "La Tour Eiffel (330 m avec antenne)" },
      { front: "Quel animal est le plus mortel pour l'homme dans le monde ?", back: "Le moustique (maladies transmises : ~700 000 morts/an)" },
      { front: "Quel pays est le plus grand producteur de fromage au monde ?", back: "Les États-Unis (en volume), mais la France a le plus de variétés" },
      { front: "Combien de langues sont parlées dans le monde ?", back: "Environ 7 000 langues" },
      { front: "Quel est le plus vieux journal encore en activité en France ?", back: "La Gazette (devenue Le Moniteur) — le plus ancien journal français encore actif est Le Figaro (1826)" },
      { front: "Quel pourcentage de la surface terrestre est couvert d'eau ?", back: "Environ 71 %" },
      { front: "Quelle est la monnaie la plus échangée au monde ?", back: "Le dollar américain (USD)" },
    ],
  },
];
