// Listes de référence QPUC - Pour mémorisation
const LISTS_DATA = [
  {
    id: "chefs-lieux-pieges",
    name: "Chefs-lieux pièges",
    icon: "🏛️",
    category: "Géographie",
    description: "Les préfectures qu'on confond ou qu'on oublie",
    type: "table",
    columns: ["Département", "Chef-lieu", "Piège courant"],
    rows: [
      ["Ain (01)", "Bourg-en-Bresse", "Pas Belley"],
      ["Aisne (02)", "Laon", "Pas Saint-Quentin ni Soissons"],
      ["Ardennes (08)", "Charleville-Mézières", "Pas Sedan"],
      ["Aube (10)", "Troyes", "Pas Bar-sur-Aube"],
      ["Calvados (14)", "Caen", "—"],
      ["Cantal (15)", "Aurillac", "Pas Saint-Flour"],
      ["Corrèze (19)", "Tulle", "Pas Brive-la-Gaillarde"],
      ["Creuse (23)", "Guéret", "Pas Aubusson"],
      ["Eure (27)", "Évreux", "Pas Bernay"],
      ["Gers (32)", "Auch", "Pas Condom"],
      ["Haute-Loire (43)", "Le Puy-en-Velay", "—"],
      ["Lozère (48)", "Mende", "Pas Florac"],
      ["Manche (50)", "Saint-Lô", "Pas Cherbourg"],
      ["Marne (51)", "Châlons-en-Champagne", "Pas Reims ni Épernay"],
      ["Haute-Marne (52)", "Chaumont", "Pas Langres"],
      ["Meuse (55)", "Bar-le-Duc", "Pas Verdun"],
      ["Oise (60)", "Beauvais", "Pas Compiègne ni Senlis"],
      ["Orne (61)", "Alençon", "Pas Argentan"],
      ["Haute-Saône (70)", "Vesoul", "Pas Gray ni Luxeuil"],
      ["Somme (80)", "Amiens", "Pas Abbeville"],
      ["Tarn-et-Garonne (82)", "Montauban", "Pas Moissac"],
      ["Var (83)", "Toulon", "Pas Draguignan (ancien chef-lieu)"],
      ["Yonne (89)", "Auxerre", "Pas Sens ni Joigny"],
      ["Territoire de Belfort (90)", "Belfort", "—"],
      ["Corse-du-Sud (2A)", "Ajaccio", "—"],
      ["Haute-Corse (2B)", "Bastia", "—"],
    ],
  },
  {
    id: "suffixes-medicaux",
    name: "Suffixes médicaux",
    icon: "🩺",
    category: "Médecine",
    description: "Comprendre le vocabulaire médical par ses racines",
    type: "grouped",
    groups: [
      {
        title: "Inflammations (-ite)",
        items: [
          { name: "Gastrite", detail: "estomac (gastêr)" },
          { name: "Hépatite", detail: "foie (hêpar)" },
          { name: "Néphrite", detail: "rein (nephros)" },
          { name: "Arthrite", detail: "articulation (arthron)" },
          { name: "Péricardite", detail: "péricarde (enveloppe du cœur)" },
          { name: "Myocardite", detail: "muscle cardiaque (myo + kardia)" },
          { name: "Cholécystite", detail: "vésicule biliaire (cholê + kystis)" },
          { name: "Méningite", detail: "méninges (mêninx)" },
          { name: "Pancréatite", detail: "pancréas" },
          { name: "Cystite", detail: "vessie (kystis)" },
          { name: "Colite", detail: "côlon (kolon)" },
          { name: "Gingivite", detail: "gencives (gingiva)" },
          { name: "Conjonctivite", detail: "conjonctive de l'œil" },
          { name: "Laryngite", detail: "larynx" },
          { name: "Pharyngite", detail: "pharynx" },
          { name: "Bronchite", detail: "bronches" },
          { name: "Dermatite", detail: "peau (derma)" },
          { name: "Otite", detail: "oreille (ous, otos)" },
          { name: "Pleurésie", detail: "plèvre" },
          { name: "Appendicite", detail: "appendice" },
        ],
      },
      {
        title: "Ablations (-ectomie)",
        items: [
          { name: "Appendicectomie", detail: "ablation de l'appendice" },
          { name: "Splénectomie", detail: "ablation de la rate (splên)" },
          { name: "Hystérectomie", detail: "ablation de l'utérus (hystera)" },
          { name: "Gastrectomie", detail: "ablation de l'estomac" },
          { name: "Cholécystectomie", detail: "ablation de la vésicule biliaire" },
          { name: "Néphrectomie", detail: "ablation du rein" },
          { name: "Thyroïdectomie", detail: "ablation de la thyroïde" },
          { name: "Mastectomie", detail: "ablation du sein (mastos)" },
          { name: "Tonsillectomie", detail: "ablation des amygdales" },
        ],
      },
      {
        title: "Examens (-scopie, -graphie, -gramme)",
        items: [
          { name: "Gastroscopie", detail: "examen visuel de l'estomac" },
          { name: "Coloscopie", detail: "examen visuel du côlon" },
          { name: "Endoscopie", detail: "examen visuel interne (endon)" },
          { name: "Électrocardiogramme", detail: "activité électrique du cœur" },
          { name: "Électroencéphalogramme", detail: "activité électrique du cerveau" },
          { name: "Électromyogramme", detail: "activité des muscles" },
          { name: "Radiographie", detail: "image par rayons X" },
          { name: "Échographie", detail: "image par ultrasons" },
        ],
      },
      {
        title: "Troubles (-orrhée, -algie, -pathie)",
        items: [
          { name: "Dysménorrhée", detail: "douleur pendant les règles" },
          { name: "Aménorrhée", detail: "absence de règles" },
          { name: "Névralgie", detail: "douleur d'un nerf" },
          { name: "Lombalgie", detail: "douleur lombaire" },
          { name: "Céphalée", detail: "mal de tête (kephalê)" },
          { name: "Neuropathie", detail: "maladie des nerfs" },
          { name: "Dyspnée", detail: "difficulté à respirer" },
          { name: "Bradycardie", detail: "rythme cardiaque trop lent" },
          { name: "Tachycardie", detail: "rythme cardiaque trop rapide" },
          { name: "Anémie", detail: "manque de globules rouges (a + haima)" },
        ],
      },
    ],
  },
  {
    id: "figures-style-liste",
    name: "Figures de style",
    icon: "✒️",
    category: "Littérature",
    description: "Toutes les figures avec exemples mémorables",
    type: "grouped",
    groups: [
      {
        title: "Figures d'analogie",
        items: [
          { name: "Comparaison", detail: "Rapprochement avec outil (comme, tel). « Fort comme un lion »" },
          { name: "Métaphore", detail: "Rapprochement SANS outil. « Cette faucille d'or dans le champ des étoiles » (Hugo)" },
          { name: "Personnification", detail: "Qualités humaines à un objet. « Le vent gémit »" },
          { name: "Allégorie", detail: "Métaphore filée représentant une idée abstraite. La Justice = femme aux yeux bandés" },
        ],
      },
      {
        title: "Figures d'atténuation / exagération",
        items: [
          { name: "Litote", detail: "Dire moins pour dire plus. « Va, je ne te hais point » = je t'aime (Chimène)" },
          { name: "Euphémisme", detail: "Atténuer le désagréable. « Il nous a quittés » = il est mort" },
          { name: "Hyperbole", detail: "Exagération. « Je meurs de faim », « un bruit à réveiller les morts »" },
        ],
      },
      {
        title: "Figures de substitution",
        items: [
          { name: "Métonymie", detail: "Lien logique. « Boire un verre » (contenant/contenu), « lire un Zola » (auteur/œuvre)" },
          { name: "Synecdoque", detail: "Partie pour le tout. « Les voiles » = les bateaux. « La France a gagné » = l'équipe" },
          { name: "Périphrase", detail: "Remplacer un mot par une expression. « La Ville lumière » = Paris" },
          { name: "Antonomase", detail: "Nom propre → nom commun. « Un harpagon » = un avare" },
          { name: "Antiphrase", detail: "Dire le contraire (ironie). « Quel beau temps ! » quand il pleut" },
        ],
      },
      {
        title: "Figures de construction",
        items: [
          { name: "Anaphore", detail: "Répétition en début. « Moi président... Moi président... »" },
          { name: "Épiphore", detail: "Répétition en fin de phrase" },
          { name: "Parallélisme", detail: "Construction identique. « Ni vu ni connu »" },
          { name: "Chiasme", detail: "Structure croisée ABBA. « Il faut manger pour vivre et non vivre pour manger »" },
          { name: "Gradation", detail: "Progression. « Va, cours, vole et nous venge ! »" },
          { name: "Asyndète", detail: "Suppression des liens. « Je suis venu, j'ai vu, j'ai vaincu »" },
          { name: "Anacoluthe", detail: "Rupture de construction. « Moi, la grammaire, ça me fatigue »" },
          { name: "Hyperbate", detail: "Inversion de l'ordre. « Du sénat romain la puissance »" },
          { name: "Prétérition", detail: "Feindre de taire. « Je ne dirai pas que... »" },
        ],
      },
      {
        title: "Figures de sonorité",
        items: [
          { name: "Allitération", detail: "Répétition de consonnes. « Pour qui sont ces serpents qui sifflent sur vos têtes »" },
          { name: "Assonance", detail: "Répétition de voyelles. « Les sanglots longs des violons »" },
          { name: "Onomatopée", detail: "Son = sens. « Coucou, crac, murmure, bourdonnement »" },
          { name: "Paronomase", detail: "Mots proches par le son. « Qui se ressemble s'assemble »" },
        ],
      },
      {
        title: "Figures d'opposition",
        items: [
          { name: "Antithèse", detail: "Opposition d'idées. « Tel qui rit vendredi, dimanche pleurera »" },
          { name: "Oxymore", detail: "Termes contradictoires accolés. « Cette obscure clarté » (Corneille)" },
          { name: "Paradoxe", detail: "Idée contraire à l'opinion. « Il faut risquer la paix » (Giraudoux)" },
        ],
      },
    ],
  },
  {
    id: "racines-grecques",
    name: "Racines grecques et latines",
    icon: "🏛️",
    category: "Vocabulaire",
    description: "Les racines qui reviennent le plus souvent à QPUC",
    type: "grouped",
    groups: [
      {
        title: "Le corps humain (grec)",
        items: [
          { name: "céphal(o)-", detail: "tête → céphalée, encéphale" },
          { name: "ophthalm(o)-", detail: "œil → ophtalmologie" },
          { name: "ot(o)-", detail: "oreille → otite, otorhinolaryngologie" },
          { name: "rhin(o)-", detail: "nez → rhinite, rhinocéros" },
          { name: "stomat(o)-", detail: "bouche → stomatologie" },
          { name: "odont(o)-", detail: "dent → orthodontie" },
          { name: "gastr(o)-", detail: "estomac → gastrite, gastronomie" },
          { name: "hépa(to)-", detail: "foie → hépatite" },
          { name: "néphro-", detail: "rein → néphrite, néphrologie" },
          { name: "cardi(o)-", detail: "cœur → cardiologie, bradycardie" },
          { name: "pneum(o)-", detail: "poumon → pneumonie" },
          { name: "derm(ato)-", detail: "peau → dermatite, dermatologie" },
          { name: "ostéo-", detail: "os → ostéoporose" },
          { name: "arthro-", detail: "articulation → arthrite" },
          { name: "myco-", detail: "champignon → mycose" },
          { name: "hém(ato)-", detail: "sang → hématome, anémie" },
        ],
      },
      {
        title: "Sciences et nature (grec)",
        items: [
          { name: "phyt(o)-", detail: "plante → épiphyte, xérophyte" },
          { name: "xyl(o)-", detail: "bois → xylème, xylophone" },
          { name: "anémo-", detail: "vent → anémochorie, anémomètre" },
          { name: "hydro-", detail: "eau → hydrochorie, hydrophyte" },
          { name: "litho-", detail: "pierre → lithographie, néolithique" },
          { name: "pyro-", detail: "feu → pyrotechnie, pyromane" },
          { name: "crypto-", detail: "caché → cryptogame, cryptographie" },
          { name: "phanéro-", detail: "visible → phanérogame" },
          { name: "zoo-", detail: "animal → zoochorie, zoologie" },
          { name: "ornitho-", detail: "oiseau → ornithologie" },
          { name: "ichty(o)-", detail: "poisson → ichtyologie" },
          { name: "entomo-", detail: "insecte → entomologie" },
        ],
      },
      {
        title: "Quantités et mesures (grec/latin)",
        items: [
          { name: "mono-", detail: "un → monotrème, monothéisme" },
          { name: "di-", detail: "deux → diptyque, dicotylédone" },
          { name: "poly-", detail: "plusieurs → polyphonie, polygone" },
          { name: "pan-", detail: "tout → pandémie, panoptique" },
          { name: "macro-", detail: "grand → macroscopique" },
          { name: "micro-", detail: "petit → microscope" },
          { name: "méga-", detail: "très grand → mégalithe" },
          { name: "brady-", detail: "lent → bradycardie" },
          { name: "tachy-", detail: "rapide → tachycardie" },
        ],
      },
      {
        title: "Suffixes courants à QPUC",
        items: [
          { name: "-chorie", detail: "dispersion → anémochorie, zoochorie" },
          { name: "-game", detail: "reproduction → cryptogame, phanérogame" },
          { name: "-sperme", detail: "graine → angiosperme, gymnosperme" },
          { name: "-graphie", detail: "écriture, dessin → lithographie, radiographie" },
          { name: "-logie", detail: "étude → ornithologie, étymologie" },
          { name: "-mètre/-métrie", detail: "mesure → baromètre, géométrie" },
          { name: "-phyte", detail: "plante → épiphyte, xérophyte" },
          { name: "-phage", detail: "manger → anthropophage, bactériophage" },
          { name: "-scope", detail: "voir → télescope, endoscope" },
        ],
      },
    ],
  },
  {
    id: "cepages-regions",
    name: "Cépages par région",
    icon: "🍷",
    category: "Gastronomie",
    description: "Les cépages et appellations clés",
    type: "grouped",
    groups: [
      {
        title: "Bourgogne",
        items: [
          { name: "Pinot noir", detail: "Rouges : Chambertin, Romanée-Conti, Clos-Vougeot, Pommard, Nuits-Saint-Georges" },
          { name: "Chardonnay", detail: "Blancs : Chablis, Meursault, Puligny-Montrachet, Pouilly-Fuissé" },
          { name: "Gamay", detail: "Beaujolais (pas AOC Bourgogne)" },
        ],
      },
      {
        title: "Bordeaux",
        items: [
          { name: "Merlot", detail: "Dominant rive droite : Pomerol, Saint-Émilion" },
          { name: "Cabernet Sauvignon", detail: "Dominant rive gauche : Médoc, Graves, Pauillac, Margaux" },
          { name: "Cabernet Franc", detail: "Assemblage, surtout Saint-Émilion" },
          { name: "Sémillon", detail: "Blancs liquoreux : Sauternes, Barsac" },
        ],
      },
      {
        title: "Vallée du Rhône",
        items: [
          { name: "Syrah", detail: "Nord : Côte-Rôtie, Hermitage, Cornas, Saint-Joseph" },
          { name: "Viognier", detail: "Condrieu, Château-Grillet (blanc)" },
          { name: "Grenache", detail: "Sud : Châteauneuf-du-Pape (jusqu'à 18 cépages), Gigondas" },
        ],
      },
      {
        title: "Loire",
        items: [
          { name: "Sauvignon blanc", detail: "Pouilly-Fumé, Sancerre" },
          { name: "Chenin blanc", detail: "Vouvray, Savennières, Coteaux-du-Layon" },
          { name: "Melon de Bourgogne", detail: "Muscadet" },
          { name: "Cabernet Franc", detail: "Chinon, Bourgueil, Saumur-Champigny" },
        ],
      },
      {
        title: "Alsace",
        items: [
          { name: "Riesling", detail: "Le plus planté, secs et minéraux" },
          { name: "Gewurztraminer", detail: "Aromatique, épicé, vendanges tardives" },
          { name: "Pinot gris", detail: "Riche et ample" },
          { name: "Muscat d'Alsace", detail: "Sec (contrairement aux autres muscats)" },
        ],
      },
      {
        title: "Jura",
        items: [
          { name: "Savagnin", detail: "Vin jaune (62 cl, clavelin, voile de levures)" },
          { name: "Poulsard", detail: "Rouge léger, typiquement jurassien" },
          { name: "Trousseau", detail: "Rouge plus charpenté" },
        ],
      },
    ],
  },
  {
    id: "detroits-canaux",
    name: "Détroits, caps et canaux",
    icon: "🌊",
    category: "Géographie",
    description: "Les passages maritimes et fluviaux à connaître",
    type: "table",
    columns: ["Nom", "Relie / Sépare", "Fait remarquable"],
    rows: [
      ["Détroit de Messine", "Italie — Sicile", "Charybde et Scylla (mythologie)"],
      ["Détroit de Gibraltar", "Espagne — Maroc", "Colonnes d'Hercule dans l'Antiquité"],
      ["Pas-de-Calais", "France — Angleterre", "33 km, le plus fréquenté au monde"],
      ["Bosphore", "Europe — Asie (Istanbul)", "Relie mer Noire et mer de Marmara"],
      ["Dardanelles", "Europe — Asie (Turquie)", "Relie Marmara et mer Égée"],
      ["Détroit de Malacca", "Malaisie — Sumatra", "Route maritime la plus empruntée (Asie)"],
      ["Détroit de Magellan", "Amérique du Sud — Terre de Feu", "Découvert en 1520"],
      ["Détroit de Béring", "Alaska — Sibérie", "Sépare Pacifique et Arctique"],
      ["Détroit d'Ormuz", "Iran — Oman", "Passage du pétrole du Golfe"],
      ["Canal de Suez", "Méditerranée — Mer Rouge", "Inauguré 1869, Ferdinand de Lesseps"],
      ["Canal de Panama", "Atlantique — Pacifique", "Inauguré 1914, écluses"],
      ["Canal de Kiel", "Mer du Nord — Baltique", "Inauguré 1895, évite le Jutland"],
      ["Canal de Briare", "Loire — Loing", "Plus ancien canal français en service"],
      ["Canal du Midi", "Atlantique — Méditerranée", "Pierre-Paul Riquet, 1681"],
    ],
  },
  {
    id: "instruments-orchestre",
    name: "Instruments de l'orchestre",
    icon: "🎵",
    category: "Musique",
    description: "Familles, tessiture et faits marquants",
    type: "grouped",
    groups: [
      {
        title: "Bois (anche simple)",
        items: [
          { name: "Clarinette", detail: "Anche simple. Tessiture la plus étendue des bois." },
          { name: "Saxophone", detail: "Anche simple. Inventé par Adolphe Sax (1846). Pas dans l'orchestre classique." },
        ],
      },
      {
        title: "Bois (anche double)",
        items: [
          { name: "Hautbois", detail: "Anche double. Donne le LA à l'orchestre pour l'accord." },
          { name: "Cor anglais", detail: "Anche double. Hautbois alto en fa. Malgré son nom, pas anglais." },
          { name: "Basson", detail: "Anche double. Grave. Le « clown de l'orchestre »." },
          { name: "Contrebasson", detail: "Anche double. L'instrument le plus grave de l'orchestre." },
        ],
      },
      {
        title: "Bois (sans anche)",
        items: [
          { name: "Flûte traversière", detail: "Embouchure latérale. En métal mais classée dans les bois." },
          { name: "Piccolo", detail: "Petite flûte. L'instrument le plus aigu de l'orchestre." },
        ],
      },
      {
        title: "Cuivres",
        items: [
          { name: "Trompette", detail: "Le plus aigu des cuivres courants." },
          { name: "Cor d'harmonie", detail: "Tuyau enroulé de 3,6 m. Son chaud et velouté." },
          { name: "Trombone", detail: "Coulisse (pas de pistons). Seul cuivre à coulisse." },
          { name: "Tuba", detail: "Le plus grave des cuivres." },
        ],
      },
      {
        title: "Cordes frottées",
        items: [
          { name: "Violon", detail: "Le plus aigu. Accordé sol-ré-la-mi." },
          { name: "Alto", detail: "Un peu plus grand que le violon. Accordé do-sol-ré-la." },
          { name: "Violoncelle", detail: "Se joue assis, piqué au sol." },
          { name: "Contrebasse", detail: "La plus grande. Se joue debout ou assis sur tabouret haut." },
        ],
      },
      {
        title: "Cordes pincées",
        items: [
          { name: "Harpe", detail: "47 cordes, 7 pédales. Seul instrument à cordes pincées de l'orchestre." },
          { name: "Pizzicato", detail: "Technique : pincer les cordes d'un instrument à archet avec les doigts." },
        ],
      },
      {
        title: "Percussions",
        items: [
          { name: "Timbales", detail: "Seule percussion à son déterminé indispensable. Peau sur chaudron de cuivre." },
          { name: "Célesta", detail: "Clavier frappant des lames de métal. Son cristallin (Danse de la fée Dragée)." },
          { name: "Glockenspiel", detail: "Jeu de lames métalliques, son brillant." },
          { name: "Triangle", detail: "Tige d'acier, son cristallin indéterminé." },
        ],
      },
    ],
  },
  {
    id: "marechaux-empire",
    name: "Maréchaux d'Empire",
    icon: "⚔️",
    category: "Histoire",
    description: "Les 26 maréchaux nommés par Napoléon",
    type: "table",
    columns: ["Maréchal", "Titre", "Fait marquant"],
    rows: [
      ["Augereau", "Duc de Castiglione", "Rallia les Bourbons en 1814"],
      ["Bernadotte", "Prince de Pontecorvo", "Devint roi de Suède (Charles XIV)"],
      ["Berthier", "Prince de Wagram", "Chef d'état-major de Napoléon, mort en 1815"],
      ["Bessières", "Duc d'Istrie", "Tué à Lützen (1813)"],
      ["Brune", "—", "Assassiné par des royalistes à Avignon (1815)"],
      ["Davout", "Duc d'Auerstaedt, prince d'Eckmühl", "Seul maréchal invaincu, le meilleur stratège"],
      ["Grouchy", "—", "Blâmé pour ne pas être arrivé à Waterloo"],
      ["Jourdan", "—", "Vainqueur à Fleurus (1794)"],
      ["Kellermann", "Duc de Valmy", "Héros de Valmy (1792)"],
      ["Lannes", "Duc de Montebello", "Mort à Essling (1809), « premier soldat de France »"],
      ["Lefebvre", "Duc de Dantzig", "D'origine modeste, ancien sergent"],
      ["Macdonald", "Duc de Tarente", "D'origine écossaise"],
      ["Marmont", "Duc de Raguse", "Trahit Napoléon en 1814 (« raguser » = trahir)"],
      ["Masséna", "Duc de Rivoli, prince d'Essling", "« L'enfant chéri de la victoire »"],
      ["Moncey", "Duc de Conegliano", "Défendit la barrière de Clichy en 1814"],
      ["Mortier", "Duc de Trévise", "Tué dans l'attentat de Fieschi (1835)"],
      ["Murat", "Roi de Naples", "Beau-frère de Napoléon, fusillé en 1815"],
      ["Ney", "Duc d'Elchingen, prince de la Moskova", "« Le Brave des braves », fusillé en 1815"],
      ["Oudinot", "Duc de Reggio", "Blessé 34 fois au combat"],
      ["Pérignon", "—", "Maréchal honoraire"],
      ["Poniatowski", "—", "Seul maréchal étranger, mort à Leipzig (1813)"],
      ["Sérurier", "—", "Maréchal honoraire"],
      ["Soult", "Duc de Dalmatie", "Devint président du Conseil sous Louis-Philippe"],
      ["Suchet", "Duc d'Albuféra", "Brillant en Espagne, administrateur habile"],
      ["Victor", "Duc de Bellune", "Rallia les Bourbons"],
    ],
  },
  {
    id: "operateurs-qpuc",
    name: "Mots-clés QPUC",
    icon: "🎯",
    category: "Stratégie",
    description: "Les formulations récurrentes et leurs réponses types",
    type: "grouped",
    groups: [
      {
        title: "« Comment appelle-t-on... »",
        items: [
          { name: "...le mâle de l'oie ?", detail: "Le jars" },
          { name: "...une lime conique et pointue ?", detail: "Queue-de-rat" },
          { name: "...l'inflammation de [organe] ?", detail: "Suffixe en -ite (voir liste médicale)" },
          { name: "...un terrain planté de pommiers ?", detail: "Un verger" },
          { name: "...la pierre au sommet d'une voûte ?", detail: "Clef de voûte" },
        ],
      },
      {
        title: "« Quel est le chef-lieu de... »",
        items: [
          { name: "Creuse", detail: "Guéret" },
          { name: "Gers", detail: "Auch" },
          { name: "Ariège", detail: "Foix" },
          { name: "Meuse", detail: "Bar-le-Duc" },
          { name: "Haute-Marne", detail: "Chaumont" },
          { name: "Lozère", detail: "Mende" },
          { name: "Manche", detail: "Saint-Lô" },
          { name: "Haute-Saône", detail: "Vesoul" },
        ],
      },
      {
        title: "« Quel terme désigne... » (vocabulaire rare)",
        items: [
          { name: "Dispersion des graines par le vent", detail: "Anémochorie" },
          { name: "Four alchimique", detail: "Athanor" },
          { name: "Cuir de peau de raie", detail: "Galuchat" },
          { name: "Outil pour imprimer un motif sur le cuir", detail: "Matoir" },
          { name: "Amorce de feu d'artifice", detail: "Espolette" },
          { name: "Contraire de dilution (finance)", detail: "Relution" },
          { name: "Écolier des petites classes (7 lettres, G)", detail: "Grimaud" },
          { name: "Organisme à reproduction cachée", detail: "Cryptogame" },
        ],
      },
      {
        title: "Pièges classiques",
        items: [
          { name: "Le Loir (sans E)", detail: "Affluent de la Loire, passe à Blois/Vendôme. Ne pas confondre avec la Loire !" },
          { name: "Héraclite ≠ Hérodote", detail: "Héraclite = l'Obscur (changement). Hérodote = père de l'Histoire" },
          { name: "Litote ≠ Euphémisme", detail: "Litote : dire moins pour dire PLUS. Euphémisme : atténuer le désagréable" },
          { name: "Métonymie ≠ Synecdoque", detail: "Métonymie : lien logique. Synecdoque : partie/tout" },
          { name: "Hémistiche", detail: "Chaque moitié d'un vers coupé par la césure (pas le vers entier)" },
        ],
      },
    ],
  },
];
