// Base de données QPUC - Calibrée sur les vrais questionnaires des clubs QPUC de Paris
// Sources : Pierre Bessac-Cantuel (Clubs QPUC Paris I & II), Club QPUC Genève, Eybens-Grenoble
const QUESTIONS = {
  // ============================================
  // 9 POINTS GAGNANTS
  // ============================================
  neufPoints: {
    // 1 point : spécifiques, nécessitent un fait précis (pas de culture générale scolaire)
    faciles: [
      { q: "Si vous commandez des fines de claire dans un restaurant, que va-t-on vous apporter ?", r: "Des huîtres" },
      { q: "Quel petit vase muni de chaînes un prêtre balance-t-il pour répandre l'odeur d'encens ?", r: "L'encensoir" },
      { q: "Quelle petite guitare porte un nom signifiant « puce qui vole » en hawaïen ?", r: "Le ukulélé" },
      { q: "À Paris, quelle sculpture de Georges Diebolt associe-t-on au pont de l'Alma ?", r: "Le zouave" },
      { q: "Quel futur roi de France fut baptisé avec une gousse d'ail et du jurançon, en 1554 ?", r: "Henri IV" },
      { q: "Quel saint ayant évangélisé les Arvernes a donné son nom à un fromage souvent désigné par l'apocope Saint-Nec' ?", r: "Saint-Nectaire" },
      { q: "Quel serpent peut être émeraude, des sables, de Duméril ou constricteur ?", r: "Le boa" },
      { q: "Quels fruits avez-vous envie de manger si vous achetez, au marché, des Mara des bois ?", r: "Des fraises" },
      { q: "Quel métier artistique a été exercé notamment par Grock et Achille Zavatta ?", r: "Clown" },
      { q: "À quel fruit associe-t-on l'embout des arrosoirs et des douches ?", r: "La pomme" },
      { q: "Quel nom porte chacune des deux parties d'un vers coupé par la césure ?", r: "Un hémistiche" },
      { q: "Comment appelle-t-on le mâle de l'oie ?", r: "Le jars" },
      { q: "Quel os, situé à la base de la langue, est le seul du corps humain à ne s'articuler avec aucun autre ?", r: "L'os hyoïde" },
      { q: "Quel détroit sépare l'Italie continentale de la Sicile ?", r: "Le détroit de Messine" },
      { q: "Quel autre nom d'oiseau donne-t-on à l'étourneau ?", r: "Le sansonnet" },
      { q: "Quelle figure de style consiste à atténuer une idée pour en renforcer l'effet ?", r: "La litote" },
      { q: "Comment appelle-t-on une lime conique et pointue en mécanique ?", r: "Une queue-de-rat" },
      { q: "Quelle est la plus petite roue dentée d'un engrenage ?", r: "Le pignon" },
      { q: "Comment appelle-t-on l'inflammation de la muqueuse de l'estomac ?", r: "La gastrite" },
      { q: "Quel nom donne-t-on à la pierre placée au sommet d'un arc ou d'une voûte ?", r: "La clef de voûte" },
      { q: "Quel procédé d'impression en creux sur métal utilise l'action d'un acide ?", r: "L'eau-forte" },
      { q: "Comment appelle-t-on le traitement thermique qui consiste à plonger un métal chauffé dans un bain froid ?", r: "La trempe" },
      { q: "Quel roi de France fut assassiné par le moine jacobin Jacques Clément en 1589 ?", r: "Henri III" },
      { q: "Comment appelle-t-on en médecine l'inflammation de la vésicule biliaire ?", r: "La cholécystite" },
      { q: "Quel terme botanique désigne le fruit charnu à noyau comme la cerise, la pêche ou l'olive ?", r: "Une drupe" },
      { q: "Quel est le chef-lieu du département de la Creuse ?", r: "Guéret" },
      { q: "Quel est le chef-lieu du département du Gers ?", r: "Auch" },
      { q: "Quel est le chef-lieu du département de l'Ariège ?", r: "Foix" },
      { q: "Quel est le chef-lieu du département de la Meuse ?", r: "Bar-le-Duc" },
      { q: "Quel instrument à anche double donne généralement le la à l'orchestre pour l'accord ?", r: "Le hautbois" },
      { q: "Quel terme musical désigne un passage joué en pinçant les cordes avec les doigts ?", r: "Le pizzicato" },
      { q: "Quel géographe grec, auteur d'une Géographie en 17 livres, vécut au Ier siècle ?", r: "Strabon" },
      { q: "Quel terme de géologie désigne un pli dont la convexité est orientée vers le haut ?", r: "Un anticlinal" },
      { q: "Quel canal relie la Loire au Loing, et est considéré comme le plus ancien canal français encore en service ?", r: "Le canal de Briare" },
      { q: "Quel philosophe présocratique est surnommé l'Obscur en raison de la difficulté de sa pensée ?", r: "Héraclite" },
      { q: "Quel est le nom de l'alliage composé de cuivre et de zinc ?", r: "Le laiton" },
      { q: "Quel pape fut arrêté par les troupes du Directoire et mourut en captivité à Valence en 1799 ?", r: "Pie VI" },
      { q: "Quelle roche volcanique vitreuse, naturellement noire, servait à tailler des lames à la préhistoire ?", r: "L'obsidienne" },
      { q: "Quel est le nom de la rivière qui passe aux Eyzies-de-Tayac, haut lieu de la préhistoire en Dordogne ?", r: "La Vézère" },
      { q: "Quel château d'Indre-et-Loire est bâti sur les arches d'un pont qui enjambe le Cher ?", r: "Chenonceau" },
      { q: "Quel physicien irlandais a donné son nom à l'unité internationale de température absolue ?", r: "Lord Kelvin (William Thomson)" },
      { q: "Quel terme de rhétorique désigne la répétition d'un mot en tête de plusieurs phrases ?", r: "L'anaphore" },
      { q: "Quel terme de droit romain désigne le droit de propriété lié au fait de naître sur un territoire ?", r: "Le jus soli" },
      { q: "Comment appelle-t-on en droit romain le pouvoir absolu du père sur les membres de sa famille ?", r: "La patria potestas" },
      { q: "Quel est le nom de l'instrument de mesure à mâchoires coulissantes utilisé en mécanique de précision ?", r: "Le pied à coulisse" },
      { q: "Quel terme désigne le procédé d'impression à plat inventé par Senefelder en 1796 ?", r: "La lithographie" },
      { q: "Quelle protéine fibreuse constitue l'essentiel des cheveux et des ongles ?", r: "La kératine" },
      { q: "Quel mot désigne à la fois un instrument à cordes pincées et une constellation ?", r: "La lyre" },
      { q: "Quel astronome danois, connu pour son nez de métal, observa une nouvelle étoile en 1572 ?", r: "Tycho Brahé" },
      { q: "Quel phénomène permet à un solide de passer directement à l'état gazeux ?", r: "La sublimation" },
      { q: "Quel cépage blanc est le seul autorisé dans l'appellation Pouilly-Fumé ?", r: "Le sauvignon blanc" },
      { q: "De quel arbre méditerranéen utilise-t-on le bois dur pour faire les manches d'outils ?", r: "Le micocoulier" },
      { q: "Quel est le chef-lieu du département du Jura, connu pour son vin jaune ?", r: "Lons-le-Saunier" },
    ],

    // 2 points : nécessitent une bonne culture spécialisée
    moyennes: [
      { q: "Quel cycliste surnommé le Petit Ramoneur fut le premier vainqueur du Tour de France en 1903 ?", r: "Maurice Garin" },
      { q: "Quel acteur français, vedette du cinéma muet, s'appelait à l'état civil Gabriel Leuvielle ?", r: "Max Linder" },
      { q: "Dans quelle discipline scientifique est décernée depuis 1877 la médaille Davy ?", r: "La chimie" },
      { q: "Quel gambiste et chef d'orchestre catalan, créateur de l'ensemble Hespèrion XXI, porte le même prénom que l'interprète de Dur dur d'être bébé ?", r: "Jordi Savall" },
      { q: "Comment s'appelle le plat suisse composé d'une galette de pommes de terre revenue dans du beurre ?", r: "Le rösti" },
      { q: "De quelle partie du corps de sa femme Wilhelm Röntgen fit-il la première radiographie en 1895 ?", r: "La main" },
      { q: "De quelle institution l'hôtel de Toulouse, situé rue Croix-des-Petits-Champs à Paris, est-il le siège ?", r: "La Banque de France" },
      { q: "Quel nom Napoléon donna-t-il aux soldats de sa garde, du fait qu'ils se plaignaient souvent ?", r: "Les grognards" },
      { q: "En jardinage, quel verbe, synonyme de démarier, désigne le fait d'aérer des plants après un semis ?", r: "Éclaircir" },
      { q: "Lors d'une compétition officielle de gymnastique, quelle est la longueur d'une poutre ?", r: "5 mètres" },
      { q: "Dans quelle région de France peut-on manger de la teurgoule avec une brioche appelée fallue ?", r: "La Normandie" },
      { q: "Sur quelle île méditerranéenne se trouve la ville de Taormina ?", r: "La Sicile" },
      { q: "Quel maréchal d'Empire, duc de Montebello, fut mortellement blessé à Essling en 1809 ?", r: "Lannes (Jean Lannes)" },
      { q: "Quel ingénieur français, né à Châlons-sur-Marne en 1769, donna son nom au procédé de conservation des aliments en bocaux ?", r: "Nicolas Appert" },
      { q: "Quel traité de 1713 mit fin à la guerre de Succession d'Espagne ?", r: "Le traité d'Utrecht" },
      { q: "Quel peintre vénitien du XVIe siècle, de son vrai nom Jacopo Robusti, est surnommé le Petit Teinturier ?", r: "Le Tintoret" },
      { q: "Quel opéra de Gluck, créé à Paris en 1774, marque la réforme de l'opéra en privilégiant l'action dramatique ?", r: "Iphigénie en Aulide" },
      { q: "Quel général d'origine saxonne, vainqueur à Fontenoy en 1745, était au service de Louis XV ?", r: "Le maréchal de Saxe (Maurice de Saxe)" },
      { q: "Quel botaniste belge du XVIe siècle, auteur d'une Historia plantarum, introduisit la tulipe en Europe occidentale ?", r: "Charles de L'Écluse (Clusius)" },
      { q: "Quelle bataille de 1214 permit à Philippe Auguste d'affirmer la suprématie capétienne ?", r: "La bataille de Bouvines" },
      { q: "Quel est le terme médical désignant une inflammation du péricarde, l'enveloppe du cœur ?", r: "La péricardite" },
      { q: "Quel compositeur hambourgeois du XVIIe siècle, organiste à Lübeck, influença le jeune Bach ?", r: "Dietrich Buxtehude" },
      { q: "Quel chimiste suisse découvrit le LSD en 1938 en travaillant sur les alcaloïdes de l'ergot de seigle ?", r: "Albert Hofmann" },
      { q: "Quel sculpteur français du XVIIe siècle est l'auteur du buste de Louis XIV le plus célèbre ?", r: "Antoine Coysevox" },
      { q: "Quel architecte parisien du XVIIe siècle conçut la Colonnade du Louvre ?", r: "Claude Perrault" },
      { q: "Quel jeu de société créé en 1985 par Rob Angel consiste à faire deviner un mot à l'aide d'un dessin ?", r: "Pictionary" },
      { q: "Quel vin du Jura, élevé sous un voile de levures, est vendu en bouteille de 62 cl appelée clavelin ?", r: "Le vin jaune" },
      { q: "Quel poète symboliste français a écrit Hérodiade et Un coup de dés jamais n'abolira le hasard ?", r: "Stéphane Mallarmé" },
      { q: "Quel peintre né en 1748 est l'auteur de La Mort de Marat, conservé à Bruxelles ?", r: "Jacques-Louis David" },
      { q: "Quelle invention de l'ingénieur Bourgeois de Châtaublanc au XVIIIe siècle permit l'exercice du métier de falotier ?", r: "Le réverbère" },
      { q: "Quel pape, né Rodrigo Borgia, régna de 1492 à 1503 et eut pour enfants César et Lucrèce ?", r: "Alexandre VI" },
      { q: "Quel canal, inauguré en 1895, relie la mer du Nord à la mer Baltique en évitant de contourner le Jutland ?", r: "Le canal de Kiel" },
      { q: "Quel est le nom de la technique de fonte en bronze utilisant un modèle en cire qui disparaît lors de la coulée ?", r: "La cire perdue" },
      { q: "Quel cépage blanc produit le célèbre Condrieu, dans la vallée du Rhône septentrionale ?", r: "Le viognier" },
      { q: "Quelle appellation bordelaise de la rive droite produit exclusivement des vins rouges à base de merlot ?", r: "Pomerol" },
      { q: "Quel souverain pontife convoqua le concile de Trente en 1545 pour répondre à la Réforme ?", r: "Paul III" },
      { q: "Quel écrivain japonais, prix Nobel 1968, est l'auteur de Pays de neige ?", r: "Yasunari Kawabata" },
      { q: "Quel romancier russe, condamné à mort puis gracié au dernier moment, est l'auteur de L'Idiot et du Joueur ?", r: "Fiodor Dostoïevski" },
      { q: "Quel fleuve côtier de Normandie, long de 225 km, passe à Lisieux et se jette dans la Manche à Honfleur ?", r: "La Touques" },
      { q: "Quel naturaliste suédois du XVIIIe siècle établit la nomenclature binominale latine des espèces ?", r: "Carl von Linné" },
      { q: "Quel vin doux naturel de Banyuls est oxydé intentionnellement dans des bonbonnes au soleil ?", r: "Le banyuls (ou le rancio)" },
      { q: "Quel accordéoniste surnommé Aimable est resté le plus populaire de France pendant les années 1960-70 ?", r: "Aimable Pluchard" },
      { q: "Quel peintre français néoclassique, élève de David, est l'auteur de L'Apothéose d'Homère et du Grand Odalisque ?", r: "Jean-Auguste-Dominique Ingres" },
      { q: "Quel terme de linguistique désigne un mot qui sonne comme ce qu'il signifie, comme coucou ou murmure ?", r: "L'onomatopée" },
    ],

    // 3 points : expert, vocabulaire rare, faits très spécifiques
    difficiles: [
      { q: "Quel botaniste américain a établi une classification des plantes à fleurs qui porta son nom ?", r: "Cronquist (Arthur Cronquist)" },
      { q: "En botanique, quel mot issu du grec désigne le mode de dispersion des graines par le vent ?", r: "L'anémochorie" },
      { q: "Au Moyen Âge, quel four tirant son nom d'un mot arabe devait permettre de réaliser la pierre philosophale ?", r: "L'athanor" },
      { q: "En économie, quel terme désignant l'augmentation du pouvoir actionnarial est le contraire de dilution ?", r: "La relution" },
      { q: "En botanique, quel adjectif issu du grec désigne un organisme dont l'appareil reproducteur n'est pas apparent, comme les algues et les mousses ?", r: "Cryptogame" },
      { q: "Quelle plante également appelée trigonelle doit son nom au fait que les Romains importaient du foin grec pour nourrir leurs chevaux ?", r: "Le fenugrec" },
      { q: "Par quel mot de 7 lettres commençant par un G désignait-on autrefois un écolier des petites classes ?", r: "Grimaud" },
      { q: "Quel est le plus long mot de la langue française s'écrivant uniquement avec des chiffres romains ?", r: "Civil" },
      { q: "Quel maître gainier du XVIIIe siècle laissa son nom à un cuir fabriqué à partir d'une peau de raie ou de requin ?", r: "Galluchat" },
      { q: "Quel outil en métal permet de frapper le cuir pour y imprimer un motif décoratif ?", r: "Le matoir" },
      { q: "Quel dispositif d'allumage à retardement permet à la bombe d'un feu d'artifice d'exploser après son lancement ?", r: "L'espolette" },
      { q: "Comment appelle-t-on les premières explosions d'un spectacle pyrotechnique ?", r: "Les marrons d'air" },
      { q: "À quel peintre, né Pietro Vannucci et maître de Raphaël, doit-on l'Annonciation de Fano ?", r: "Le Pérugin" },
      { q: "En Auvergne, quel mot désignant la montée des troupeaux lors de la transhumance est le contraire de dévalade ?", r: "La montade" },
      { q: "Dans le corps de ballet de l'Opéra de Paris, quel échelon est situé entre sujet et danseur étoile ?", r: "Premier danseur" },
      { q: "En cuisine, que fait-on lorsqu'on fatigue la salade ?", r: "On la remue (on la touille)" },
      { q: "Quel roman paru en 1860, dénonçant l'exploitation coloniale dans les Indes néerlandaises, doit-on à Multatuli ?", r: "Max Havelaar" },
      { q: "Dans Cyrano de Bergerac d'Edmond Rostand, quelle tirade commence par « Et que faudrait-il faire » ?", r: "La tirade des Non-merci" },
      { q: "Quel genre d'animal est l'œdicnème criard, également appelé courlis de terre ?", r: "Un oiseau" },
      { q: "Quel chimiste du XIXe siècle donna son nom à un alliage de zinc, nickel et argent utilisé pour les couverts ?", r: "Ruolz (Henri de Ruolz)" },
      { q: "En médecine, dans quel cas une femme peut-elle souffrir de dysménorrhées ?", r: "Lors des règles" },
      { q: "Quel petit vase utilisé par les athlètes grecs contenait l'huile dont ils s'enduisaient le corps ?", r: "L'aryballe" },
      { q: "Quel tissu conducteur transporte la sève brute des racines aux feuilles chez les plantes vasculaires ?", r: "Le xylème" },
      { q: "Quel terme désigne la maçonnerie d'un pont entre deux piles ou entre une pile et une culée ?", r: "Une travée" },
      { q: "À quel ordre de mammifères pondeurs appartient l'ornithorynque ?", r: "Les monotrèmes" },
      { q: "Quel architecte et designer allemand fonda le Bauhaus à Weimar en 1919 ?", r: "Walter Gropius" },
      { q: "Quel physicien soviétique, prix Nobel 1962, formula la théorie de la superfluidité de l'hélium liquide ?", r: "Lev Landau" },
      { q: "Quel compositeur danois est l'auteur de la symphonie L'Inextinguible, sa 4e, créée en 1916 ?", r: "Carl Nielsen" },
      { q: "Quel film de Jacques Rivette, tourné en 1968 et d'une durée de 12 heures 40, ne fut diffusé que dans une seule salle ?", r: "Out 1" },
      { q: "Quel compositeur polonais du XXe siècle est l'auteur du Thrène à la mémoire des victimes d'Hiroshima ?", r: "Krzysztof Penderecki" },
      { q: "Quel abbé du XVIIe siècle rédigea avec Claude Lancelot une grammaire générale et raisonnée à Port-Royal ?", r: "Antoine Arnauld" },
      { q: "Quel romancier du XVIIe siècle est l'auteur de L'Astrée, roman pastoral fleuve en cinq parties, inachevé à sa mort ?", r: "Honoré d'Urfé" },
      { q: "Quel peintre symboliste belge du XIXe siècle est l'auteur de La Chute des anges rebelles ?", r: "Félicien Rops" },
      { q: "Quel terme de phonétique désigne le son aigu émis par certaines consonnes comme le /s/ ou le /ʃ/ ?", r: "La sibilante" },
      { q: "Quel opéra de Janáček, créé à Brno en 1904, est inspiré de la vie paysanne morave ?", r: "Jenůfa" },
      { q: "Quel artiste publia en 1916 le manifeste Dada au cabaret Voltaire à Zurich ?", r: "Hugo Ball" },
      { q: "Quel compositeur français du XXe siècle écrivit le Concerto champêtre pour clavecin et orchestre pour Wanda Landowska ?", r: "Francis Poulenc" },
      { q: "Quel ingénieur français du XIXe siècle inventa le procédé de fabrication de l'aluminium par électrolyse ?", r: "Paul Héroult" },
      { q: "Quel mathématicien anglais du XIXe siècle conçut la machine analytique, ancêtre de l'ordinateur, restée à l'état de projet ?", r: "Charles Babbage" },
      { q: "Quel peintre expressionniste allemand, membre de Die Brücke, est connu pour ses aplats de couleurs criardes et ses silhouettes anguleuses ?", r: "Ernst Ludwig Kirchner" },
      { q: "Quelle langue indo-européenne éteinte depuis le IVe siècle, connue par la traduction de la Bible de Wulfila, est l'ancêtre des langues germaniques ?", r: "Le gotique" },
      { q: "Quel col des Alpes-Maritimes, à 2 802 mètres, sépare le bassin de la Tinée de celui de la Roya ?", r: "Le col de la Bonette" },
      { q: "Quel manifeste de 1910, signé par Boccioni, Carrà et Russolo, proclama les principes du futurisme en peinture ?", r: "Le Manifeste des peintres futuristes" },
      { q: "Quel physicien suisse, prix Nobel 1987, est l'un des découvreurs de la supraconductivité à haute température ?", r: "Karl Alexander Müller" },
      { q: "Quelle sonde soviétique fut la première à se poser en douceur sur la Lune en 1966 ?", r: "Luna 9" },
      { q: "Quel compositeur autrichien, surnommé le maître de la symphonie, écrivit neuf symphonies monumentales dont la 8e inachevée ?", r: "Anton Bruckner" },
      { q: "Quel écrivain péruvien, prix Nobel 2010, est l'auteur de La Fête au Bouc et de Conversation à La Cathédrale ?", r: "Mario Vargas Llosa" },
      { q: "Quel évêque de Meaux, prédicateur de Louis XIV, est l'auteur de l'Oraison funèbre d'Henriette d'Angleterre ?", r: "Bossuet" },
      { q: "Quel poète grec, prix Nobel 1963, est l'auteur du recueil Strophe ?", r: "Giorgos Séféris" },
      { q: "Quelle romancière autrichienne, prix Nobel 2004, est l'auteure de La Pianiste ?", r: "Elfriede Jelinek" },
    ],
  },

  // ============================================
  // 4 À LA SUITE - Thèmes avec 4 questions progressives
  // ============================================
  quatreALaSuite: [
    {
      theme: "Les feux d'artifice",
      questions: [
        { q: "Comment appelle-t-on l'art de concevoir des feux d'artifice ?", r: "La pyrotechnie" },
        { q: "Quel peuple d'Asie est à l'origine, en 1044, d'un premier procédé mêlant poudre et salpêtre ?", r: "Les Chinois" },
        { q: "Comment appelle-t-on les premières explosions d'un spectacle pyrotechnique ?", r: "Les marrons d'air" },
        { q: "Quel dispositif d'allumage à retardement permet à la bombe d'exploser après son lancement ?", r: "L'espolette" },
      ],
    },
    {
      theme: "Le cuir",
      questions: [
        { q: "Comment appelle-t-on l'artisan qui travaille le cuir pour fabriquer des selles et des harnais ?", r: "Le sellier" },
        { q: "Quel procédé chimique transforme la peau brute en cuir imputrescible ?", r: "Le tannage" },
        { q: "Quel maître gainier du XVIIIe siècle laissa son nom à un cuir de peau de raie ou de requin ?", r: "Galluchat" },
        { q: "Quel outil en métal permet de frapper le cuir pour y imprimer un motif décoratif ?", r: "Le matoir" },
      ],
    },
    {
      theme: "Le sport dans l'Antiquité",
      questions: [
        { q: "Dans quelle ville du Péloponnèse les premiers Jeux se sont-ils tenus en 776 avant J.-C. ?", r: "Olympie" },
        { q: "Comment appelle-t-on l'épreuve combinant cinq disciplines dont la course, le saut et le lancer ?", r: "Le pentathlon" },
        { q: "Quelle couronne végétale était remise aux vainqueurs des Jeux olympiques antiques ?", r: "Le kotinos (couronne d'olivier)" },
        { q: "Quel petit vase utilisé par les athlètes contenait l'huile dont ils s'enduisaient le corps ?", r: "L'aryballe" },
      ],
    },
    {
      theme: "Les fromages de France",
      questions: [
        { q: "Quel fromage normand à pâte molle et croûte fleurie tire son nom d'un village du pays d'Auge ?", r: "Le camembert" },
        { q: "Quel fromage savoyard à pâte pressée cuite est produit en meules de 35 à 40 kg ?", r: "Le beaufort" },
        { q: "Quel fromage corse, à pâte molle et à l'odeur très forte, est affiné avec des larves de mouche ?", r: "Le casgiu merzu" },
        { q: "Quel saint ayant évangélisé les Arvernes donna son nom à un fromage d'Auvergne souvent dit Saint-Nec' ?", r: "Saint-Nectaire" },
      ],
    },
    {
      theme: "Les maréchaux d'Empire",
      questions: [
        { q: "Quel maréchal d'Empire, prince d'Essling, commanda l'armée de Portugal ?", r: "Masséna" },
        { q: "Quel maréchal d'Empire, duc de Montebello, mourut à Essling en 1809 ?", r: "Lannes" },
        { q: "Quel maréchal d'Empire, duc d'Elchingen puis prince de la Moskova, fut fusillé en 1815 ?", r: "Ney (Michel Ney)" },
        { q: "Quel maréchal d'Empire, duc de Trévise, mourut dans l'attentat de Fieschi en 1835 ?", r: "Mortier (Édouard Mortier)" },
      ],
    },
    {
      theme: "Les vins du Jura",
      questions: [
        { q: "Quel est le chef-lieu du Jura, dont le vignoble s'étend sur le Revermont ?", r: "Lons-le-Saunier" },
        { q: "Quel vin du Jura est élevé sous un voile de levures et vendu en clavelin de 62 cl ?", r: "Le vin jaune" },
        { q: "Quel cépage blanc typiquement jurassien entre dans la composition du vin jaune ?", r: "Le savagnin" },
        { q: "Quel vin de paille jurassien est obtenu par le séchage des raisins sur des claies avant pressurage ?", r: "Le vin de paille" },
      ],
    },
    {
      theme: "Les instruments de mesure",
      questions: [
        { q: "Quel instrument à mâchoires coulissantes sert à mesurer des épaisseurs avec précision ?", r: "Le pied à coulisse" },
        { q: "Quel instrument mesure la pression atmosphérique grâce à une colonne de mercure ?", r: "Le baromètre" },
        { q: "Quel instrument de mesure optique, inventé par Amici, sert à déterminer l'indice de réfraction d'un liquide ?", r: "Le réfractomètre" },
        { q: "Quel instrument de précision mesure les angles horizontaux et verticaux en topographie ?", r: "Le théodolite" },
      ],
    },
    {
      theme: "La Normandie",
      questions: [
        { q: "Quelle tapisserie du XIe siècle, conservée à Bayeux, raconte la conquête de l'Angleterre ?", r: "La tapisserie de Bayeux" },
        { q: "Quel dessert normand à base de riz au lait cuit au four avec de la cannelle s'appelle la... ?", r: "La teurgoule" },
        { q: "Quelle brioche normande, aplatie et dorée, accompagne traditionnellement la teurgoule ?", r: "La fallue" },
        { q: "Quelle rivière de Normandie, longue de 225 km, passe à Lisieux et se jette à Honfleur ?", r: "La Touques" },
      ],
    },
    {
      theme: "L'opéra baroque",
      questions: [
        { q: "Quel opéra de Monteverdi, créé à Mantoue en 1607, est le premier chef-d'œuvre du genre ?", r: "L'Orfeo" },
        { q: "Quel compositeur français du XVIIe siècle, né à Florence, créa la tragédie en musique à la cour de Louis XIV ?", r: "Lully (Jean-Baptiste Lully)" },
        { q: "Quel opéra de Rameau, créé en 1733, met en scène Diane, Phèdre et Hippolyte ?", r: "Hippolyte et Aricie" },
        { q: "Quel opéra de Purcell, le seul véritable opéra anglais du XVIIe siècle, raconte l'histoire de la reine de Carthage ?", r: "Didon et Énée" },
      ],
    },
    {
      theme: "Les philosophes présocratiques",
      questions: [
        { q: "Quel philosophe de Milet est souvent cité comme le premier philosophe occidental ?", r: "Thalès" },
        { q: "Quel philosophe est surnommé l'Obscur en raison de la difficulté de sa pensée sur le changement ?", r: "Héraclite" },
        { q: "Quel philosophe d'Élée formula les paradoxes de la flèche et d'Achille et la tortue ?", r: "Zénon d'Élée" },
        { q: "Quel philosophe d'Abdère, contemporain de Socrate, postula que tout est composé d'atomes et de vide ?", r: "Démocrite" },
      ],
    },
    {
      theme: "Les traités historiques",
      questions: [
        { q: "Quel traité de 1648 mit fin à la guerre de Trente Ans ?", r: "Les traités de Westphalie" },
        { q: "Quel traité de 1713 mit fin à la guerre de Succession d'Espagne ?", r: "Le traité d'Utrecht" },
        { q: "Quel accord secret de 1916 divisa le Moyen-Orient entre la France et le Royaume-Uni ?", r: "Les accords Sykes-Picot" },
        { q: "Quel traité de 1957 institua la Communauté économique européenne entre six États ?", r: "Le traité de Rome" },
      ],
    },
    {
      theme: "La botanique",
      questions: [
        { q: "Quel terme botanique désigne le fruit charnu à noyau comme la cerise ou la pêche ?", r: "Une drupe" },
        { q: "Quel tissu conducteur transporte la sève brute des racines aux feuilles ?", r: "Le xylème" },
        { q: "Quel adjectif désigne un organisme dont l'appareil reproducteur n'est pas apparent ?", r: "Cryptogame" },
        { q: "Quel mot issu du grec désigne le mode de dispersion des graines par le vent ?", r: "L'anémochorie" },
      ],
    },
    {
      theme: "Le cinéma français des années 1930",
      questions: [
        { q: "Quel film de Jean Renoir de 1937 met en scène des prisonniers français pendant la Grande Guerre ?", r: "La Grande Illusion" },
        { q: "Quel film de Marcel Carné de 1938 voit Jean Gabin incarner un déserteur au Havre ?", r: "Quai des Brumes" },
        { q: "Quelle réplique culte Michèle Morgan adresse-t-elle à Jean Gabin dans ce film ?", r: "T'as de beaux yeux, tu sais" },
        { q: "Quel scénariste et poète écrivit les dialogues de Quai des Brumes, Les Enfants du paradis et Drôle de drame ?", r: "Jacques Prévert" },
      ],
    },
    {
      theme: "L'alchimie et ses symboles",
      questions: [
        { q: "Quel métal précieux les alchimistes cherchaient-ils à produire à partir de métaux vils ?", r: "L'or" },
        { q: "Quel objet mythique devait permettre la transmutation des métaux en or ?", r: "La pierre philosophale" },
        { q: "Quel four tirant son nom d'un mot arabe devait permettre de réaliser cette transmutation ?", r: "L'athanor" },
        { q: "Quel terme alchimique, du grec chrysopoeia, désigne l'art de fabriquer de l'or ?", r: "La chrysopée" },
      ],
    },
    {
      theme: "Les peintres de la Renaissance italienne",
      questions: [
        { q: "Quel peintre florentin du Quattrocento est l'auteur du Printemps et de La Naissance de Vénus ?", r: "Botticelli" },
        { q: "À quel peintre, né Pietro Vannucci et maître de Raphaël, doit-on l'Annonciation de Fano ?", r: "Le Pérugin" },
        { q: "Quel peintre vénitien, de son vrai nom Jacopo Robusti, est surnommé le Petit Teinturier ?", r: "Le Tintoret" },
        { q: "Quel peintre maniériste, né en Crète, travailla à Tolède et est connu sous un surnom signifiant « le Grec » ?", r: "Le Greco" },
      ],
    },
    {
      theme: "Les inventeurs français",
      questions: [
        { q: "Quel ingénieur, né à Châlons-sur-Marne en 1769, inventa la conservation des aliments en bocaux ?", r: "Nicolas Appert" },
        { q: "Quel ingénieur construisit le viaduc de Garabit dans le Cantal avant de réaliser sa tour parisienne ?", r: "Gustave Eiffel" },
        { q: "Quel ingénieur inventa le procédé de fabrication de l'aluminium par électrolyse en 1886 ?", r: "Paul Héroult" },
        { q: "Quel inventeur du XVIIIe siècle créa le réverbère, permettant l'éclairage public des rues ?", r: "Bourgeois de Châtaublanc" },
      ],
    },
    {
      theme: "La médecine et ses termes",
      questions: [
        { q: "Comment appelle-t-on l'inflammation de la muqueuse de l'estomac ?", r: "La gastrite" },
        { q: "Comment appelle-t-on l'inflammation du péricarde, l'enveloppe du cœur ?", r: "La péricardite" },
        { q: "Comment appelle-t-on l'inflammation de la vésicule biliaire ?", r: "La cholécystite" },
        { q: "Dans quel cas une femme peut-elle souffrir de dysménorrhées ?", r: "Lors des règles" },
      ],
    },
    {
      theme: "Les fleuves côtiers de France",
      questions: [
        { q: "Quel fleuve côtier du Languedoc passe à Béziers et se jette en Méditerranée à Agde ?", r: "L'Hérault" },
        { q: "Quel fleuve côtier de Provence traverse Aix-en-Provence et se jette dans l'étang de Berre ?", r: "L'Arc" },
        { q: "Quel affluent de la Loire passe à Blois et Vendôme et conflue à Angers, sans « e » final ?", r: "Le Loir" },
        { q: "Quelle rivière de Normandie passe à Lisieux et se jette dans la Manche à Honfleur ?", r: "La Touques" },
      ],
    },
    {
      theme: "Les prix Nobel de littérature",
      questions: [
        { q: "Quel écrivain suédois, prix Nobel 1909, est l'auteur de La Saga de Gösta Berlings ?", r: "Selma Lagerlöf" },
        { q: "Quel écrivain français, prix Nobel 1985, est l'auteur de Tropismes et de L'Usage de la parole ?", r: "Nathalie Sarraute" },
        { q: "Quel poète grec, prix Nobel 1963, est l'auteur du recueil Strophe ?", r: "Giorgos Séféris" },
        { q: "Quelle romancière autrichienne, prix Nobel 2004, est l'auteure de La Pianiste ?", r: "Elfriede Jelinek" },
      ],
    },
    {
      theme: "Les Causses et le Massif central",
      questions: [
        { q: "Comment appelle-t-on les plateaux calcaires arides du Languedoc parsemés d'avens et de grottes ?", r: "Les Causses" },
        { q: "Quel est le nom de la chaîne de volcans éteints dont le puy de Dôme culmine à 1 465 mètres ?", r: "La chaîne des Puys" },
        { q: "Quel terme d'auvergnat désigne la montée des troupeaux lors de la transhumance ?", r: "La montade" },
        { q: "Quelle rivière du Massif central, affluent de la Loire, passe à Vichy ?", r: "L'Allier" },
      ],
    },
  ],

  // ============================================
  // FACE À FACE - Indices progressifs (4 pts → 3 → 2 → 1)
  // ============================================
  faceAFace: [
    {
      theme: "Un courant artistique",
      indices: [
        "Style pictural dont l'appellation serait due à un vers du poème Au cabaret vert de Rimbaud.",
        "Malraux m'a opposé à l'art Vaudou lors de ses voyages à Haïti.",
        "Un musée m'est consacré à Laval, ville natale de mon principal représentant.",
        "Le douanier Rousseau est le plus célèbre de mes artistes, tous autodidactes.",
      ],
      reponse: "L'art naïf",
    },
    {
      theme: "Un personnage antique",
      indices: [
        "Poète et dramaturge contemporain de Pisistrate, j'apparais dans le prologue de l'opéra Platée de Rameau.",
        "Auteur des Jeunes gens et des Prêtres, je suis un personnage semi-légendaire du VIe siècle avant J.-C.",
        "On m'attribue l'invention du dialogue entre un acteur et le chœur lors des fêtes de Dionysos.",
        "En anglais, comédien peut se traduire par Thespian, dérivé de mon nom.",
      ],
      reponse: "Thespis",
    },
    {
      theme: "Un arbre",
      indices: [
        "Arbre de la famille des fabacées, je suis cité dans les paroles de la chanson Auprès de mon arbre de Brassens.",
        "Arbre cauliflore, mes fleurs roses apparaissent directement sur le tronc et les branches avant les feuilles.",
        "Aussi appelé gainier ou siliquastre, je suis un arbre ornemental très répandu dans les parcs.",
        "Selon une légende, c'est à cet arbre que Judas se serait pendu après sa trahison.",
      ],
      reponse: "L'arbre de Judée",
    },
    {
      theme: "Un insecte",
      indices: [
        "Arachnide de l'ordre des opilions, je ne suis pas venimeux et je suis même censé porter bonheur.",
        "Mon nom courant serait dû au fait que mes longues pattes ont le même mouvement qu'une faux.",
        "On me confond souvent avec une araignée, mais je n'ai qu'un seul segment corporel.",
        "Mon nom commun évoque le travail de celui qui coupe les blés.",
      ],
      reponse: "Le faucheux",
    },
    {
      theme: "Un scientifique",
      indices: [
        "Né en 1834, j'ai donné mon nom à un cratère lunaire et à une dorsale dans l'océan Arctique.",
        "Chimiste de formation, je fus professeur à l'université de Saint-Pétersbourg.",
        "En 1869, je classai les éléments chimiques par masse atomique croissante en laissant des cases vides pour des éléments encore inconnus.",
        "Ma classification périodique des éléments est toujours utilisée dans toutes les salles de chimie du monde.",
      ],
      reponse: "Mendeleïev",
    },
    {
      theme: "Un rite religieux",
      indices: [
        "Rite suivi d'un repas festif et de danses comme la hora, je célèbre un passage à l'âge adulte.",
        "Mon nom vient de l'araméen et signifie « fils du commandement ».",
        "Mon équivalent féminin est la bat-mitsvah.",
        "Je marque l'entrée dans la majorité religieuse du jeune garçon juif, à l'âge de 13 ans.",
      ],
      reponse: "La bar-mitsvah",
    },
    {
      theme: "Un homme politique français",
      indices: [
        "Né en 1891 à Saint-Chamond dans la Loire, j'exerçai longtemps la profession de chapelier.",
        "Maire de Saint-Chamond pendant plus de vingt ans, je fus également président du Conseil général de la Loire.",
        "Rappelé au pouvoir à 61 ans, je réussis à stabiliser le franc en 1952 sans hausse d'impôts.",
        "Mon nom reste associé à un emprunt obligataire de 1952 qui connut un succès populaire considérable.",
      ],
      reponse: "Antoine Pinay",
    },
    {
      theme: "Un légume",
      indices: [
        "Légume-racine de la famille des Brassicacées, je suis originaire des régions nordiques de l'Europe.",
        "Hybride naturel du chou et du navet, mon nom vient du suédois rotabagge.",
        "Introduit en France sous Louis XVI comme aliment de disette, je fus très consommé pendant les deux guerres.",
        "Ma chair jaune-orangée se consomme en purée, en soupe ou en gratin.",
      ],
      reponse: "Le rutabaga",
    },
    {
      theme: "Un mathématicien français",
      indices: [
        "Né à Paris en 1811, fils d'un notable républicain, je montrai des aptitudes extraordinaires pour les mathématiques.",
        "Refusé deux fois à l'École polytechnique, je fus emprisonné à Sainte-Pélagie pour mes activités républicaines.",
        "La veille de mon duel fatal, je rédigeai à la hâte une lettre résumant mes découvertes en théorie des groupes.",
        "Mort à 20 ans en 1832, mes travaux fondèrent ce qu'on appelle aujourd'hui la théorie qui porte mon nom.",
      ],
      reponse: "Évariste Galois",
    },
    {
      theme: "Un film français",
      indices: [
        "Tourné en 1938 en partie dans les studios de Joinville et dans les rues du Havre, mon titre a deux mots.",
        "Mon scénariste, Jacques Prévert, y glisse une atmosphère de fatalité et de brume.",
        "Jean Gabin y incarne un soldat déserteur traqué par la police.",
        "Michèle Morgan y prononce la réplique culte : « T'as de beaux yeux, tu sais. »",
      ],
      reponse: "Quai des Brumes",
    },
    {
      theme: "Un maréchal d'Empire",
      indices: [
        "Fils d'un aubergiste gascon, je m'engageai dans l'armée à 16 ans.",
        "Napoléon m'appelait affectueusement le « premier soldat de France » et me nomma duc de Montebello.",
        "Je fus le premier des maréchaux d'Empire à mourir au combat.",
        "Mortellement blessé à la cuisse par un boulet au pont d'Essling en 1809, je mourus dans les bras de Napoléon.",
      ],
      reponse: "Lannes (Jean Lannes)",
    },
    {
      theme: "Un peintre",
      indices: [
        "Né à Delft en 1632, je ne quittai presque jamais ma ville natale.",
        "Je travaillai avec une lenteur exceptionnelle, produisant seulement une quarantaine d'œuvres en toute ma vie.",
        "Mon commanditaire principal fut Pieter van Ruijven.",
        "Ma Laitière et ma Vue de Delft sont parmi les tableaux les plus admirés au monde.",
      ],
      reponse: "Johannes Vermeer",
    },
    {
      theme: "Un scientifique",
      indices: [
        "Né à Brno en 1822, fils de paysan silésien, j'entrai au monastère des Augustins.",
        "Pendant dix ans, je cultivai des milliers de pieds de pois en faisant varier couleur et forme des graines.",
        "Je présentai mes résultats en 1865 à la Société d'histoire naturelle de Brno, mais ils passèrent inaperçus.",
        "Redécouvertes en 1900, mes lois sur l'hérédité fondèrent la génétique.",
      ],
      reponse: "Gregor Mendel",
    },
    {
      theme: "Un compositeur",
      indices: [
        "Né à Hambourg en 1833, je passai la majeure partie de ma vie à Vienne.",
        "Je défendis une conception absolue de la musique, opposée au drame wagnérien.",
        "J'écrivis quatre symphonies, un Double Concerto pour violon et violoncelle et un Requiem allemand.",
        "Mes Danses hongroises et mon Requiem créé à Brême en 1868 sont parmi mes œuvres les plus connues.",
      ],
      reponse: "Johannes Brahms",
    },
    {
      theme: "Un général antique",
      indices: [
        "Né à Carthage vers 247 avant J.-C., fils du général Hamilcar Barca, je grandis en Ibérie.",
        "En 218 avant J.-C., je quittai Carthagène avec 40 000 hommes et 37 éléphants pour envahir l'Italie.",
        "J'infligeai à Rome ses pires défaites à la Trébie, au lac Trasimène et à Cannes.",
        "Je fus finalement vaincu à Zama en 202 avant J.-C. par Scipion l'Africain.",
      ],
      reponse: "Hannibal Barca",
    },
    {
      theme: "Une invention",
      indices: [
        "Rendue publique le 7 janvier 1839 lors d'une séance de l'Académie des sciences.",
        "Elle utilise une plaque d'argent poli exposée à des vapeurs d'iode pour créer une image unique.",
        "Son inventeur s'associa avec Nicéphore Niépce, auteur de la première image fixe connue en 1826.",
        "Cette invention révolutionna la représentation du réel et porta le nom de Louis Daguerre.",
      ],
      reponse: "Le daguerréotype",
    },
    {
      theme: "Un philosophe",
      indices: [
        "Né à Königsberg en 1724, je ne quittai pratiquement jamais ma ville natale.",
        "J'opérai ce que j'appelais moi-même une « révolution copernicienne » en philosophie.",
        "Je formulai l'impératif catégorique : agir selon la maxime dont on peut vouloir qu'elle devienne loi universelle.",
        "Ma Critique de la raison pure, publiée en 1781, est l'un des textes fondateurs de la philosophie moderne.",
      ],
      reponse: "Emmanuel Kant",
    },
    {
      theme: "Un monument parisien",
      indices: [
        "Commandé par Louis XIV à Jules Hardouin-Mansart en 1676, je fus achevé en 1708.",
        "Ma façade classique au dôme doré domine l'esplanade du même nom au cœur du 7e arrondissement.",
        "J'abrite depuis 1840 le tombeau de Napoléon Ier sous une coupole de porphyre rouge.",
        "Fondé comme hôpital militaire royal, j'accueille encore aujourd'hui des pensionnaires invalides.",
      ],
      reponse: "L'hôtel des Invalides",
    },
    {
      theme: "Un écrivain russe",
      indices: [
        "Né en 1821, je fus condamné à mort en 1849 puis gracié au pied du peloton d'exécution.",
        "Cette expérience marqua profondément mon œuvre sur les bagnards et les maladies de l'âme.",
        "Mes romans explorent la souffrance, le mal, la culpabilité et la foi.",
        "Crime et Châtiment, L'Idiot et Les Frères Karamazov sont mes œuvres les plus célèbres.",
      ],
      reponse: "Fiodor Dostoïevski",
    },
    {
      theme: "Un traité",
      indices: [
        "Signé simultanément dans deux villes de Westphalie le 24 octobre 1648.",
        "Il mit fin à la guerre de Trente Ans qui ravageait l'Europe centrale depuis 1618.",
        "Il consacra l'indépendance des cantons suisses et des Provinces-Unies.",
        "Il est considéré comme l'acte fondateur du système moderne des relations entre États souverains.",
      ],
      reponse: "Les traités de Westphalie",
    },
  ],
};
